/*
 * Autogenerated file
 * Copyright (c) 2025 BFLB Pinctrl Generator <nandojve@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef DT_BINDINGS_PINCTRL_BFLB_BL61X_PINCTRL_H_
#define DT_BINDINGS_PINCTRL_BFLB_BL61X_PINCTRL_H_

#define BFLB_PINMUX_FUN_INST_sdh                        0x0000
#define BFLB_PINMUX_FUN_INST_spi                        0x0001
#define BFLB_PINMUX_FUN_INST_flash0                     0x0002
#define BFLB_PINMUX_FUN_INST_flash1                     0x0102
#define BFLB_PINMUX_FUN_INST_flash2                     0x0202
#define BFLB_PINMUX_FUN_INST_i2s0                       0x0003
#define BFLB_PINMUX_FUN_INST_pdm                        0x0004
#define BFLB_PINMUX_FUN_INST_i2c0                       0x0005
#define BFLB_PINMUX_FUN_INST_i2c1                       0x0106
#define BFLB_PINMUX_FUN_INST_uart0                      0x0007
#define BFLB_PINMUX_FUN_INST_emac                       0x0008
#define BFLB_PINMUX_FUN_INST_cam0                       0x0009
#define BFLB_PINMUX_FUN_INST_cam1                       0x0109
#define BFLB_PINMUX_FUN_INST_analog                     0x000a
#define BFLB_PINMUX_FUN_INST_swgpio                     0x000b
#define BFLB_PINMUX_FUN_INST_gpio                       0x000b
#define BFLB_PINMUX_FUN_INST_sdio                       0x000c
#define BFLB_PINMUX_FUN_INST_pwm0                       0x0010
#define BFLB_PINMUX_FUN_INST_jtag                       0x0011
#define BFLB_PINMUX_FUN_INST_uart1                      0x0112
#define BFLB_PINMUX_FUN_INST_pwm1                       0x0113
#define BFLB_PINMUX_FUN_INST_spi1                       0x0114
#define BFLB_PINMUX_FUN_INST_i2s1                       0x0115
#define BFLB_PINMUX_FUN_INST_dbi_b                      0x0016
#define BFLB_PINMUX_FUN_INST_dbi_c                      0x0017
#define BFLB_PINMUX_FUN_INST_qspi                       0x0018
#define BFLB_PINMUX_FUN_INST_audac                      0x0019
#define BFLB_PINMUX_FUN_INST_clock_out                  0x001f

#define BFLB_PINMUX_SIGNAL_blck                         0x00
#define BFLB_PINMUX_SIGNAL_bclk                         0x00
#define BFLB_PINMUX_SIGNAL_ch9                          0x00
#define BFLB_PINMUX_SIGNAL_cts                          0x01
#define BFLB_PINMUX_SIGNAL_ch0p                         0x00
#define BFLB_PINMUX_SIGNAL_ch8                          0x00
#define BFLB_PINMUX_SIGNAL_ch1p                         0x00
#define BFLB_PINMUX_SIGNAL_ch2                          0x00
#define BFLB_PINMUX_SIGNAL_ch2p                         0x00
#define BFLB_PINMUX_SIGNAL_ch3p                         0x00
#define BFLB_PINMUX_SIGNAL_cs                           0x00
#define BFLB_PINMUX_SIGNAL_clk                          0x00
#define BFLB_PINMUX_SIGNAL_ch7                          0x00
#define BFLB_PINMUX_SIGNAL_ch6                          0x00
#define BFLB_PINMUX_SIGNAL_cmd                          0x00
#define BFLB_PINMUX_SIGNAL_ch5                          0x00
#define BFLB_PINMUX_SIGNAL_ch4                          0x00
#define BFLB_PINMUX_SIGNAL_ch0                          0x00
#define BFLB_PINMUX_SIGNAL_ch10                         0x00
#define BFLB_PINMUX_SIGNAL_di                           0x00
#define BFLB_PINMUX_SIGNAL_do                           0x00
#define BFLB_PINMUX_SIGNAL_dat0                         0x00
#define BFLB_PINMUX_SIGNAL_d1                           0x00
#define BFLB_PINMUX_SIGNAL_d2                           0x00
#define BFLB_PINMUX_SIGNAL_d0                           0x00
#define BFLB_PINMUX_SIGNAL_d3                           0x00
#define BFLB_PINMUX_SIGNAL_dat1                         0x00
#define BFLB_PINMUX_SIGNAL_dat2                         0x00
#define BFLB_PINMUX_SIGNAL_dat3                         0x00
#define BFLB_PINMUX_SIGNAL_dat4                         0x00
#define BFLB_PINMUX_SIGNAL_dat6                         0x00
#define BFLB_PINMUX_SIGNAL_dat7                         0x00
#define BFLB_PINMUX_SIGNAL_dat5                         0x00
#define BFLB_PINMUX_SIGNAL_fs                           0x00
#define BFLB_PINMUX_SIGNAL_hsync                        0x00
#define BFLB_PINMUX_SIGNAL_in                           0x00
#define BFLB_PINMUX_SIGNAL_miso                         0x00
#define BFLB_PINMUX_SIGNAL_mosi                         0x00
#define BFLB_PINMUX_SIGNAL_mdc                          0x00
#define BFLB_PINMUX_SIGNAL_mdio                         0x00
#define BFLB_PINMUX_SIGNAL_n                            0x00
#define BFLB_PINMUX_SIGNAL_p                            0x00
#define BFLB_PINMUX_SIGNAL_rts                          0x00
#define BFLB_PINMUX_SIGNAL_rx                           0x03
#define BFLB_PINMUX_SIGNAL_ref_clk                      0x00
#define BFLB_PINMUX_SIGNAL_rxd0                         0x00
#define BFLB_PINMUX_SIGNAL_rxd1                         0x00
#define BFLB_PINMUX_SIGNAL_rxerr                        0x00
#define BFLB_PINMUX_SIGNAL_rx_dv                        0x00
#define BFLB_PINMUX_SIGNAL_ss                           0x00
#define BFLB_PINMUX_SIGNAL_scl                          0x00
#define BFLB_PINMUX_SIGNAL_sclk                         0x00
#define BFLB_PINMUX_SIGNAL_sda                          0x00
#define BFLB_PINMUX_SIGNAL_sda0                         0x00
#define BFLB_PINMUX_SIGNAL_sda1                         0x00
#define BFLB_PINMUX_SIGNAL_sda2                         0x00
#define BFLB_PINMUX_SIGNAL_sda3                         0x00
#define BFLB_PINMUX_SIGNAL_tx                           0x02
#define BFLB_PINMUX_SIGNAL_tms                          0x00
#define BFLB_PINMUX_SIGNAL_tck                          0x00
#define BFLB_PINMUX_SIGNAL_tdo                          0x00
#define BFLB_PINMUX_SIGNAL_tdi                          0x00
#define BFLB_PINMUX_SIGNAL_txd0                         0x00
#define BFLB_PINMUX_SIGNAL_txd1                         0x00
#define BFLB_PINMUX_SIGNAL_tx_en                        0x00
#define BFLB_PINMUX_SIGNAL_vsync                        0x00

#endif /* DT_BINDINGS_PINCTRL_BFLB_BL61X_PINCTRL_H_ */
