/*
 * Autogenerated file
 * Copyright (c) 2026 BFLB Pinctrl Generator <nandojve@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef DT_BINDINGS_PINCTRL_BFLB_BL616CL32X_PINCTRL_H_
#define DT_BINDINGS_PINCTRL_BFLB_BL616CL32X_PINCTRL_H_

#include <dt-bindings/pinctrl/bl616cl-pinctrl.h>
#include <dt-bindings/pinctrl/bflb-common-pinctrl.h>

/* gpio4_spi0_ss */
#define GPIO4_SPI0_SS \
	BFLB_PINMUX(4, spi0, ss, periph)

/* gpio4_i2s_bclk */
#define GPIO4_I2S_BCLK \
	BFLB_PINMUX(4, i2s, bclk, periph)

/* gpio4_i2c0_scl */
#define GPIO4_I2C0_SCL \
	BFLB_PINMUX(4, i2c0, scl, periph)

/* gpio4_i2c1_scl */
#define GPIO4_I2C1_SCL \
	BFLB_PINMUX(4, i2c1, scl, periph)

/* gpio4_uart0_rts */
#define GPIO4_UART0_RTS \
	BFLB_PINMUX(4, uart0, rts, periph)

/* gpio4_uart0_cts */
#define GPIO4_UART0_CTS \
	BFLB_PINMUX(4, uart0, cts, periph)

/* gpio4_uart0_tx */
#define GPIO4_UART0_TX \
	BFLB_PINMUX(4, uart0, tx, periph)

/* gpio4_uart0_rx */
#define GPIO4_UART0_RX \
	BFLB_PINMUX(4, uart0, rx, periph)

/* gpio4_uart1_rts */
#define GPIO4_UART1_RTS \
	BFLB_PINMUX(4, uart1, rts, periph)

/* gpio4_uart1_cts */
#define GPIO4_UART1_CTS \
	BFLB_PINMUX(4, uart1, cts, periph)

/* gpio4_uart1_tx */
#define GPIO4_UART1_TX \
	BFLB_PINMUX(4, uart1, tx, periph)

/* gpio4_uart1_rx */
#define GPIO4_UART1_RX \
	BFLB_PINMUX(4, uart1, rx, periph)

/* gpio4_uart2_rts */
#define GPIO4_UART2_RTS \
	BFLB_PINMUX(4, uart2, rts, periph)

/* gpio4_uart2_cts */
#define GPIO4_UART2_CTS \
	BFLB_PINMUX(4, uart2, cts, periph)

/* gpio4_uart2_tx */
#define GPIO4_UART2_TX \
	BFLB_PINMUX(4, uart2, tx, periph)

/* gpio4_uart2_rx */
#define GPIO4_UART2_RX \
	BFLB_PINMUX(4, uart2, rx, periph)

/* gpio4_pwm0_ch0p */
#define GPIO4_PWM0_CH0P \
	BFLB_PINMUX(4, pwm0, ch0p, periph)

/* gpio4_spi1_ss */
#define GPIO4_SPI1_SS \
	BFLB_PINMUX(4, spi1, ss, periph)

/* gpio4_dbi_c_sda */
#define GPIO4_DBI_C_SDA \
	BFLB_PINMUX(4, dbi_c, sda, periph)

/* gpio4_jtag_tms */
#define GPIO4_JTAG_TMS \
	BFLB_PINMUX(4, jtag, tms, periph)

/* gpio4_clock_out0_cam_ref */
#define GPIO4_CLOCK_OUT0_CAM_REF \
	BFLB_PINMUX(4, clock_out0, cam_ref, periph)

/* gpio4_clock_out0_i2s_ref */
#define GPIO4_CLOCK_OUT0_I2S_REF \
	BFLB_PINMUX(4, clock_out0, i2s_ref, periph)

/* gpio4_clock_out0_solo_in_128fs */
#define GPIO4_CLOCK_OUT0_SOLO_IN_128FS \
	BFLB_PINMUX(4, clock_out0, solo_in_128fs, periph)

/* gpio4_adc_ch4 */
#define GPIO4_ADC_CH4 \
	BFLB_PINMUX(4, adc, ch4, analog)

/* gpio5_spi0_sclk */
#define GPIO5_SPI0_SCLK \
	BFLB_PINMUX(5, spi0, sclk, periph)

/* gpio5_i2s_fs */
#define GPIO5_I2S_FS \
	BFLB_PINMUX(5, i2s, fs, periph)

/* gpio5_i2c0_sda */
#define GPIO5_I2C0_SDA \
	BFLB_PINMUX(5, i2c0, sda, periph)

/* gpio5_i2c1_sda */
#define GPIO5_I2C1_SDA \
	BFLB_PINMUX(5, i2c1, sda, periph)

/* gpio5_uart0_rts */
#define GPIO5_UART0_RTS \
	BFLB_PINMUX(5, uart0, rts, periph)

/* gpio5_uart0_cts */
#define GPIO5_UART0_CTS \
	BFLB_PINMUX(5, uart0, cts, periph)

/* gpio5_uart0_tx */
#define GPIO5_UART0_TX \
	BFLB_PINMUX(5, uart0, tx, periph)

/* gpio5_uart0_rx */
#define GPIO5_UART0_RX \
	BFLB_PINMUX(5, uart0, rx, periph)

/* gpio5_uart1_rts */
#define GPIO5_UART1_RTS \
	BFLB_PINMUX(5, uart1, rts, periph)

/* gpio5_uart1_cts */
#define GPIO5_UART1_CTS \
	BFLB_PINMUX(5, uart1, cts, periph)

/* gpio5_uart1_tx */
#define GPIO5_UART1_TX \
	BFLB_PINMUX(5, uart1, tx, periph)

/* gpio5_uart1_rx */
#define GPIO5_UART1_RX \
	BFLB_PINMUX(5, uart1, rx, periph)

/* gpio5_uart2_rts */
#define GPIO5_UART2_RTS \
	BFLB_PINMUX(5, uart2, rts, periph)

/* gpio5_uart2_cts */
#define GPIO5_UART2_CTS \
	BFLB_PINMUX(5, uart2, cts, periph)

/* gpio5_uart2_tx */
#define GPIO5_UART2_TX \
	BFLB_PINMUX(5, uart2, tx, periph)

/* gpio5_uart2_rx */
#define GPIO5_UART2_RX \
	BFLB_PINMUX(5, uart2, rx, periph)

/* gpio5_pwm0_ch1p */
#define GPIO5_PWM0_CH1P \
	BFLB_PINMUX(5, pwm0, ch1p, periph)

/* gpio5_spi1_sclk */
#define GPIO5_SPI1_SCLK \
	BFLB_PINMUX(5, spi1, sclk, periph)

/* gpio5_dbi_c_dc */
#define GPIO5_DBI_C_DC \
	BFLB_PINMUX(5, dbi_c, dc, periph)

/* gpio5_jtag_tck */
#define GPIO5_JTAG_TCK \
	BFLB_PINMUX(5, jtag, tck, periph)

/* gpio5_clock_out1_cam_ref */
#define GPIO5_CLOCK_OUT1_CAM_REF \
	BFLB_PINMUX(5, clock_out1, cam_ref, periph)

/* gpio5_clock_out1_i2s_ref */
#define GPIO5_CLOCK_OUT1_I2S_REF \
	BFLB_PINMUX(5, clock_out1, i2s_ref, periph)

/* gpio5_clock_out1_solo_in_128fs */
#define GPIO5_CLOCK_OUT1_SOLO_IN_128FS \
	BFLB_PINMUX(5, clock_out1, solo_in_128fs, periph)

/* gpio5_adc_ch5 */
#define GPIO5_ADC_CH5 \
	BFLB_PINMUX(5, adc, ch5, analog)

/* gpio6_sdh_dat2 */
#define GPIO6_SDH_DAT2 \
	BFLB_PINMUX(6, sdh, dat2, periph)

/* gpio6_spi0_miso */
#define GPIO6_SPI0_MISO \
	BFLB_PINMUX(6, spi0, miso, periph)

/* gpio6_sf2_cs */
#define GPIO6_SF2_CS \
	BFLB_PINMUX(6, sf2, cs, periph)

/* gpio6_i2s_di */
#define GPIO6_I2S_DI \
	BFLB_PINMUX(6, i2s, di, periph)

/* gpio6_i2c0_scl */
#define GPIO6_I2C0_SCL \
	BFLB_PINMUX(6, i2c0, scl, periph)

/* gpio6_i2c1_scl */
#define GPIO6_I2C1_SCL \
	BFLB_PINMUX(6, i2c1, scl, periph)

/* gpio6_uart0_rts */
#define GPIO6_UART0_RTS \
	BFLB_PINMUX(6, uart0, rts, periph)

/* gpio6_uart0_cts */
#define GPIO6_UART0_CTS \
	BFLB_PINMUX(6, uart0, cts, periph)

/* gpio6_uart0_tx */
#define GPIO6_UART0_TX \
	BFLB_PINMUX(6, uart0, tx, periph)

/* gpio6_uart0_rx */
#define GPIO6_UART0_RX \
	BFLB_PINMUX(6, uart0, rx, periph)

/* gpio6_uart1_rts */
#define GPIO6_UART1_RTS \
	BFLB_PINMUX(6, uart1, rts, periph)

/* gpio6_uart1_cts */
#define GPIO6_UART1_CTS \
	BFLB_PINMUX(6, uart1, cts, periph)

/* gpio6_uart1_tx */
#define GPIO6_UART1_TX \
	BFLB_PINMUX(6, uart1, tx, periph)

/* gpio6_uart1_rx */
#define GPIO6_UART1_RX \
	BFLB_PINMUX(6, uart1, rx, periph)

/* gpio6_uart2_rts */
#define GPIO6_UART2_RTS \
	BFLB_PINMUX(6, uart2, rts, periph)

/* gpio6_uart2_cts */
#define GPIO6_UART2_CTS \
	BFLB_PINMUX(6, uart2, cts, periph)

/* gpio6_uart2_tx */
#define GPIO6_UART2_TX \
	BFLB_PINMUX(6, uart2, tx, periph)

/* gpio6_uart2_rx */
#define GPIO6_UART2_RX \
	BFLB_PINMUX(6, uart2, rx, periph)

/* gpio6_sdio_dat2 */
#define GPIO6_SDIO_DAT2 \
	BFLB_PINMUX(6, sdio, dat2, periph)

/* gpio6_pwm0_ch2p */
#define GPIO6_PWM0_CH2P \
	BFLB_PINMUX(6, pwm0, ch2p, periph)

/* gpio6_spi1_miso */
#define GPIO6_SPI1_MISO \
	BFLB_PINMUX(6, spi1, miso, periph)

/* gpio6_dbi_c_scl */
#define GPIO6_DBI_C_SCL \
	BFLB_PINMUX(6, dbi_c, scl, periph)

/* gpio6_qspi_scl */
#define GPIO6_QSPI_SCL \
	BFLB_PINMUX(6, qspi, scl, periph)

/* gpio6_jtag_tdo */
#define GPIO6_JTAG_TDO \
	BFLB_PINMUX(6, jtag, tdo, periph)

/* gpio6_clock_out2_cam_ref */
#define GPIO6_CLOCK_OUT2_CAM_REF \
	BFLB_PINMUX(6, clock_out2, cam_ref, periph)

/* gpio6_clock_out2_i2s_ref */
#define GPIO6_CLOCK_OUT2_I2S_REF \
	BFLB_PINMUX(6, clock_out2, i2s_ref, periph)

/* gpio6_clock_out2_xtal */
#define GPIO6_CLOCK_OUT2_XTAL \
	BFLB_PINMUX(6, clock_out2, xtal, periph)

/* gpio6_clock_out2_wifipll_32m */
#define GPIO6_CLOCK_OUT2_WIFIPLL_32M \
	BFLB_PINMUX(6, clock_out2, wifipll_32m, periph)

/* gpio6_adc_ch6 */
#define GPIO6_ADC_CH6 \
	BFLB_PINMUX(6, adc, ch6, analog)

/* gpio7_sdh_dat3 */
#define GPIO7_SDH_DAT3 \
	BFLB_PINMUX(7, sdh, dat3, periph)

/* gpio7_spi0_mosi */
#define GPIO7_SPI0_MOSI \
	BFLB_PINMUX(7, spi0, mosi, periph)

/* gpio7_sf2_d1 */
#define GPIO7_SF2_D1 \
	BFLB_PINMUX(7, sf2, d1, periph)

/* gpio7_i2s_do */
#define GPIO7_I2S_DO \
	BFLB_PINMUX(7, i2s, do, periph)

/* gpio7_i2c0_sda */
#define GPIO7_I2C0_SDA \
	BFLB_PINMUX(7, i2c0, sda, periph)

/* gpio7_i2c1_sda */
#define GPIO7_I2C1_SDA \
	BFLB_PINMUX(7, i2c1, sda, periph)

/* gpio7_uart0_rts */
#define GPIO7_UART0_RTS \
	BFLB_PINMUX(7, uart0, rts, periph)

/* gpio7_uart0_cts */
#define GPIO7_UART0_CTS \
	BFLB_PINMUX(7, uart0, cts, periph)

/* gpio7_uart0_tx */
#define GPIO7_UART0_TX \
	BFLB_PINMUX(7, uart0, tx, periph)

/* gpio7_uart0_rx */
#define GPIO7_UART0_RX \
	BFLB_PINMUX(7, uart0, rx, periph)

/* gpio7_uart1_rts */
#define GPIO7_UART1_RTS \
	BFLB_PINMUX(7, uart1, rts, periph)

/* gpio7_uart1_cts */
#define GPIO7_UART1_CTS \
	BFLB_PINMUX(7, uart1, cts, periph)

/* gpio7_uart1_tx */
#define GPIO7_UART1_TX \
	BFLB_PINMUX(7, uart1, tx, periph)

/* gpio7_uart1_rx */
#define GPIO7_UART1_RX \
	BFLB_PINMUX(7, uart1, rx, periph)

/* gpio7_uart2_rts */
#define GPIO7_UART2_RTS \
	BFLB_PINMUX(7, uart2, rts, periph)

/* gpio7_uart2_cts */
#define GPIO7_UART2_CTS \
	BFLB_PINMUX(7, uart2, cts, periph)

/* gpio7_uart2_tx */
#define GPIO7_UART2_TX \
	BFLB_PINMUX(7, uart2, tx, periph)

/* gpio7_uart2_rx */
#define GPIO7_UART2_RX \
	BFLB_PINMUX(7, uart2, rx, periph)

/* gpio7_sdio_dat3 */
#define GPIO7_SDIO_DAT3 \
	BFLB_PINMUX(7, sdio, dat3, periph)

/* gpio7_pwm0_ch3p */
#define GPIO7_PWM0_CH3P \
	BFLB_PINMUX(7, pwm0, ch3p, periph)

/* gpio7_spi1_mosi */
#define GPIO7_SPI1_MOSI \
	BFLB_PINMUX(7, spi1, mosi, periph)

/* gpio7_dbi_c_cs */
#define GPIO7_DBI_C_CS \
	BFLB_PINMUX(7, dbi_c, cs, periph)

/* gpio7_qspi_cs */
#define GPIO7_QSPI_CS \
	BFLB_PINMUX(7, qspi, cs, periph)

/* gpio7_jtag_tdi */
#define GPIO7_JTAG_TDI \
	BFLB_PINMUX(7, jtag, tdi, periph)

/* gpio7_clock_out3_cam_ref */
#define GPIO7_CLOCK_OUT3_CAM_REF \
	BFLB_PINMUX(7, clock_out3, cam_ref, periph)

/* gpio7_clock_out3_i2s_ref */
#define GPIO7_CLOCK_OUT3_I2S_REF \
	BFLB_PINMUX(7, clock_out3, i2s_ref, periph)

/* gpio7_clock_out3_wifipll_48m */
#define GPIO7_CLOCK_OUT3_WIFIPLL_48M \
	BFLB_PINMUX(7, clock_out3, wifipll_48m, periph)

/* gpio7_adc_ch7 */
#define GPIO7_ADC_CH7 \
	BFLB_PINMUX(7, adc, ch7, analog)

/* gpio8_sdh_cmd */
#define GPIO8_SDH_CMD \
	BFLB_PINMUX(8, sdh, cmd, periph)

/* gpio8_spi0_ss */
#define GPIO8_SPI0_SS \
	BFLB_PINMUX(8, spi0, ss, periph)

/* gpio8_sf2_d2 */
#define GPIO8_SF2_D2 \
	BFLB_PINMUX(8, sf2, d2, periph)

/* gpio8_i2s_bclk */
#define GPIO8_I2S_BCLK \
	BFLB_PINMUX(8, i2s, bclk, periph)

/* gpio8_i2c0_scl */
#define GPIO8_I2C0_SCL \
	BFLB_PINMUX(8, i2c0, scl, periph)

/* gpio8_i2c1_scl */
#define GPIO8_I2C1_SCL \
	BFLB_PINMUX(8, i2c1, scl, periph)

/* gpio8_uart0_rts */
#define GPIO8_UART0_RTS \
	BFLB_PINMUX(8, uart0, rts, periph)

/* gpio8_uart0_cts */
#define GPIO8_UART0_CTS \
	BFLB_PINMUX(8, uart0, cts, periph)

/* gpio8_uart0_tx */
#define GPIO8_UART0_TX \
	BFLB_PINMUX(8, uart0, tx, periph)

/* gpio8_uart0_rx */
#define GPIO8_UART0_RX \
	BFLB_PINMUX(8, uart0, rx, periph)

/* gpio8_uart1_rts */
#define GPIO8_UART1_RTS \
	BFLB_PINMUX(8, uart1, rts, periph)

/* gpio8_uart1_cts */
#define GPIO8_UART1_CTS \
	BFLB_PINMUX(8, uart1, cts, periph)

/* gpio8_uart1_tx */
#define GPIO8_UART1_TX \
	BFLB_PINMUX(8, uart1, tx, periph)

/* gpio8_uart1_rx */
#define GPIO8_UART1_RX \
	BFLB_PINMUX(8, uart1, rx, periph)

/* gpio8_uart2_rts */
#define GPIO8_UART2_RTS \
	BFLB_PINMUX(8, uart2, rts, periph)

/* gpio8_uart2_cts */
#define GPIO8_UART2_CTS \
	BFLB_PINMUX(8, uart2, cts, periph)

/* gpio8_uart2_tx */
#define GPIO8_UART2_TX \
	BFLB_PINMUX(8, uart2, tx, periph)

/* gpio8_uart2_rx */
#define GPIO8_UART2_RX \
	BFLB_PINMUX(8, uart2, rx, periph)

/* gpio8_sdio_cmd */
#define GPIO8_SDIO_CMD \
	BFLB_PINMUX(8, sdio, cmd, periph)

/* gpio8_pwm0_ch0p */
#define GPIO8_PWM0_CH0P \
	BFLB_PINMUX(8, pwm0, ch0p, periph)

/* gpio8_spi1_ss */
#define GPIO8_SPI1_SS \
	BFLB_PINMUX(8, spi1, ss, periph)

/* gpio8_dbi_c_sda */
#define GPIO8_DBI_C_SDA \
	BFLB_PINMUX(8, dbi_c, sda, periph)

/* gpio8_qspi_sda0 */
#define GPIO8_QSPI_SDA0 \
	BFLB_PINMUX(8, qspi, sda0, periph)

/* gpio8_jtag_tms */
#define GPIO8_JTAG_TMS \
	BFLB_PINMUX(8, jtag, tms, periph)

/* gpio8_clock_out0_cam_ref */
#define GPIO8_CLOCK_OUT0_CAM_REF \
	BFLB_PINMUX(8, clock_out0, cam_ref, periph)

/* gpio8_clock_out0_i2s_ref */
#define GPIO8_CLOCK_OUT0_I2S_REF \
	BFLB_PINMUX(8, clock_out0, i2s_ref, periph)

/* gpio8_clock_out0_solo_in_128fs */
#define GPIO8_CLOCK_OUT0_SOLO_IN_128FS \
	BFLB_PINMUX(8, clock_out0, solo_in_128fs, periph)

/* gpio9_sdh_clk */
#define GPIO9_SDH_CLK \
	BFLB_PINMUX(9, sdh, clk, periph)

/* gpio9_spi0_sclk */
#define GPIO9_SPI0_SCLK \
	BFLB_PINMUX(9, spi0, sclk, periph)

/* gpio9_sf2_d0 */
#define GPIO9_SF2_D0 \
	BFLB_PINMUX(9, sf2, d0, periph)

/* gpio9_sf2_d3 */
#define GPIO9_SF2_D3 \
	BFLB_PINMUX(9, sf2, d3, periph)

/* gpio9_i2s_fs */
#define GPIO9_I2S_FS \
	BFLB_PINMUX(9, i2s, fs, periph)

/* gpio9_i2c0_sda */
#define GPIO9_I2C0_SDA \
	BFLB_PINMUX(9, i2c0, sda, periph)

/* gpio9_i2c1_sda */
#define GPIO9_I2C1_SDA \
	BFLB_PINMUX(9, i2c1, sda, periph)

/* gpio9_uart0_rts */
#define GPIO9_UART0_RTS \
	BFLB_PINMUX(9, uart0, rts, periph)

/* gpio9_uart0_cts */
#define GPIO9_UART0_CTS \
	BFLB_PINMUX(9, uart0, cts, periph)

/* gpio9_uart0_tx */
#define GPIO9_UART0_TX \
	BFLB_PINMUX(9, uart0, tx, periph)

/* gpio9_uart0_rx */
#define GPIO9_UART0_RX \
	BFLB_PINMUX(9, uart0, rx, periph)

/* gpio9_uart1_rts */
#define GPIO9_UART1_RTS \
	BFLB_PINMUX(9, uart1, rts, periph)

/* gpio9_uart1_cts */
#define GPIO9_UART1_CTS \
	BFLB_PINMUX(9, uart1, cts, periph)

/* gpio9_uart1_tx */
#define GPIO9_UART1_TX \
	BFLB_PINMUX(9, uart1, tx, periph)

/* gpio9_uart1_rx */
#define GPIO9_UART1_RX \
	BFLB_PINMUX(9, uart1, rx, periph)

/* gpio9_uart2_rts */
#define GPIO9_UART2_RTS \
	BFLB_PINMUX(9, uart2, rts, periph)

/* gpio9_uart2_cts */
#define GPIO9_UART2_CTS \
	BFLB_PINMUX(9, uart2, cts, periph)

/* gpio9_uart2_tx */
#define GPIO9_UART2_TX \
	BFLB_PINMUX(9, uart2, tx, periph)

/* gpio9_uart2_rx */
#define GPIO9_UART2_RX \
	BFLB_PINMUX(9, uart2, rx, periph)

/* gpio9_sdio_cmd */
#define GPIO9_SDIO_CMD \
	BFLB_PINMUX(9, sdio, cmd, periph)

/* gpio9_pwm0_ch1p */
#define GPIO9_PWM0_CH1P \
	BFLB_PINMUX(9, pwm0, ch1p, periph)

/* gpio9_spi1_sclk */
#define GPIO9_SPI1_SCLK \
	BFLB_PINMUX(9, spi1, sclk, periph)

/* gpio9_dbi_c_dc */
#define GPIO9_DBI_C_DC \
	BFLB_PINMUX(9, dbi_c, dc, periph)

/* gpio9_qspi_sda1 */
#define GPIO9_QSPI_SDA1 \
	BFLB_PINMUX(9, qspi, sda1, periph)

/* gpio9_jtag_tck */
#define GPIO9_JTAG_TCK \
	BFLB_PINMUX(9, jtag, tck, periph)

/* gpio9_clock_out1_cam_ref */
#define GPIO9_CLOCK_OUT1_CAM_REF \
	BFLB_PINMUX(9, clock_out1, cam_ref, periph)

/* gpio9_clock_out1_i2s_ref */
#define GPIO9_CLOCK_OUT1_I2S_REF \
	BFLB_PINMUX(9, clock_out1, i2s_ref, periph)

/* gpio9_clock_out1_solo_in_128fs */
#define GPIO9_CLOCK_OUT1_SOLO_IN_128FS \
	BFLB_PINMUX(9, clock_out1, solo_in_128fs, periph)

/* gpio10_sdh_dat0 */
#define GPIO10_SDH_DAT0 \
	BFLB_PINMUX(10, sdh, dat0, periph)

/* gpio10_spi0_miso */
#define GPIO10_SPI0_MISO \
	BFLB_PINMUX(10, spi0, miso, periph)

/* gpio10_sf2_clk */
#define GPIO10_SF2_CLK \
	BFLB_PINMUX(10, sf2, clk, periph)

/* gpio10_i2s_di */
#define GPIO10_I2S_DI \
	BFLB_PINMUX(10, i2s, di, periph)

/* gpio10_i2c0_scl */
#define GPIO10_I2C0_SCL \
	BFLB_PINMUX(10, i2c0, scl, periph)

/* gpio10_i2c1_scl */
#define GPIO10_I2C1_SCL \
	BFLB_PINMUX(10, i2c1, scl, periph)

/* gpio10_uart0_rts */
#define GPIO10_UART0_RTS \
	BFLB_PINMUX(10, uart0, rts, periph)

/* gpio10_uart0_cts */
#define GPIO10_UART0_CTS \
	BFLB_PINMUX(10, uart0, cts, periph)

/* gpio10_uart0_tx */
#define GPIO10_UART0_TX \
	BFLB_PINMUX(10, uart0, tx, periph)

/* gpio10_uart0_rx */
#define GPIO10_UART0_RX \
	BFLB_PINMUX(10, uart0, rx, periph)

/* gpio10_uart1_rts */
#define GPIO10_UART1_RTS \
	BFLB_PINMUX(10, uart1, rts, periph)

/* gpio10_uart1_cts */
#define GPIO10_UART1_CTS \
	BFLB_PINMUX(10, uart1, cts, periph)

/* gpio10_uart1_tx */
#define GPIO10_UART1_TX \
	BFLB_PINMUX(10, uart1, tx, periph)

/* gpio10_uart1_rx */
#define GPIO10_UART1_RX \
	BFLB_PINMUX(10, uart1, rx, periph)

/* gpio10_uart2_rts */
#define GPIO10_UART2_RTS \
	BFLB_PINMUX(10, uart2, rts, periph)

/* gpio10_uart2_cts */
#define GPIO10_UART2_CTS \
	BFLB_PINMUX(10, uart2, cts, periph)

/* gpio10_uart2_tx */
#define GPIO10_UART2_TX \
	BFLB_PINMUX(10, uart2, tx, periph)

/* gpio10_uart2_rx */
#define GPIO10_UART2_RX \
	BFLB_PINMUX(10, uart2, rx, periph)

/* gpio10_sdio_dat0 */
#define GPIO10_SDIO_DAT0 \
	BFLB_PINMUX(10, sdio, dat0, periph)

/* gpio10_pwm0_ch2p */
#define GPIO10_PWM0_CH2P \
	BFLB_PINMUX(10, pwm0, ch2p, periph)

/* gpio10_spi1_miso */
#define GPIO10_SPI1_MISO \
	BFLB_PINMUX(10, spi1, miso, periph)

/* gpio10_dbi_c_scl */
#define GPIO10_DBI_C_SCL \
	BFLB_PINMUX(10, dbi_c, scl, periph)

/* gpio10_qspi_sda2 */
#define GPIO10_QSPI_SDA2 \
	BFLB_PINMUX(10, qspi, sda2, periph)

/* gpio10_jtag_tdo */
#define GPIO10_JTAG_TDO \
	BFLB_PINMUX(10, jtag, tdo, periph)

/* gpio10_clock_out2_cam_ref */
#define GPIO10_CLOCK_OUT2_CAM_REF \
	BFLB_PINMUX(10, clock_out2, cam_ref, periph)

/* gpio10_clock_out2_i2s_ref */
#define GPIO10_CLOCK_OUT2_I2S_REF \
	BFLB_PINMUX(10, clock_out2, i2s_ref, periph)

/* gpio10_clock_out2_xtal */
#define GPIO10_CLOCK_OUT2_XTAL \
	BFLB_PINMUX(10, clock_out2, xtal, periph)

/* gpio10_clock_out2_wifipll_32m */
#define GPIO10_CLOCK_OUT2_WIFIPLL_32M \
	BFLB_PINMUX(10, clock_out2, wifipll_32m, periph)

/* gpio11_sdh_dat1 */
#define GPIO11_SDH_DAT1 \
	BFLB_PINMUX(11, sdh, dat1, periph)

/* gpio11_spi0_mosi */
#define GPIO11_SPI0_MOSI \
	BFLB_PINMUX(11, spi0, mosi, periph)

/* gpio11_sf2_d3 */
#define GPIO11_SF2_D3 \
	BFLB_PINMUX(11, sf2, d3, periph)

/* gpio11_sf2_d0 */
#define GPIO11_SF2_D0 \
	BFLB_PINMUX(11, sf2, d0, periph)

/* gpio11_i2s_do */
#define GPIO11_I2S_DO \
	BFLB_PINMUX(11, i2s, do, periph)

/* gpio11_i2c0_sda */
#define GPIO11_I2C0_SDA \
	BFLB_PINMUX(11, i2c0, sda, periph)

/* gpio11_i2c1_sda */
#define GPIO11_I2C1_SDA \
	BFLB_PINMUX(11, i2c1, sda, periph)

/* gpio11_uart0_rts */
#define GPIO11_UART0_RTS \
	BFLB_PINMUX(11, uart0, rts, periph)

/* gpio11_uart0_cts */
#define GPIO11_UART0_CTS \
	BFLB_PINMUX(11, uart0, cts, periph)

/* gpio11_uart0_tx */
#define GPIO11_UART0_TX \
	BFLB_PINMUX(11, uart0, tx, periph)

/* gpio11_uart0_rx */
#define GPIO11_UART0_RX \
	BFLB_PINMUX(11, uart0, rx, periph)

/* gpio11_uart1_rts */
#define GPIO11_UART1_RTS \
	BFLB_PINMUX(11, uart1, rts, periph)

/* gpio11_uart1_cts */
#define GPIO11_UART1_CTS \
	BFLB_PINMUX(11, uart1, cts, periph)

/* gpio11_uart1_tx */
#define GPIO11_UART1_TX \
	BFLB_PINMUX(11, uart1, tx, periph)

/* gpio11_uart1_rx */
#define GPIO11_UART1_RX \
	BFLB_PINMUX(11, uart1, rx, periph)

/* gpio11_uart2_rts */
#define GPIO11_UART2_RTS \
	BFLB_PINMUX(11, uart2, rts, periph)

/* gpio11_uart2_cts */
#define GPIO11_UART2_CTS \
	BFLB_PINMUX(11, uart2, cts, periph)

/* gpio11_uart2_tx */
#define GPIO11_UART2_TX \
	BFLB_PINMUX(11, uart2, tx, periph)

/* gpio11_uart2_rx */
#define GPIO11_UART2_RX \
	BFLB_PINMUX(11, uart2, rx, periph)

/* gpio11_sdio_dat1 */
#define GPIO11_SDIO_DAT1 \
	BFLB_PINMUX(11, sdio, dat1, periph)

/* gpio11_pwm0_ch3p */
#define GPIO11_PWM0_CH3P \
	BFLB_PINMUX(11, pwm0, ch3p, periph)

/* gpio11_dbi_c_cs */
#define GPIO11_DBI_C_CS \
	BFLB_PINMUX(11, dbi_c, cs, periph)

/* gpio11_qspi_sda3 */
#define GPIO11_QSPI_SDA3 \
	BFLB_PINMUX(11, qspi, sda3, periph)

/* gpio11_jtag_tdi */
#define GPIO11_JTAG_TDI \
	BFLB_PINMUX(11, jtag, tdi, periph)

/* gpio11_clock_out3_cam_ref */
#define GPIO11_CLOCK_OUT3_CAM_REF \
	BFLB_PINMUX(11, clock_out3, cam_ref, periph)

/* gpio11_clock_out3_i2s_ref */
#define GPIO11_CLOCK_OUT3_I2S_REF \
	BFLB_PINMUX(11, clock_out3, i2s_ref, periph)

/* gpio11_clock_out3_wifipll_48m */
#define GPIO11_CLOCK_OUT3_WIFIPLL_48M \
	BFLB_PINMUX(11, clock_out3, wifipll_48m, periph)

/* gpio12_spi0_ss */
#define GPIO12_SPI0_SS \
	BFLB_PINMUX(12, spi0, ss, periph)

/* gpio12_i2s_bclk */
#define GPIO12_I2S_BCLK \
	BFLB_PINMUX(12, i2s, bclk, periph)

/* gpio12_i2c0_scl */
#define GPIO12_I2C0_SCL \
	BFLB_PINMUX(12, i2c0, scl, periph)

/* gpio12_i2c1_scl */
#define GPIO12_I2C1_SCL \
	BFLB_PINMUX(12, i2c1, scl, periph)

/* gpio12_uart0_rts */
#define GPIO12_UART0_RTS \
	BFLB_PINMUX(12, uart0, rts, periph)

/* gpio12_uart0_cts */
#define GPIO12_UART0_CTS \
	BFLB_PINMUX(12, uart0, cts, periph)

/* gpio12_uart0_tx */
#define GPIO12_UART0_TX \
	BFLB_PINMUX(12, uart0, tx, periph)

/* gpio12_uart0_rx */
#define GPIO12_UART0_RX \
	BFLB_PINMUX(12, uart0, rx, periph)

/* gpio12_uart1_rts */
#define GPIO12_UART1_RTS \
	BFLB_PINMUX(12, uart1, rts, periph)

/* gpio12_uart1_cts */
#define GPIO12_UART1_CTS \
	BFLB_PINMUX(12, uart1, cts, periph)

/* gpio12_uart1_tx */
#define GPIO12_UART1_TX \
	BFLB_PINMUX(12, uart1, tx, periph)

/* gpio12_uart1_rx */
#define GPIO12_UART1_RX \
	BFLB_PINMUX(12, uart1, rx, periph)

/* gpio12_uart2_rts */
#define GPIO12_UART2_RTS \
	BFLB_PINMUX(12, uart2, rts, periph)

/* gpio12_uart2_cts */
#define GPIO12_UART2_CTS \
	BFLB_PINMUX(12, uart2, cts, periph)

/* gpio12_uart2_tx */
#define GPIO12_UART2_TX \
	BFLB_PINMUX(12, uart2, tx, periph)

/* gpio12_uart2_rx */
#define GPIO12_UART2_RX \
	BFLB_PINMUX(12, uart2, rx, periph)

/* gpio12_emac_mdio */
#define GPIO12_EMAC_MDIO \
	BFLB_PINMUX(12, emac, mdio, periph)

/* gpio12_cam0_dat0 */
#define GPIO12_CAM0_DAT0 \
	BFLB_PINMUX(12, cam0, dat0, periph)

/* gpio12_pwm0_ch0p */
#define GPIO12_PWM0_CH0P \
	BFLB_PINMUX(12, pwm0, ch0p, periph)

/* gpio12_spi1_ss */
#define GPIO12_SPI1_SS \
	BFLB_PINMUX(12, spi1, ss, periph)

/* gpio12_dbi_b_db0 */
#define GPIO12_DBI_B_DB0 \
	BFLB_PINMUX(12, dbi_b, db0, periph)

/* gpio12_dbi_c_sda */
#define GPIO12_DBI_C_SDA \
	BFLB_PINMUX(12, dbi_c, sda, periph)

/* gpio12_qspi_scl */
#define GPIO12_QSPI_SCL \
	BFLB_PINMUX(12, qspi, scl, periph)

/* gpio12_audac_p */
#define GPIO12_AUDAC_P \
	BFLB_PINMUX(12, audac, p, periph)

/* gpio12_jtag_tms */
#define GPIO12_JTAG_TMS \
	BFLB_PINMUX(12, jtag, tms, periph)

/* gpio12_clock_out0_cam_ref */
#define GPIO12_CLOCK_OUT0_CAM_REF \
	BFLB_PINMUX(12, clock_out0, cam_ref, periph)

/* gpio12_clock_out0_i2s_ref */
#define GPIO12_CLOCK_OUT0_I2S_REF \
	BFLB_PINMUX(12, clock_out0, i2s_ref, periph)

/* gpio12_clock_out0_solo_in_128fs */
#define GPIO12_CLOCK_OUT0_SOLO_IN_128FS \
	BFLB_PINMUX(12, clock_out0, solo_in_128fs, periph)

/* gpio12_adc_ch8 */
#define GPIO12_ADC_CH8 \
	BFLB_PINMUX(12, adc, ch8, analog)

/* gpio13_spi0_sclk */
#define GPIO13_SPI0_SCLK \
	BFLB_PINMUX(13, spi0, sclk, periph)

/* gpio13_i2s_fs */
#define GPIO13_I2S_FS \
	BFLB_PINMUX(13, i2s, fs, periph)

/* gpio13_i2c0_sda */
#define GPIO13_I2C0_SDA \
	BFLB_PINMUX(13, i2c0, sda, periph)

/* gpio13_i2c1_sda */
#define GPIO13_I2C1_SDA \
	BFLB_PINMUX(13, i2c1, sda, periph)

/* gpio13_uart0_rts */
#define GPIO13_UART0_RTS \
	BFLB_PINMUX(13, uart0, rts, periph)

/* gpio13_uart0_cts */
#define GPIO13_UART0_CTS \
	BFLB_PINMUX(13, uart0, cts, periph)

/* gpio13_uart0_tx */
#define GPIO13_UART0_TX \
	BFLB_PINMUX(13, uart0, tx, periph)

/* gpio13_uart0_rx */
#define GPIO13_UART0_RX \
	BFLB_PINMUX(13, uart0, rx, periph)

/* gpio13_uart1_rts */
#define GPIO13_UART1_RTS \
	BFLB_PINMUX(13, uart1, rts, periph)

/* gpio13_uart1_cts */
#define GPIO13_UART1_CTS \
	BFLB_PINMUX(13, uart1, cts, periph)

/* gpio13_uart1_tx */
#define GPIO13_UART1_TX \
	BFLB_PINMUX(13, uart1, tx, periph)

/* gpio13_uart1_rx */
#define GPIO13_UART1_RX \
	BFLB_PINMUX(13, uart1, rx, periph)

/* gpio13_uart2_rts */
#define GPIO13_UART2_RTS \
	BFLB_PINMUX(13, uart2, rts, periph)

/* gpio13_uart2_cts */
#define GPIO13_UART2_CTS \
	BFLB_PINMUX(13, uart2, cts, periph)

/* gpio13_uart2_tx */
#define GPIO13_UART2_TX \
	BFLB_PINMUX(13, uart2, tx, periph)

/* gpio13_uart2_rx */
#define GPIO13_UART2_RX \
	BFLB_PINMUX(13, uart2, rx, periph)

/* gpio13_emac_mdc */
#define GPIO13_EMAC_MDC \
	BFLB_PINMUX(13, emac, mdc, periph)

/* gpio13_cam0_dat1 */
#define GPIO13_CAM0_DAT1 \
	BFLB_PINMUX(13, cam0, dat1, periph)

/* gpio13_pwm0_ch1p */
#define GPIO13_PWM0_CH1P \
	BFLB_PINMUX(13, pwm0, ch1p, periph)

/* gpio13_spi1_sclk */
#define GPIO13_SPI1_SCLK \
	BFLB_PINMUX(13, spi1, sclk, periph)

/* gpio13_dbi_b_db1 */
#define GPIO13_DBI_B_DB1 \
	BFLB_PINMUX(13, dbi_b, db1, periph)

/* gpio13_dbi_c_dc */
#define GPIO13_DBI_C_DC \
	BFLB_PINMUX(13, dbi_c, dc, periph)

/* gpio13_qspi_cs */
#define GPIO13_QSPI_CS \
	BFLB_PINMUX(13, qspi, cs, periph)

/* gpio13_audac_n */
#define GPIO13_AUDAC_N \
	BFLB_PINMUX(13, audac, n, periph)

/* gpio13_jtag_tck */
#define GPIO13_JTAG_TCK \
	BFLB_PINMUX(13, jtag, tck, periph)

/* gpio13_clock_out1_cam_ref */
#define GPIO13_CLOCK_OUT1_CAM_REF \
	BFLB_PINMUX(13, clock_out1, cam_ref, periph)

/* gpio13_clock_out1_i2s_ref */
#define GPIO13_CLOCK_OUT1_I2S_REF \
	BFLB_PINMUX(13, clock_out1, i2s_ref, periph)

/* gpio13_clock_out1_solo_in_128fs */
#define GPIO13_CLOCK_OUT1_SOLO_IN_128FS \
	BFLB_PINMUX(13, clock_out1, solo_in_128fs, periph)

/* gpio13_adc_ch9 */
#define GPIO13_ADC_CH9 \
	BFLB_PINMUX(13, adc, ch9, analog)

/* gpio18_spi0_miso */
#define GPIO18_SPI0_MISO \
	BFLB_PINMUX(18, spi0, miso, periph)

/* gpio18_i2s_di */
#define GPIO18_I2S_DI \
	BFLB_PINMUX(18, i2s, di, periph)

/* gpio18_i2c0_scl */
#define GPIO18_I2C0_SCL \
	BFLB_PINMUX(18, i2c0, scl, periph)

/* gpio18_i2c1_scl */
#define GPIO18_I2C1_SCL \
	BFLB_PINMUX(18, i2c1, scl, periph)

/* gpio18_uart0_rts */
#define GPIO18_UART0_RTS \
	BFLB_PINMUX(18, uart0, rts, periph)

/* gpio18_uart0_cts */
#define GPIO18_UART0_CTS \
	BFLB_PINMUX(18, uart0, cts, periph)

/* gpio18_uart0_tx */
#define GPIO18_UART0_TX \
	BFLB_PINMUX(18, uart0, tx, periph)

/* gpio18_uart0_rx */
#define GPIO18_UART0_RX \
	BFLB_PINMUX(18, uart0, rx, periph)

/* gpio18_uart1_rts */
#define GPIO18_UART1_RTS \
	BFLB_PINMUX(18, uart1, rts, periph)

/* gpio18_uart1_cts */
#define GPIO18_UART1_CTS \
	BFLB_PINMUX(18, uart1, cts, periph)

/* gpio18_uart1_tx */
#define GPIO18_UART1_TX \
	BFLB_PINMUX(18, uart1, tx, periph)

/* gpio18_uart1_rx */
#define GPIO18_UART1_RX \
	BFLB_PINMUX(18, uart1, rx, periph)

/* gpio18_uart2_rts */
#define GPIO18_UART2_RTS \
	BFLB_PINMUX(18, uart2, rts, periph)

/* gpio18_uart2_cts */
#define GPIO18_UART2_CTS \
	BFLB_PINMUX(18, uart2, cts, periph)

/* gpio18_uart2_tx */
#define GPIO18_UART2_TX \
	BFLB_PINMUX(18, uart2, tx, periph)

/* gpio18_uart2_rx */
#define GPIO18_UART2_RX \
	BFLB_PINMUX(18, uart2, rx, periph)

/* gpio18_emac_rxd1 */
#define GPIO18_EMAC_RXD1 \
	BFLB_PINMUX(18, emac, rxd1, periph)

/* gpio18_cam0_dat6 */
#define GPIO18_CAM0_DAT6 \
	BFLB_PINMUX(18, cam0, dat6, periph)

/* gpio18_pwm0_ch2p */
#define GPIO18_PWM0_CH2P \
	BFLB_PINMUX(18, pwm0, ch2p, periph)

/* gpio18_spi1_miso */
#define GPIO18_SPI1_MISO \
	BFLB_PINMUX(18, spi1, miso, periph)

/* gpio18_dbi_b_db6 */
#define GPIO18_DBI_B_DB6 \
	BFLB_PINMUX(18, dbi_b, db6, periph)

/* gpio18_dbi_c_scl */
#define GPIO18_DBI_C_SCL \
	BFLB_PINMUX(18, dbi_c, scl, periph)

/* gpio18_qspi_scl */
#define GPIO18_QSPI_SCL \
	BFLB_PINMUX(18, qspi, scl, periph)

/* gpio18_audac_p */
#define GPIO18_AUDAC_P \
	BFLB_PINMUX(18, audac, p, periph)

/* gpio18_jtag_tdo */
#define GPIO18_JTAG_TDO \
	BFLB_PINMUX(18, jtag, tdo, periph)

/* gpio18_clock_out2_cam_ref */
#define GPIO18_CLOCK_OUT2_CAM_REF \
	BFLB_PINMUX(18, clock_out2, cam_ref, periph)

/* gpio18_clock_out2_i2s_ref */
#define GPIO18_CLOCK_OUT2_I2S_REF \
	BFLB_PINMUX(18, clock_out2, i2s_ref, periph)

/* gpio18_clock_out2_xtal */
#define GPIO18_CLOCK_OUT2_XTAL \
	BFLB_PINMUX(18, clock_out2, xtal, periph)

/* gpio18_clock_out2_wifipll_32m */
#define GPIO18_CLOCK_OUT2_WIFIPLL_32M \
	BFLB_PINMUX(18, clock_out2, wifipll_32m, periph)

/* gpio19_spi0_mosi */
#define GPIO19_SPI0_MOSI \
	BFLB_PINMUX(19, spi0, mosi, periph)

/* gpio19_i2s_do */
#define GPIO19_I2S_DO \
	BFLB_PINMUX(19, i2s, do, periph)

/* gpio19_i2c0_sda */
#define GPIO19_I2C0_SDA \
	BFLB_PINMUX(19, i2c0, sda, periph)

/* gpio19_i2c1_sda */
#define GPIO19_I2C1_SDA \
	BFLB_PINMUX(19, i2c1, sda, periph)

/* gpio19_uart0_rts */
#define GPIO19_UART0_RTS \
	BFLB_PINMUX(19, uart0, rts, periph)

/* gpio19_uart0_cts */
#define GPIO19_UART0_CTS \
	BFLB_PINMUX(19, uart0, cts, periph)

/* gpio19_uart0_tx */
#define GPIO19_UART0_TX \
	BFLB_PINMUX(19, uart0, tx, periph)

/* gpio19_uart0_rx */
#define GPIO19_UART0_RX \
	BFLB_PINMUX(19, uart0, rx, periph)

/* gpio19_uart1_rts */
#define GPIO19_UART1_RTS \
	BFLB_PINMUX(19, uart1, rts, periph)

/* gpio19_uart1_cts */
#define GPIO19_UART1_CTS \
	BFLB_PINMUX(19, uart1, cts, periph)

/* gpio19_uart1_tx */
#define GPIO19_UART1_TX \
	BFLB_PINMUX(19, uart1, tx, periph)

/* gpio19_uart1_rx */
#define GPIO19_UART1_RX \
	BFLB_PINMUX(19, uart1, rx, periph)

/* gpio19_uart2_rts */
#define GPIO19_UART2_RTS \
	BFLB_PINMUX(19, uart2, rts, periph)

/* gpio19_uart2_cts */
#define GPIO19_UART2_CTS \
	BFLB_PINMUX(19, uart2, cts, periph)

/* gpio19_uart2_tx */
#define GPIO19_UART2_TX \
	BFLB_PINMUX(19, uart2, tx, periph)

/* gpio19_uart2_rx */
#define GPIO19_UART2_RX \
	BFLB_PINMUX(19, uart2, rx, periph)

/* gpio19_emac_rxd0 */
#define GPIO19_EMAC_RXD0 \
	BFLB_PINMUX(19, emac, rxd0, periph)

/* gpio19_cam0_dat7 */
#define GPIO19_CAM0_DAT7 \
	BFLB_PINMUX(19, cam0, dat7, periph)

/* gpio19_pwm0_ch3p */
#define GPIO19_PWM0_CH3P \
	BFLB_PINMUX(19, pwm0, ch3p, periph)

/* gpio19_spi1_mosi */
#define GPIO19_SPI1_MOSI \
	BFLB_PINMUX(19, spi1, mosi, periph)

/* gpio19_dbi_b_db7 */
#define GPIO19_DBI_B_DB7 \
	BFLB_PINMUX(19, dbi_b, db7, periph)

/* gpio19_dbi_c_cs */
#define GPIO19_DBI_C_CS \
	BFLB_PINMUX(19, dbi_c, cs, periph)

/* gpio19_qspi_cs */
#define GPIO19_QSPI_CS \
	BFLB_PINMUX(19, qspi, cs, periph)

/* gpio19_audac_n */
#define GPIO19_AUDAC_N \
	BFLB_PINMUX(19, audac, n, periph)

/* gpio19_jtag_tdi */
#define GPIO19_JTAG_TDI \
	BFLB_PINMUX(19, jtag, tdi, periph)

/* gpio19_clock_out3_cam_ref */
#define GPIO19_CLOCK_OUT3_CAM_REF \
	BFLB_PINMUX(19, clock_out3, cam_ref, periph)

/* gpio19_clock_out3_i2s_ref */
#define GPIO19_CLOCK_OUT3_I2S_REF \
	BFLB_PINMUX(19, clock_out3, i2s_ref, periph)

/* gpio19_clock_out3_wifipll_48m */
#define GPIO19_CLOCK_OUT3_WIFIPLL_48M \
	BFLB_PINMUX(19, clock_out3, wifipll_48m, periph)

/* gpio20_spi0_ss */
#define GPIO20_SPI0_SS \
	BFLB_PINMUX(20, spi0, ss, periph)

/* gpio20_i2s_bclk */
#define GPIO20_I2S_BCLK \
	BFLB_PINMUX(20, i2s, bclk, periph)

/* gpio20_pdm_clk */
#define GPIO20_PDM_CLK \
	BFLB_PINMUX(20, pdm, clk, periph)

/* gpio20_i2c0_scl */
#define GPIO20_I2C0_SCL \
	BFLB_PINMUX(20, i2c0, scl, periph)

/* gpio20_i2c1_scl */
#define GPIO20_I2C1_SCL \
	BFLB_PINMUX(20, i2c1, scl, periph)

/* gpio20_uart0_rts */
#define GPIO20_UART0_RTS \
	BFLB_PINMUX(20, uart0, rts, periph)

/* gpio20_uart0_cts */
#define GPIO20_UART0_CTS \
	BFLB_PINMUX(20, uart0, cts, periph)

/* gpio20_uart0_tx */
#define GPIO20_UART0_TX \
	BFLB_PINMUX(20, uart0, tx, periph)

/* gpio20_uart0_rx */
#define GPIO20_UART0_RX \
	BFLB_PINMUX(20, uart0, rx, periph)

/* gpio20_uart1_rts */
#define GPIO20_UART1_RTS \
	BFLB_PINMUX(20, uart1, rts, periph)

/* gpio20_uart1_cts */
#define GPIO20_UART1_CTS \
	BFLB_PINMUX(20, uart1, cts, periph)

/* gpio20_uart1_tx */
#define GPIO20_UART1_TX \
	BFLB_PINMUX(20, uart1, tx, periph)

/* gpio20_uart1_rx */
#define GPIO20_UART1_RX \
	BFLB_PINMUX(20, uart1, rx, periph)

/* gpio20_uart2_rts */
#define GPIO20_UART2_RTS \
	BFLB_PINMUX(20, uart2, rts, periph)

/* gpio20_uart2_cts */
#define GPIO20_UART2_CTS \
	BFLB_PINMUX(20, uart2, cts, periph)

/* gpio20_uart2_tx */
#define GPIO20_UART2_TX \
	BFLB_PINMUX(20, uart2, tx, periph)

/* gpio20_uart2_rx */
#define GPIO20_UART2_RX \
	BFLB_PINMUX(20, uart2, rx, periph)

/* gpio20_emac_rx_dv */
#define GPIO20_EMAC_RX_DV \
	BFLB_PINMUX(20, emac, rx_dv, periph)

/* gpio20_cam0_vsync */
#define GPIO20_CAM0_VSYNC \
	BFLB_PINMUX(20, cam0, vsync, periph)

/* gpio20_pwm0_ch0p */
#define GPIO20_PWM0_CH0P \
	BFLB_PINMUX(20, pwm0, ch0p, periph)

/* gpio20_spi1_ss */
#define GPIO20_SPI1_SS \
	BFLB_PINMUX(20, spi1, ss, periph)

/* gpio20_dbi_c_sda */
#define GPIO20_DBI_C_SDA \
	BFLB_PINMUX(20, dbi_c, sda, periph)

/* gpio20_qspi_sda0 */
#define GPIO20_QSPI_SDA0 \
	BFLB_PINMUX(20, qspi, sda0, periph)

/* gpio20_jtag_tms */
#define GPIO20_JTAG_TMS \
	BFLB_PINMUX(20, jtag, tms, periph)

/* gpio20_clock_out0_cam_ref */
#define GPIO20_CLOCK_OUT0_CAM_REF \
	BFLB_PINMUX(20, clock_out0, cam_ref, periph)

/* gpio20_clock_out0_i2s_ref */
#define GPIO20_CLOCK_OUT0_I2S_REF \
	BFLB_PINMUX(20, clock_out0, i2s_ref, periph)

/* gpio20_clock_out0_solo_in_128fs */
#define GPIO20_CLOCK_OUT0_SOLO_IN_128FS \
	BFLB_PINMUX(20, clock_out0, solo_in_128fs, periph)

/* gpio21_spi0_sclk */
#define GPIO21_SPI0_SCLK \
	BFLB_PINMUX(21, spi0, sclk, periph)

/* gpio21_i2s_fs */
#define GPIO21_I2S_FS \
	BFLB_PINMUX(21, i2s, fs, periph)

/* gpio21_pdm_in */
#define GPIO21_PDM_IN \
	BFLB_PINMUX(21, pdm, in, periph)

/* gpio21_i2c0_sda */
#define GPIO21_I2C0_SDA \
	BFLB_PINMUX(21, i2c0, sda, periph)

/* gpio21_i2c1_sda */
#define GPIO21_I2C1_SDA \
	BFLB_PINMUX(21, i2c1, sda, periph)

/* gpio21_uart0_rts */
#define GPIO21_UART0_RTS \
	BFLB_PINMUX(21, uart0, rts, periph)

/* gpio21_uart0_cts */
#define GPIO21_UART0_CTS \
	BFLB_PINMUX(21, uart0, cts, periph)

/* gpio21_uart0_tx */
#define GPIO21_UART0_TX \
	BFLB_PINMUX(21, uart0, tx, periph)

/* gpio21_uart0_rx */
#define GPIO21_UART0_RX \
	BFLB_PINMUX(21, uart0, rx, periph)

/* gpio21_uart1_rts */
#define GPIO21_UART1_RTS \
	BFLB_PINMUX(21, uart1, rts, periph)

/* gpio21_uart1_cts */
#define GPIO21_UART1_CTS \
	BFLB_PINMUX(21, uart1, cts, periph)

/* gpio21_uart1_tx */
#define GPIO21_UART1_TX \
	BFLB_PINMUX(21, uart1, tx, periph)

/* gpio21_uart1_rx */
#define GPIO21_UART1_RX \
	BFLB_PINMUX(21, uart1, rx, periph)

/* gpio21_uart2_rts */
#define GPIO21_UART2_RTS \
	BFLB_PINMUX(21, uart2, rts, periph)

/* gpio21_uart2_cts */
#define GPIO21_UART2_CTS \
	BFLB_PINMUX(21, uart2, cts, periph)

/* gpio21_uart2_tx */
#define GPIO21_UART2_TX \
	BFLB_PINMUX(21, uart2, tx, periph)

/* gpio21_uart2_rx */
#define GPIO21_UART2_RX \
	BFLB_PINMUX(21, uart2, rx, periph)

/* gpio21_cam0_clk */
#define GPIO21_CAM0_CLK \
	BFLB_PINMUX(21, cam0, clk, periph)

/* gpio21_pwm0_ch1p */
#define GPIO21_PWM0_CH1P \
	BFLB_PINMUX(21, pwm0, ch1p, periph)

/* gpio21_spi1_sclk */
#define GPIO21_SPI1_SCLK \
	BFLB_PINMUX(21, spi1, sclk, periph)

/* gpio21_dbi_c_dc */
#define GPIO21_DBI_C_DC \
	BFLB_PINMUX(21, dbi_c, dc, periph)

/* gpio21_qspi_sda1 */
#define GPIO21_QSPI_SDA1 \
	BFLB_PINMUX(21, qspi, sda1, periph)

/* gpio21_jtag_tck */
#define GPIO21_JTAG_TCK \
	BFLB_PINMUX(21, jtag, tck, periph)

/* gpio21_clock_out1_cam_ref */
#define GPIO21_CLOCK_OUT1_CAM_REF \
	BFLB_PINMUX(21, clock_out1, cam_ref, periph)

/* gpio21_clock_out1_i2s_ref */
#define GPIO21_CLOCK_OUT1_I2S_REF \
	BFLB_PINMUX(21, clock_out1, i2s_ref, periph)

/* gpio21_clock_out1_solo_in_128fs */
#define GPIO21_CLOCK_OUT1_SOLO_IN_128FS \
	BFLB_PINMUX(21, clock_out1, solo_in_128fs, periph)

/* gpio22_spi0_miso */
#define GPIO22_SPI0_MISO \
	BFLB_PINMUX(22, spi0, miso, periph)

/* gpio22_i2s_di */
#define GPIO22_I2S_DI \
	BFLB_PINMUX(22, i2s, di, periph)

/* gpio22_i2c0_scl */
#define GPIO22_I2C0_SCL \
	BFLB_PINMUX(22, i2c0, scl, periph)

/* gpio22_i2c1_scl */
#define GPIO22_I2C1_SCL \
	BFLB_PINMUX(22, i2c1, scl, periph)

/* gpio22_uart0_rts */
#define GPIO22_UART0_RTS \
	BFLB_PINMUX(22, uart0, rts, periph)

/* gpio22_uart0_cts */
#define GPIO22_UART0_CTS \
	BFLB_PINMUX(22, uart0, cts, periph)

/* gpio22_uart0_tx */
#define GPIO22_UART0_TX \
	BFLB_PINMUX(22, uart0, tx, periph)

/* gpio22_uart0_rx */
#define GPIO22_UART0_RX \
	BFLB_PINMUX(22, uart0, rx, periph)

/* gpio22_uart1_rts */
#define GPIO22_UART1_RTS \
	BFLB_PINMUX(22, uart1, rts, periph)

/* gpio22_uart1_cts */
#define GPIO22_UART1_CTS \
	BFLB_PINMUX(22, uart1, cts, periph)

/* gpio22_uart1_tx */
#define GPIO22_UART1_TX \
	BFLB_PINMUX(22, uart1, tx, periph)

/* gpio22_uart1_rx */
#define GPIO22_UART1_RX \
	BFLB_PINMUX(22, uart1, rx, periph)

/* gpio22_uart2_rts */
#define GPIO22_UART2_RTS \
	BFLB_PINMUX(22, uart2, rts, periph)

/* gpio22_uart2_cts */
#define GPIO22_UART2_CTS \
	BFLB_PINMUX(22, uart2, cts, periph)

/* gpio22_uart2_tx */
#define GPIO22_UART2_TX \
	BFLB_PINMUX(22, uart2, tx, periph)

/* gpio22_uart2_rx */
#define GPIO22_UART2_RX \
	BFLB_PINMUX(22, uart2, rx, periph)

/* gpio22_cam0_hsync */
#define GPIO22_CAM0_HSYNC \
	BFLB_PINMUX(22, cam0, hsync, periph)

/* gpio22_pwm0_ch2p */
#define GPIO22_PWM0_CH2P \
	BFLB_PINMUX(22, pwm0, ch2p, periph)

/* gpio22_spi1_miso */
#define GPIO22_SPI1_MISO \
	BFLB_PINMUX(22, spi1, miso, periph)

/* gpio22_dbi_c_scl */
#define GPIO22_DBI_C_SCL \
	BFLB_PINMUX(22, dbi_c, scl, periph)

/* gpio22_qspi_sda2 */
#define GPIO22_QSPI_SDA2 \
	BFLB_PINMUX(22, qspi, sda2, periph)

/* gpio22_jtag_tdo */
#define GPIO22_JTAG_TDO \
	BFLB_PINMUX(22, jtag, tdo, periph)

/* gpio22_clock_out2_cam_ref */
#define GPIO22_CLOCK_OUT2_CAM_REF \
	BFLB_PINMUX(22, clock_out2, cam_ref, periph)

/* gpio22_clock_out2_i2s_ref */
#define GPIO22_CLOCK_OUT2_I2S_REF \
	BFLB_PINMUX(22, clock_out2, i2s_ref, periph)

/* gpio22_clock_out2_xtal */
#define GPIO22_CLOCK_OUT2_XTAL \
	BFLB_PINMUX(22, clock_out2, xtal, periph)

/* gpio22_clock_out2_wifipll_32m */
#define GPIO22_CLOCK_OUT2_WIFIPLL_32M \
	BFLB_PINMUX(22, clock_out2, wifipll_32m, periph)

/* gpio23_spi0_mosi */
#define GPIO23_SPI0_MOSI \
	BFLB_PINMUX(23, spi0, mosi, periph)

/* gpio23_i2s_do */
#define GPIO23_I2S_DO \
	BFLB_PINMUX(23, i2s, do, periph)

/* gpio23_i2c0_sda */
#define GPIO23_I2C0_SDA \
	BFLB_PINMUX(23, i2c0, sda, periph)

/* gpio23_i2c1_sda */
#define GPIO23_I2C1_SDA \
	BFLB_PINMUX(23, i2c1, sda, periph)

/* gpio23_uart0_rts */
#define GPIO23_UART0_RTS \
	BFLB_PINMUX(23, uart0, rts, periph)

/* gpio23_uart0_cts */
#define GPIO23_UART0_CTS \
	BFLB_PINMUX(23, uart0, cts, periph)

/* gpio23_uart0_tx */
#define GPIO23_UART0_TX \
	BFLB_PINMUX(23, uart0, tx, periph)

/* gpio23_uart0_rx */
#define GPIO23_UART0_RX \
	BFLB_PINMUX(23, uart0, rx, periph)

/* gpio23_uart1_rts */
#define GPIO23_UART1_RTS \
	BFLB_PINMUX(23, uart1, rts, periph)

/* gpio23_uart1_cts */
#define GPIO23_UART1_CTS \
	BFLB_PINMUX(23, uart1, cts, periph)

/* gpio23_uart1_tx */
#define GPIO23_UART1_TX \
	BFLB_PINMUX(23, uart1, tx, periph)

/* gpio23_uart1_rx */
#define GPIO23_UART1_RX \
	BFLB_PINMUX(23, uart1, rx, periph)

/* gpio23_uart2_rts */
#define GPIO23_UART2_RTS \
	BFLB_PINMUX(23, uart2, rts, periph)

/* gpio23_uart2_cts */
#define GPIO23_UART2_CTS \
	BFLB_PINMUX(23, uart2, cts, periph)

/* gpio23_uart2_tx */
#define GPIO23_UART2_TX \
	BFLB_PINMUX(23, uart2, tx, periph)

/* gpio23_uart2_rx */
#define GPIO23_UART2_RX \
	BFLB_PINMUX(23, uart2, rx, periph)

/* gpio23_emac_mdio */
#define GPIO23_EMAC_MDIO \
	BFLB_PINMUX(23, emac, mdio, periph)

/* gpio23_cam0_vsync */
#define GPIO23_CAM0_VSYNC \
	BFLB_PINMUX(23, cam0, vsync, periph)

/* gpio23_pwm0_ch3p */
#define GPIO23_PWM0_CH3P \
	BFLB_PINMUX(23, pwm0, ch3p, periph)

/* gpio23_spi1_mosi */
#define GPIO23_SPI1_MOSI \
	BFLB_PINMUX(23, spi1, mosi, periph)

/* gpio23_dbi_c_cs */
#define GPIO23_DBI_C_CS \
	BFLB_PINMUX(23, dbi_c, cs, periph)

/* gpio23_qspi_sda3 */
#define GPIO23_QSPI_SDA3 \
	BFLB_PINMUX(23, qspi, sda3, periph)

/* gpio23_jtag_tdi */
#define GPIO23_JTAG_TDI \
	BFLB_PINMUX(23, jtag, tdi, periph)

/* gpio23_clock_out3_cam_ref */
#define GPIO23_CLOCK_OUT3_CAM_REF \
	BFLB_PINMUX(23, clock_out3, cam_ref, periph)

/* gpio23_clock_out3_i2s_ref */
#define GPIO23_CLOCK_OUT3_I2S_REF \
	BFLB_PINMUX(23, clock_out3, i2s_ref, periph)

/* gpio23_clock_out3_wifipll_48m */
#define GPIO23_CLOCK_OUT3_WIFIPLL_48M \
	BFLB_PINMUX(23, clock_out3, wifipll_48m, periph)

/* gpio32_spi0_ss */
#define GPIO32_SPI0_SS \
	BFLB_PINMUX(32, spi0, ss, periph)

/* gpio32_i2s_bclk */
#define GPIO32_I2S_BCLK \
	BFLB_PINMUX(32, i2s, bclk, periph)

/* gpio32_pdm_clk */
#define GPIO32_PDM_CLK \
	BFLB_PINMUX(32, pdm, clk, periph)

/* gpio32_i2c0_scl */
#define GPIO32_I2C0_SCL \
	BFLB_PINMUX(32, i2c0, scl, periph)

/* gpio32_i2c1_scl */
#define GPIO32_I2C1_SCL \
	BFLB_PINMUX(32, i2c1, scl, periph)

/* gpio32_uart0_rts */
#define GPIO32_UART0_RTS \
	BFLB_PINMUX(32, uart0, rts, periph)

/* gpio32_uart0_cts */
#define GPIO32_UART0_CTS \
	BFLB_PINMUX(32, uart0, cts, periph)

/* gpio32_uart0_tx */
#define GPIO32_UART0_TX \
	BFLB_PINMUX(32, uart0, tx, periph)

/* gpio32_uart0_rx */
#define GPIO32_UART0_RX \
	BFLB_PINMUX(32, uart0, rx, periph)

/* gpio32_uart1_rts */
#define GPIO32_UART1_RTS \
	BFLB_PINMUX(32, uart1, rts, periph)

/* gpio32_uart1_cts */
#define GPIO32_UART1_CTS \
	BFLB_PINMUX(32, uart1, cts, periph)

/* gpio32_uart1_tx */
#define GPIO32_UART1_TX \
	BFLB_PINMUX(32, uart1, tx, periph)

/* gpio32_uart1_rx */
#define GPIO32_UART1_RX \
	BFLB_PINMUX(32, uart1, rx, periph)

/* gpio32_uart2_rts */
#define GPIO32_UART2_RTS \
	BFLB_PINMUX(32, uart2, rts, periph)

/* gpio32_uart2_cts */
#define GPIO32_UART2_CTS \
	BFLB_PINMUX(32, uart2, cts, periph)

/* gpio32_uart2_tx */
#define GPIO32_UART2_TX \
	BFLB_PINMUX(32, uart2, tx, periph)

/* gpio32_uart2_rx */
#define GPIO32_UART2_RX \
	BFLB_PINMUX(32, uart2, rx, periph)

/* gpio32_pwm0_ch0p */
#define GPIO32_PWM0_CH0P \
	BFLB_PINMUX(32, pwm0, ch0p, periph)

/* gpio32_spi1_ss */
#define GPIO32_SPI1_SS \
	BFLB_PINMUX(32, spi1, ss, periph)

/* gpio32_dbi_c_sda */
#define GPIO32_DBI_C_SDA \
	BFLB_PINMUX(32, dbi_c, sda, periph)

/* gpio32_jtag_tms */
#define GPIO32_JTAG_TMS \
	BFLB_PINMUX(32, jtag, tms, periph)

/* gpio32_clock_out0_cam_ref */
#define GPIO32_CLOCK_OUT0_CAM_REF \
	BFLB_PINMUX(32, clock_out0, cam_ref, periph)

/* gpio32_clock_out0_i2s_ref */
#define GPIO32_CLOCK_OUT0_I2S_REF \
	BFLB_PINMUX(32, clock_out0, i2s_ref, periph)

/* gpio32_clock_out0_solo_in_128fs */
#define GPIO32_CLOCK_OUT0_SOLO_IN_128FS \
	BFLB_PINMUX(32, clock_out0, solo_in_128fs, periph)

/* gpio32_adc_ch10 */
#define GPIO32_ADC_CH10 \
	BFLB_PINMUX(32, adc, ch10, analog)

/* gpio32_usb_dp */
#define GPIO32_USB_DP \
	BFLB_PINMUX(32, usb, dp, analog)

/* gpio33_spi0_sclk */
#define GPIO33_SPI0_SCLK \
	BFLB_PINMUX(33, spi0, sclk, periph)

/* gpio33_i2s_fs */
#define GPIO33_I2S_FS \
	BFLB_PINMUX(33, i2s, fs, periph)

/* gpio33_pdm_in */
#define GPIO33_PDM_IN \
	BFLB_PINMUX(33, pdm, in, periph)

/* gpio33_i2c0_sda */
#define GPIO33_I2C0_SDA \
	BFLB_PINMUX(33, i2c0, sda, periph)

/* gpio33_i2c1_sda */
#define GPIO33_I2C1_SDA \
	BFLB_PINMUX(33, i2c1, sda, periph)

/* gpio33_uart0_rts */
#define GPIO33_UART0_RTS \
	BFLB_PINMUX(33, uart0, rts, periph)

/* gpio33_uart0_cts */
#define GPIO33_UART0_CTS \
	BFLB_PINMUX(33, uart0, cts, periph)

/* gpio33_uart0_tx */
#define GPIO33_UART0_TX \
	BFLB_PINMUX(33, uart0, tx, periph)

/* gpio33_uart0_rx */
#define GPIO33_UART0_RX \
	BFLB_PINMUX(33, uart0, rx, periph)

/* gpio33_uart1_rts */
#define GPIO33_UART1_RTS \
	BFLB_PINMUX(33, uart1, rts, periph)

/* gpio33_uart1_cts */
#define GPIO33_UART1_CTS \
	BFLB_PINMUX(33, uart1, cts, periph)

/* gpio33_uart1_tx */
#define GPIO33_UART1_TX \
	BFLB_PINMUX(33, uart1, tx, periph)

/* gpio33_uart1_rx */
#define GPIO33_UART1_RX \
	BFLB_PINMUX(33, uart1, rx, periph)

/* gpio33_uart2_rts */
#define GPIO33_UART2_RTS \
	BFLB_PINMUX(33, uart2, rts, periph)

/* gpio33_uart2_cts */
#define GPIO33_UART2_CTS \
	BFLB_PINMUX(33, uart2, cts, periph)

/* gpio33_uart2_tx */
#define GPIO33_UART2_TX \
	BFLB_PINMUX(33, uart2, tx, periph)

/* gpio33_uart2_rx */
#define GPIO33_UART2_RX \
	BFLB_PINMUX(33, uart2, rx, periph)

/* gpio33_pwm0_ch1p */
#define GPIO33_PWM0_CH1P \
	BFLB_PINMUX(33, pwm0, ch1p, periph)

/* gpio33_spi1_sclk */
#define GPIO33_SPI1_SCLK \
	BFLB_PINMUX(33, spi1, sclk, periph)

/* gpio33_dbi_c_dc */
#define GPIO33_DBI_C_DC \
	BFLB_PINMUX(33, dbi_c, dc, periph)

/* gpio33_jtag_tck */
#define GPIO33_JTAG_TCK \
	BFLB_PINMUX(33, jtag, tck, periph)

/* gpio33_clock_out1_cam_ref */
#define GPIO33_CLOCK_OUT1_CAM_REF \
	BFLB_PINMUX(33, clock_out1, cam_ref, periph)

/* gpio33_clock_out1_i2s_ref */
#define GPIO33_CLOCK_OUT1_I2S_REF \
	BFLB_PINMUX(33, clock_out1, i2s_ref, periph)

/* gpio33_clock_out1_solo_in_128fs */
#define GPIO33_CLOCK_OUT1_SOLO_IN_128FS \
	BFLB_PINMUX(33, clock_out1, solo_in_128fs, periph)

/* gpio33_adc_ch11 */
#define GPIO33_ADC_CH11 \
	BFLB_PINMUX(33, adc, ch11, analog)

/* gpio33_usb_dm */
#define GPIO33_USB_DM \
	BFLB_PINMUX(33, usb, dm, analog)

/* gpio34_spi0_miso */
#define GPIO34_SPI0_MISO \
	BFLB_PINMUX(34, spi0, miso, periph)

/* gpio34_i2s_di */
#define GPIO34_I2S_DI \
	BFLB_PINMUX(34, i2s, di, periph)

/* gpio34_i2c0_scl */
#define GPIO34_I2C0_SCL \
	BFLB_PINMUX(34, i2c0, scl, periph)

/* gpio34_i2c1_scl */
#define GPIO34_I2C1_SCL \
	BFLB_PINMUX(34, i2c1, scl, periph)

/* gpio34_uart0_rts */
#define GPIO34_UART0_RTS \
	BFLB_PINMUX(34, uart0, rts, periph)

/* gpio34_uart0_cts */
#define GPIO34_UART0_CTS \
	BFLB_PINMUX(34, uart0, cts, periph)

/* gpio34_uart0_tx */
#define GPIO34_UART0_TX \
	BFLB_PINMUX(34, uart0, tx, periph)

/* gpio34_uart0_rx */
#define GPIO34_UART0_RX \
	BFLB_PINMUX(34, uart0, rx, periph)

/* gpio34_uart1_rts */
#define GPIO34_UART1_RTS \
	BFLB_PINMUX(34, uart1, rts, periph)

/* gpio34_uart1_cts */
#define GPIO34_UART1_CTS \
	BFLB_PINMUX(34, uart1, cts, periph)

/* gpio34_uart1_tx */
#define GPIO34_UART1_TX \
	BFLB_PINMUX(34, uart1, tx, periph)

/* gpio34_uart1_rx */
#define GPIO34_UART1_RX \
	BFLB_PINMUX(34, uart1, rx, periph)

/* gpio34_uart2_rts */
#define GPIO34_UART2_RTS \
	BFLB_PINMUX(34, uart2, rts, periph)

/* gpio34_uart2_cts */
#define GPIO34_UART2_CTS \
	BFLB_PINMUX(34, uart2, cts, periph)

/* gpio34_uart2_tx */
#define GPIO34_UART2_TX \
	BFLB_PINMUX(34, uart2, tx, periph)

/* gpio34_uart2_rx */
#define GPIO34_UART2_RX \
	BFLB_PINMUX(34, uart2, rx, periph)

/* gpio34_pwm0_ch2p */
#define GPIO34_PWM0_CH2P \
	BFLB_PINMUX(34, pwm0, ch2p, periph)

/* gpio34_spi1_miso */
#define GPIO34_SPI1_MISO \
	BFLB_PINMUX(34, spi1, miso, periph)

/* gpio34_dbi_c_scl */
#define GPIO34_DBI_C_SCL \
	BFLB_PINMUX(34, dbi_c, scl, periph)

/* gpio34_jtag_tdo */
#define GPIO34_JTAG_TDO \
	BFLB_PINMUX(34, jtag, tdo, periph)

/* gpio34_clock_out2_cam_ref */
#define GPIO34_CLOCK_OUT2_CAM_REF \
	BFLB_PINMUX(34, clock_out2, cam_ref, periph)

/* gpio34_clock_out2_i2s_ref */
#define GPIO34_CLOCK_OUT2_I2S_REF \
	BFLB_PINMUX(34, clock_out2, i2s_ref, periph)

/* gpio34_clock_out2_xtal */
#define GPIO34_CLOCK_OUT2_XTAL \
	BFLB_PINMUX(34, clock_out2, xtal, periph)

/* gpio34_clock_out2_wifipll_32m */
#define GPIO34_CLOCK_OUT2_WIFIPLL_32M \
	BFLB_PINMUX(34, clock_out2, wifipll_32m, periph)

/* gpio35_spi0_mosi */
#define GPIO35_SPI0_MOSI \
	BFLB_PINMUX(35, spi0, mosi, periph)

/* gpio35_i2s_do */
#define GPIO35_I2S_DO \
	BFLB_PINMUX(35, i2s, do, periph)

/* gpio35_i2c0_sda */
#define GPIO35_I2C0_SDA \
	BFLB_PINMUX(35, i2c0, sda, periph)

/* gpio35_i2c1_sda */
#define GPIO35_I2C1_SDA \
	BFLB_PINMUX(35, i2c1, sda, periph)

/* gpio35_uart0_rts */
#define GPIO35_UART0_RTS \
	BFLB_PINMUX(35, uart0, rts, periph)

/* gpio35_uart0_cts */
#define GPIO35_UART0_CTS \
	BFLB_PINMUX(35, uart0, cts, periph)

/* gpio35_uart0_tx */
#define GPIO35_UART0_TX \
	BFLB_PINMUX(35, uart0, tx, periph)

/* gpio35_uart0_rx */
#define GPIO35_UART0_RX \
	BFLB_PINMUX(35, uart0, rx, periph)

/* gpio35_uart1_rts */
#define GPIO35_UART1_RTS \
	BFLB_PINMUX(35, uart1, rts, periph)

/* gpio35_uart1_cts */
#define GPIO35_UART1_CTS \
	BFLB_PINMUX(35, uart1, cts, periph)

/* gpio35_uart1_tx */
#define GPIO35_UART1_TX \
	BFLB_PINMUX(35, uart1, tx, periph)

/* gpio35_uart1_rx */
#define GPIO35_UART1_RX \
	BFLB_PINMUX(35, uart1, rx, periph)

/* gpio35_uart2_rts */
#define GPIO35_UART2_RTS \
	BFLB_PINMUX(35, uart2, rts, periph)

/* gpio35_uart2_cts */
#define GPIO35_UART2_CTS \
	BFLB_PINMUX(35, uart2, cts, periph)

/* gpio35_uart2_tx */
#define GPIO35_UART2_TX \
	BFLB_PINMUX(35, uart2, tx, periph)

/* gpio35_uart2_rx */
#define GPIO35_UART2_RX \
	BFLB_PINMUX(35, uart2, rx, periph)

/* gpio35_pwm0_ch3p */
#define GPIO35_PWM0_CH3P \
	BFLB_PINMUX(35, pwm0, ch3p, periph)

/* gpio35_spi1_mosi */
#define GPIO35_SPI1_MOSI \
	BFLB_PINMUX(35, spi1, mosi, periph)

/* gpio35_dbi_c_cs */
#define GPIO35_DBI_C_CS \
	BFLB_PINMUX(35, dbi_c, cs, periph)

/* gpio35_jtag_tdi */
#define GPIO35_JTAG_TDI \
	BFLB_PINMUX(35, jtag, tdi, periph)

/* gpio35_clock_out3_cam_ref */
#define GPIO35_CLOCK_OUT3_CAM_REF \
	BFLB_PINMUX(35, clock_out3, cam_ref, periph)

/* gpio35_clock_out3_i2s_ref */
#define GPIO35_CLOCK_OUT3_I2S_REF \
	BFLB_PINMUX(35, clock_out3, i2s_ref, periph)

/* gpio35_clock_out3_wifipll_48m */
#define GPIO35_CLOCK_OUT3_WIFIPLL_48M \
	BFLB_PINMUX(35, clock_out3, wifipll_48m, periph)

/* gpio36_spi0_ss */
#define GPIO36_SPI0_SS \
	BFLB_PINMUX(36, spi0, ss, periph)

/* gpio36_i2s_bclk */
#define GPIO36_I2S_BCLK \
	BFLB_PINMUX(36, i2s, bclk, periph)

/* gpio36_i2c0_scl */
#define GPIO36_I2C0_SCL \
	BFLB_PINMUX(36, i2c0, scl, periph)

/* gpio36_i2c1_scl */
#define GPIO36_I2C1_SCL \
	BFLB_PINMUX(36, i2c1, scl, periph)

/* gpio36_uart0_rts */
#define GPIO36_UART0_RTS \
	BFLB_PINMUX(36, uart0, rts, periph)

/* gpio36_uart0_cts */
#define GPIO36_UART0_CTS \
	BFLB_PINMUX(36, uart0, cts, periph)

/* gpio36_uart0_tx */
#define GPIO36_UART0_TX \
	BFLB_PINMUX(36, uart0, tx, periph)

/* gpio36_uart0_rx */
#define GPIO36_UART0_RX \
	BFLB_PINMUX(36, uart0, rx, periph)

/* gpio36_uart1_rts */
#define GPIO36_UART1_RTS \
	BFLB_PINMUX(36, uart1, rts, periph)

/* gpio36_uart1_cts */
#define GPIO36_UART1_CTS \
	BFLB_PINMUX(36, uart1, cts, periph)

/* gpio36_uart1_tx */
#define GPIO36_UART1_TX \
	BFLB_PINMUX(36, uart1, tx, periph)

/* gpio36_uart1_rx */
#define GPIO36_UART1_RX \
	BFLB_PINMUX(36, uart1, rx, periph)

/* gpio36_uart2_rts */
#define GPIO36_UART2_RTS \
	BFLB_PINMUX(36, uart2, rts, periph)

/* gpio36_uart2_cts */
#define GPIO36_UART2_CTS \
	BFLB_PINMUX(36, uart2, cts, periph)

/* gpio36_uart2_tx */
#define GPIO36_UART2_TX \
	BFLB_PINMUX(36, uart2, tx, periph)

/* gpio36_uart2_rx */
#define GPIO36_UART2_RX \
	BFLB_PINMUX(36, uart2, rx, periph)

/* gpio36_pwm0_ch0p */
#define GPIO36_PWM0_CH0P \
	BFLB_PINMUX(36, pwm0, ch0p, periph)

/* gpio36_spi1_ss */
#define GPIO36_SPI1_SS \
	BFLB_PINMUX(36, spi1, ss, periph)

/* gpio36_dbi_b_dc */
#define GPIO36_DBI_B_DC \
	BFLB_PINMUX(36, dbi_b, dc, periph)

/* gpio36_jtag_tms */
#define GPIO36_JTAG_TMS \
	BFLB_PINMUX(36, jtag, tms, periph)

/* gpio36_clock_out0_cam_ref */
#define GPIO36_CLOCK_OUT0_CAM_REF \
	BFLB_PINMUX(36, clock_out0, cam_ref, periph)

/* gpio36_clock_out0_i2s_ref */
#define GPIO36_CLOCK_OUT0_I2S_REF \
	BFLB_PINMUX(36, clock_out0, i2s_ref, periph)

/* gpio36_clock_out0_solo_in_128fs */
#define GPIO36_CLOCK_OUT0_SOLO_IN_128FS \
	BFLB_PINMUX(36, clock_out0, solo_in_128fs, periph)

#endif /* DT_BINDINGS_PINCTRL_BFLB_BL616CL32X_PINCTRL_H_ */
