/*
 * Autogenerated file
 * Copyright (c) 2025 BFLB Pinctrl Generator <nandojve@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef DT_BINDINGS_PINCTRL_BFLB_BL616X_PINCTRL_H_
#define DT_BINDINGS_PINCTRL_BFLB_BL616X_PINCTRL_H_

#include <dt-bindings/pinctrl/bl61x-pinctrl.h>
#include <dt-bindings/pinctrl/bflb-common-pinctrl.h>

/* gpio0_spi_ss */
#define GPIO0_SPI_SS \
	BFLB_PINMUX(0, spi, ss, periph)

/* gpio0_i2s_blck */
#define GPIO0_I2S_BLCK \
	BFLB_PINMUX(0, i2s, blck, periph)

/* gpio0_i2c0_scl */
#define GPIO0_I2C0_SCL \
	BFLB_PINMUX(0, i2c0, scl, periph)

/* gpio0_i2c1_scl */
#define GPIO0_I2C1_SCL \
	BFLB_PINMUX(0, i2c1, scl, periph)

/* gpio0_uart0_rts */
#define GPIO0_UART0_RTS \
	BFLB_PINMUX(0, uart0, rts, periph)

/* gpio0_uart0_cts */
#define GPIO0_UART0_CTS \
	BFLB_PINMUX(0, uart0, cts, periph)

/* gpio0_uart0_tx */
#define GPIO0_UART0_TX \
	BFLB_PINMUX(0, uart0, tx, periph)

/* gpio0_uart0_rx */
#define GPIO0_UART0_RX \
	BFLB_PINMUX(0, uart0, rx, periph)

/* gpio0_uart1_rts */
#define GPIO0_UART1_RTS \
	BFLB_PINMUX(0, uart1, rts, periph)

/* gpio0_uart1_cts */
#define GPIO0_UART1_CTS \
	BFLB_PINMUX(0, uart1, cts, periph)

/* gpio0_uart1_tx */
#define GPIO0_UART1_TX \
	BFLB_PINMUX(0, uart1, tx, periph)

/* gpio0_uart1_rx */
#define GPIO0_UART1_RX \
	BFLB_PINMUX(0, uart1, rx, periph)

/* gpio0_cam1_vsync */
#define GPIO0_CAM1_VSYNC \
	BFLB_PINMUX(0, cam1, vsync, periph)

/* gpio0_pwm0_ch0p */
#define GPIO0_PWM0_CH0P \
	BFLB_PINMUX(0, pwm0, ch0p, periph)

/* gpio0_jtag_tms */
#define GPIO0_JTAG_TMS \
	BFLB_PINMUX(0, jtag, tms, periph)

/* gpio0_adc_ch9 */
#define GPIO0_ADC_CH9 \
	BFLB_PINMUX(0, adc, ch9, analog)

/* gpio1_spi_sclk */
#define GPIO1_SPI_SCLK \
	BFLB_PINMUX(1, spi, sclk, periph)

/* gpio1_i2s_fs */
#define GPIO1_I2S_FS \
	BFLB_PINMUX(1, i2s, fs, periph)

/* gpio1_i2c0_sda */
#define GPIO1_I2C0_SDA \
	BFLB_PINMUX(1, i2c0, sda, periph)

/* gpio1_i2c1_sda */
#define GPIO1_I2C1_SDA \
	BFLB_PINMUX(1, i2c1, sda, periph)

/* gpio1_uart0_rts */
#define GPIO1_UART0_RTS \
	BFLB_PINMUX(1, uart0, rts, periph)

/* gpio1_uart0_cts */
#define GPIO1_UART0_CTS \
	BFLB_PINMUX(1, uart0, cts, periph)

/* gpio1_uart0_tx */
#define GPIO1_UART0_TX \
	BFLB_PINMUX(1, uart0, tx, periph)

/* gpio1_uart0_rx */
#define GPIO1_UART0_RX \
	BFLB_PINMUX(1, uart0, rx, periph)

/* gpio1_uart1_rts */
#define GPIO1_UART1_RTS \
	BFLB_PINMUX(1, uart1, rts, periph)

/* gpio1_uart1_cts */
#define GPIO1_UART1_CTS \
	BFLB_PINMUX(1, uart1, cts, periph)

/* gpio1_uart1_tx */
#define GPIO1_UART1_TX \
	BFLB_PINMUX(1, uart1, tx, periph)

/* gpio1_uart1_rx */
#define GPIO1_UART1_RX \
	BFLB_PINMUX(1, uart1, rx, periph)

/* gpio1_cam1_hsync */
#define GPIO1_CAM1_HSYNC \
	BFLB_PINMUX(1, cam1, hsync, periph)

/* gpio1_pwm0_ch1p */
#define GPIO1_PWM0_CH1P \
	BFLB_PINMUX(1, pwm0, ch1p, periph)

/* gpio1_jtag_tck */
#define GPIO1_JTAG_TCK \
	BFLB_PINMUX(1, jtag, tck, periph)

/* gpio1_adc_ch8 */
#define GPIO1_ADC_CH8 \
	BFLB_PINMUX(1, adc, ch8, analog)

/* gpio2_spi_miso */
#define GPIO2_SPI_MISO \
	BFLB_PINMUX(2, spi, miso, periph)

/* gpio2_i2s_di */
#define GPIO2_I2S_DI \
	BFLB_PINMUX(2, i2s, di, periph)

/* gpio2_i2c0_scl */
#define GPIO2_I2C0_SCL \
	BFLB_PINMUX(2, i2c0, scl, periph)

/* gpio2_i2c1_scl */
#define GPIO2_I2C1_SCL \
	BFLB_PINMUX(2, i2c1, scl, periph)

/* gpio2_uart0_rts */
#define GPIO2_UART0_RTS \
	BFLB_PINMUX(2, uart0, rts, periph)

/* gpio2_uart0_cts */
#define GPIO2_UART0_CTS \
	BFLB_PINMUX(2, uart0, cts, periph)

/* gpio2_uart0_tx */
#define GPIO2_UART0_TX \
	BFLB_PINMUX(2, uart0, tx, periph)

/* gpio2_uart0_rx */
#define GPIO2_UART0_RX \
	BFLB_PINMUX(2, uart0, rx, periph)

/* gpio2_uart1_rts */
#define GPIO2_UART1_RTS \
	BFLB_PINMUX(2, uart1, rts, periph)

/* gpio2_uart1_cts */
#define GPIO2_UART1_CTS \
	BFLB_PINMUX(2, uart1, cts, periph)

/* gpio2_uart1_tx */
#define GPIO2_UART1_TX \
	BFLB_PINMUX(2, uart1, tx, periph)

/* gpio2_uart1_rx */
#define GPIO2_UART1_RX \
	BFLB_PINMUX(2, uart1, rx, periph)

/* gpio2_pwm0_ch2p */
#define GPIO2_PWM0_CH2P \
	BFLB_PINMUX(2, pwm0, ch2p, periph)

/* gpio2_jtag_tdo */
#define GPIO2_JTAG_TDO \
	BFLB_PINMUX(2, jtag, tdo, periph)

/* gpio2_adc_ch2 */
#define GPIO2_ADC_CH2 \
	BFLB_PINMUX(2, adc, ch2, analog)

/* gpio3_spi_mosi */
#define GPIO3_SPI_MOSI \
	BFLB_PINMUX(3, spi, mosi, periph)

/* gpio3_i2s_do */
#define GPIO3_I2S_DO \
	BFLB_PINMUX(3, i2s, do, periph)

/* gpio3_i2c0_sda */
#define GPIO3_I2C0_SDA \
	BFLB_PINMUX(3, i2c0, sda, periph)

/* gpio3_i2c1_sda */
#define GPIO3_I2C1_SDA \
	BFLB_PINMUX(3, i2c1, sda, periph)

/* gpio3_uart0_rts */
#define GPIO3_UART0_RTS \
	BFLB_PINMUX(3, uart0, rts, periph)

/* gpio3_uart0_cts */
#define GPIO3_UART0_CTS \
	BFLB_PINMUX(3, uart0, cts, periph)

/* gpio3_uart0_tx */
#define GPIO3_UART0_TX \
	BFLB_PINMUX(3, uart0, tx, periph)

/* gpio3_uart0_rx */
#define GPIO3_UART0_RX \
	BFLB_PINMUX(3, uart0, rx, periph)

/* gpio3_uart1_rts */
#define GPIO3_UART1_RTS \
	BFLB_PINMUX(3, uart1, rts, periph)

/* gpio3_uart1_cts */
#define GPIO3_UART1_CTS \
	BFLB_PINMUX(3, uart1, cts, periph)

/* gpio3_uart1_tx */
#define GPIO3_UART1_TX \
	BFLB_PINMUX(3, uart1, tx, periph)

/* gpio3_uart1_rx */
#define GPIO3_UART1_RX \
	BFLB_PINMUX(3, uart1, rx, periph)

/* gpio3_cam1_dat0 */
#define GPIO3_CAM1_DAT0 \
	BFLB_PINMUX(3, cam1, dat0, periph)

/* gpio3_pwm0_ch3p */
#define GPIO3_PWM0_CH3P \
	BFLB_PINMUX(3, pwm0, ch3p, periph)

/* gpio3_jtag_tdi */
#define GPIO3_JTAG_TDI \
	BFLB_PINMUX(3, jtag, tdi, periph)

/* gpio3_adc_ch8 */
#define GPIO3_ADC_CH8 \
	BFLB_PINMUX(3, adc, ch8, analog)

/* gpio10_sdh_dat1 */
#define GPIO10_SDH_DAT1 \
	BFLB_PINMUX(10, sdh, dat1, periph)

/* gpio10_spi_miso */
#define GPIO10_SPI_MISO \
	BFLB_PINMUX(10, spi, miso, periph)

/* gpio10_flash2_d3 */
#define GPIO10_FLASH2_D3 \
	BFLB_PINMUX(10, flash2, d3, periph)

/* gpio10_i2s_di */
#define GPIO10_I2S_DI \
	BFLB_PINMUX(10, i2s, di, periph)

/* gpio10_i2c0_scl */
#define GPIO10_I2C0_SCL \
	BFLB_PINMUX(10, i2c0, scl, periph)

/* gpio10_i2c1_scl */
#define GPIO10_I2C1_SCL \
	BFLB_PINMUX(10, i2c1, scl, periph)

/* gpio10_uart0_rts */
#define GPIO10_UART0_RTS \
	BFLB_PINMUX(10, uart0, rts, periph)

/* gpio10_uart0_cts */
#define GPIO10_UART0_CTS \
	BFLB_PINMUX(10, uart0, cts, periph)

/* gpio10_uart0_tx */
#define GPIO10_UART0_TX \
	BFLB_PINMUX(10, uart0, tx, periph)

/* gpio10_uart0_rx */
#define GPIO10_UART0_RX \
	BFLB_PINMUX(10, uart0, rx, periph)

/* gpio10_uart1_rts */
#define GPIO10_UART1_RTS \
	BFLB_PINMUX(10, uart1, rts, periph)

/* gpio10_uart1_cts */
#define GPIO10_UART1_CTS \
	BFLB_PINMUX(10, uart1, cts, periph)

/* gpio10_uart1_tx */
#define GPIO10_UART1_TX \
	BFLB_PINMUX(10, uart1, tx, periph)

/* gpio10_uart1_rx */
#define GPIO10_UART1_RX \
	BFLB_PINMUX(10, uart1, rx, periph)

/* gpio10_cam1_dat1 */
#define GPIO10_CAM1_DAT1 \
	BFLB_PINMUX(10, cam1, dat1, periph)

/* gpio10_sdio_dat2 */
#define GPIO10_SDIO_DAT2 \
	BFLB_PINMUX(10, sdio, dat2, periph)

/* gpio10_pwm0_ch2p */
#define GPIO10_PWM0_CH2P \
	BFLB_PINMUX(10, pwm0, ch2p, periph)

/* gpio10_qspi_scl */
#define GPIO10_QSPI_SCL \
	BFLB_PINMUX(10, qspi, scl, periph)

/* gpio10_jtag_tdo */
#define GPIO10_JTAG_TDO \
	BFLB_PINMUX(10, jtag, tdo, periph)

/* gpio10_adc_ch7 */
#define GPIO10_ADC_CH7 \
	BFLB_PINMUX(10, adc, ch7, analog)

/* gpio11_sdh_dat0 */
#define GPIO11_SDH_DAT0 \
	BFLB_PINMUX(11, sdh, dat0, periph)

/* gpio11_spi_mosi */
#define GPIO11_SPI_MOSI \
	BFLB_PINMUX(11, spi, mosi, periph)

/* gpio11_flash3_clk */
#define GPIO11_FLASH3_CLK \
	BFLB_PINMUX(11, flash3, clk, periph)

/* gpio11_i2s_do */
#define GPIO11_I2S_DO \
	BFLB_PINMUX(11, i2s, do, periph)

/* gpio11_i2c0_sda */
#define GPIO11_I2C0_SDA \
	BFLB_PINMUX(11, i2c0, sda, periph)

/* gpio11_i2c1_sda */
#define GPIO11_I2C1_SDA \
	BFLB_PINMUX(11, i2c1, sda, periph)

/* gpio11_uart0_rts */
#define GPIO11_UART0_RTS \
	BFLB_PINMUX(11, uart0, rts, periph)

/* gpio11_uart0_cts */
#define GPIO11_UART0_CTS \
	BFLB_PINMUX(11, uart0, cts, periph)

/* gpio11_uart0_tx */
#define GPIO11_UART0_TX \
	BFLB_PINMUX(11, uart0, tx, periph)

/* gpio11_uart0_rx */
#define GPIO11_UART0_RX \
	BFLB_PINMUX(11, uart0, rx, periph)

/* gpio11_uart1_rts */
#define GPIO11_UART1_RTS \
	BFLB_PINMUX(11, uart1, rts, periph)

/* gpio11_uart1_cts */
#define GPIO11_UART1_CTS \
	BFLB_PINMUX(11, uart1, cts, periph)

/* gpio11_uart1_tx */
#define GPIO11_UART1_TX \
	BFLB_PINMUX(11, uart1, tx, periph)

/* gpio11_uart1_rx */
#define GPIO11_UART1_RX \
	BFLB_PINMUX(11, uart1, rx, periph)

/* gpio11_cam1_dat2 */
#define GPIO11_CAM1_DAT2 \
	BFLB_PINMUX(11, cam1, dat2, periph)

/* gpio11_sdio_dat3 */
#define GPIO11_SDIO_DAT3 \
	BFLB_PINMUX(11, sdio, dat3, periph)

/* gpio11_pwm0_ch3p */
#define GPIO11_PWM0_CH3P \
	BFLB_PINMUX(11, pwm0, ch3p, periph)

/* gpio11_qspi_cs */
#define GPIO11_QSPI_CS \
	BFLB_PINMUX(11, qspi, cs, periph)

/* gpio11_jtag_tdi */
#define GPIO11_JTAG_TDI \
	BFLB_PINMUX(11, jtag, tdi, periph)

/* gpio12_sdh_clk */
#define GPIO12_SDH_CLK \
	BFLB_PINMUX(12, sdh, clk, periph)

/* gpio12_spi_ss */
#define GPIO12_SPI_SS \
	BFLB_PINMUX(12, spi, ss, periph)

/* gpio12_flash3_d0 */
#define GPIO12_FLASH3_D0 \
	BFLB_PINMUX(12, flash3, d0, periph)

/* gpio12_i2s_bclk */
#define GPIO12_I2S_BCLK \
	BFLB_PINMUX(12, i2s, bclk, periph)

/* gpio12_i2c0_scl */
#define GPIO12_I2C0_SCL \
	BFLB_PINMUX(12, i2c0, scl, periph)

/* gpio12_i2c1_scl */
#define GPIO12_I2C1_SCL \
	BFLB_PINMUX(12, i2c1, scl, periph)

/* gpio12_uart0_rts */
#define GPIO12_UART0_RTS \
	BFLB_PINMUX(12, uart0, rts, periph)

/* gpio12_uart0_cts */
#define GPIO12_UART0_CTS \
	BFLB_PINMUX(12, uart0, cts, periph)

/* gpio12_uart0_tx */
#define GPIO12_UART0_TX \
	BFLB_PINMUX(12, uart0, tx, periph)

/* gpio12_uart0_rx */
#define GPIO12_UART0_RX \
	BFLB_PINMUX(12, uart0, rx, periph)

/* gpio12_uart1_rts */
#define GPIO12_UART1_RTS \
	BFLB_PINMUX(12, uart1, rts, periph)

/* gpio12_uart1_cts */
#define GPIO12_UART1_CTS \
	BFLB_PINMUX(12, uart1, cts, periph)

/* gpio12_uart1_tx */
#define GPIO12_UART1_TX \
	BFLB_PINMUX(12, uart1, tx, periph)

/* gpio12_uart1_rx */
#define GPIO12_UART1_RX \
	BFLB_PINMUX(12, uart1, rx, periph)

/* gpio12_cam1_dat3 */
#define GPIO12_CAM1_DAT3 \
	BFLB_PINMUX(12, cam1, dat3, periph)

/* gpio12_sdio_cmd */
#define GPIO12_SDIO_CMD \
	BFLB_PINMUX(12, sdio, cmd, periph)

/* gpio12_pwm0_ch0p */
#define GPIO12_PWM0_CH0P \
	BFLB_PINMUX(12, pwm0, ch0p, periph)

/* gpio12_qspi_sda0 */
#define GPIO12_QSPI_SDA0 \
	BFLB_PINMUX(12, qspi, sda0, periph)

/* gpio12_jtag_tms */
#define GPIO12_JTAG_TMS \
	BFLB_PINMUX(12, jtag, tms, periph)

/* gpio12_adc_ch6 */
#define GPIO12_ADC_CH6 \
	BFLB_PINMUX(12, adc, ch6, analog)

/* gpio13_sdh_cmd */
#define GPIO13_SDH_CMD \
	BFLB_PINMUX(13, sdh, cmd, periph)

/* gpio13_spi_sclk */
#define GPIO13_SPI_SCLK \
	BFLB_PINMUX(13, spi, sclk, periph)

/* gpio13_flash3_d2 */
#define GPIO13_FLASH3_D2 \
	BFLB_PINMUX(13, flash3, d2, periph)

/* gpio13_i2s_fs */
#define GPIO13_I2S_FS \
	BFLB_PINMUX(13, i2s, fs, periph)

/* gpio13_i2c0_sda */
#define GPIO13_I2C0_SDA \
	BFLB_PINMUX(13, i2c0, sda, periph)

/* gpio13_i2c1_sda */
#define GPIO13_I2C1_SDA \
	BFLB_PINMUX(13, i2c1, sda, periph)

/* gpio13_uart0_rts */
#define GPIO13_UART0_RTS \
	BFLB_PINMUX(13, uart0, rts, periph)

/* gpio13_uart0_cts */
#define GPIO13_UART0_CTS \
	BFLB_PINMUX(13, uart0, cts, periph)

/* gpio13_uart0_tx */
#define GPIO13_UART0_TX \
	BFLB_PINMUX(13, uart0, tx, periph)

/* gpio13_uart0_rx */
#define GPIO13_UART0_RX \
	BFLB_PINMUX(13, uart0, rx, periph)

/* gpio13_uart1_rts */
#define GPIO13_UART1_RTS \
	BFLB_PINMUX(13, uart1, rts, periph)

/* gpio13_uart1_cts */
#define GPIO13_UART1_CTS \
	BFLB_PINMUX(13, uart1, cts, periph)

/* gpio13_uart1_tx */
#define GPIO13_UART1_TX \
	BFLB_PINMUX(13, uart1, tx, periph)

/* gpio13_uart1_rx */
#define GPIO13_UART1_RX \
	BFLB_PINMUX(13, uart1, rx, periph)

/* gpio13_cam1_clk */
#define GPIO13_CAM1_CLK \
	BFLB_PINMUX(13, cam1, clk, periph)

/* gpio13_sdio_clk */
#define GPIO13_SDIO_CLK \
	BFLB_PINMUX(13, sdio, clk, periph)

/* gpio13_pwm0_ch1p */
#define GPIO13_PWM0_CH1P \
	BFLB_PINMUX(13, pwm0, ch1p, periph)

/* gpio13_qspi_sda1 */
#define GPIO13_QSPI_SDA1 \
	BFLB_PINMUX(13, qspi, sda1, periph)

/* gpio13_jtag_tck */
#define GPIO13_JTAG_TCK \
	BFLB_PINMUX(13, jtag, tck, periph)

/* gpio13_adc_ch5 */
#define GPIO13_ADC_CH5 \
	BFLB_PINMUX(13, adc, ch5, analog)

/* gpio14_sdh_dat3 */
#define GPIO14_SDH_DAT3 \
	BFLB_PINMUX(14, sdh, dat3, periph)

/* gpio14_spi_miso */
#define GPIO14_SPI_MISO \
	BFLB_PINMUX(14, spi, miso, periph)

/* gpio14_flash3_d1 */
#define GPIO14_FLASH3_D1 \
	BFLB_PINMUX(14, flash3, d1, periph)

/* gpio14_i2s_di */
#define GPIO14_I2S_DI \
	BFLB_PINMUX(14, i2s, di, periph)

/* gpio14_i2c0_scl */
#define GPIO14_I2C0_SCL \
	BFLB_PINMUX(14, i2c0, scl, periph)

/* gpio14_i2c1_scl */
#define GPIO14_I2C1_SCL \
	BFLB_PINMUX(14, i2c1, scl, periph)

/* gpio14_uart0_rts */
#define GPIO14_UART0_RTS \
	BFLB_PINMUX(14, uart0, rts, periph)

/* gpio14_uart0_cts */
#define GPIO14_UART0_CTS \
	BFLB_PINMUX(14, uart0, cts, periph)

/* gpio14_uart0_tx */
#define GPIO14_UART0_TX \
	BFLB_PINMUX(14, uart0, tx, periph)

/* gpio14_uart0_rx */
#define GPIO14_UART0_RX \
	BFLB_PINMUX(14, uart0, rx, periph)

/* gpio14_uart1_rts */
#define GPIO14_UART1_RTS \
	BFLB_PINMUX(14, uart1, rts, periph)

/* gpio14_uart1_cts */
#define GPIO14_UART1_CTS \
	BFLB_PINMUX(14, uart1, cts, periph)

/* gpio14_uart1_tx */
#define GPIO14_UART1_TX \
	BFLB_PINMUX(14, uart1, tx, periph)

/* gpio14_uart1_rx */
#define GPIO14_UART1_RX \
	BFLB_PINMUX(14, uart1, rx, periph)

/* gpio14_cam1_dat4 */
#define GPIO14_CAM1_DAT4 \
	BFLB_PINMUX(14, cam1, dat4, periph)

/* gpio14_sdio_dat0 */
#define GPIO14_SDIO_DAT0 \
	BFLB_PINMUX(14, sdio, dat0, periph)

/* gpio14_pwm0_ch2p */
#define GPIO14_PWM0_CH2P \
	BFLB_PINMUX(14, pwm0, ch2p, periph)

/* gpio14_qspi_sda2 */
#define GPIO14_QSPI_SDA2 \
	BFLB_PINMUX(14, qspi, sda2, periph)

/* gpio14_audac_p */
#define GPIO14_AUDAC_P \
	BFLB_PINMUX(14, audac, p, periph)

/* gpio14_jtag_tdo */
#define GPIO14_JTAG_TDO \
	BFLB_PINMUX(14, jtag, tdo, periph)

/* gpio14_adc_ch4 */
#define GPIO14_ADC_CH4 \
	BFLB_PINMUX(14, adc, ch4, analog)

/* gpio15_sdh_dat2 */
#define GPIO15_SDH_DAT2 \
	BFLB_PINMUX(15, sdh, dat2, periph)

/* gpio15_spi_mosi */
#define GPIO15_SPI_MOSI \
	BFLB_PINMUX(15, spi, mosi, periph)

/* gpio15_flash3_cs */
#define GPIO15_FLASH3_CS \
	BFLB_PINMUX(15, flash3, cs, periph)

/* gpio15_i2s_do */
#define GPIO15_I2S_DO \
	BFLB_PINMUX(15, i2s, do, periph)

/* gpio15_i2c0_sda */
#define GPIO15_I2C0_SDA \
	BFLB_PINMUX(15, i2c0, sda, periph)

/* gpio15_i2c1_sda */
#define GPIO15_I2C1_SDA \
	BFLB_PINMUX(15, i2c1, sda, periph)

/* gpio15_uart0_rts */
#define GPIO15_UART0_RTS \
	BFLB_PINMUX(15, uart0, rts, periph)

/* gpio15_uart0_cts */
#define GPIO15_UART0_CTS \
	BFLB_PINMUX(15, uart0, cts, periph)

/* gpio15_uart0_tx */
#define GPIO15_UART0_TX \
	BFLB_PINMUX(15, uart0, tx, periph)

/* gpio15_uart0_rx */
#define GPIO15_UART0_RX \
	BFLB_PINMUX(15, uart0, rx, periph)

/* gpio15_uart1_rts */
#define GPIO15_UART1_RTS \
	BFLB_PINMUX(15, uart1, rts, periph)

/* gpio15_uart1_cts */
#define GPIO15_UART1_CTS \
	BFLB_PINMUX(15, uart1, cts, periph)

/* gpio15_uart1_tx */
#define GPIO15_UART1_TX \
	BFLB_PINMUX(15, uart1, tx, periph)

/* gpio15_uart1_rx */
#define GPIO15_UART1_RX \
	BFLB_PINMUX(15, uart1, rx, periph)

/* gpio15_sdio_dat1 */
#define GPIO15_SDIO_DAT1 \
	BFLB_PINMUX(15, sdio, dat1, periph)

/* gpio15_pwm0_ch3p */
#define GPIO15_PWM0_CH3P \
	BFLB_PINMUX(15, pwm0, ch3p, periph)

/* gpio15_qspi_sda3 */
#define GPIO15_QSPI_SDA3 \
	BFLB_PINMUX(15, qspi, sda3, periph)

/* gpio15_audac_n */
#define GPIO15_AUDAC_N \
	BFLB_PINMUX(15, audac, n, periph)

/* gpio15_jtag_tdi */
#define GPIO15_JTAG_TDI \
	BFLB_PINMUX(15, jtag, tdi, periph)

/* gpio16_spi_ss */
#define GPIO16_SPI_SS \
	BFLB_PINMUX(16, spi, ss, periph)

/* gpio16_i2s_bclk */
#define GPIO16_I2S_BCLK \
	BFLB_PINMUX(16, i2s, bclk, periph)

/* gpio16_i2c0_scl */
#define GPIO16_I2C0_SCL \
	BFLB_PINMUX(16, i2c0, scl, periph)

/* gpio16_i2c1_scl */
#define GPIO16_I2C1_SCL \
	BFLB_PINMUX(16, i2c1, scl, periph)

/* gpio16_uart0_rts */
#define GPIO16_UART0_RTS \
	BFLB_PINMUX(16, uart0, rts, periph)

/* gpio16_uart0_cts */
#define GPIO16_UART0_CTS \
	BFLB_PINMUX(16, uart0, cts, periph)

/* gpio16_uart0_tx */
#define GPIO16_UART0_TX \
	BFLB_PINMUX(16, uart0, tx, periph)

/* gpio16_uart0_rx */
#define GPIO16_UART0_RX \
	BFLB_PINMUX(16, uart0, rx, periph)

/* gpio16_uart1_rts */
#define GPIO16_UART1_RTS \
	BFLB_PINMUX(16, uart1, rts, periph)

/* gpio16_uart1_cts */
#define GPIO16_UART1_CTS \
	BFLB_PINMUX(16, uart1, cts, periph)

/* gpio16_uart1_tx */
#define GPIO16_UART1_TX \
	BFLB_PINMUX(16, uart1, tx, periph)

/* gpio16_uart1_rx */
#define GPIO16_UART1_RX \
	BFLB_PINMUX(16, uart1, rx, periph)

/* gpio16_cam1_dat6 */
#define GPIO16_CAM1_DAT6 \
	BFLB_PINMUX(16, cam1, dat6, periph)

/* gpio16_pwm0_ch0p */
#define GPIO16_PWM0_CH0P \
	BFLB_PINMUX(16, pwm0, ch0p, periph)

/* gpio16_jtag_tms */
#define GPIO16_JTAG_TMS \
	BFLB_PINMUX(16, jtag, tms, periph)

/* gpio17_spi_sclk */
#define GPIO17_SPI_SCLK \
	BFLB_PINMUX(17, spi, sclk, periph)

/* gpio17_i2s_fs */
#define GPIO17_I2S_FS \
	BFLB_PINMUX(17, i2s, fs, periph)

/* gpio17_i2c0_sda */
#define GPIO17_I2C0_SDA \
	BFLB_PINMUX(17, i2c0, sda, periph)

/* gpio17_i2c1_sda */
#define GPIO17_I2C1_SDA \
	BFLB_PINMUX(17, i2c1, sda, periph)

/* gpio17_uart0_rts */
#define GPIO17_UART0_RTS \
	BFLB_PINMUX(17, uart0, rts, periph)

/* gpio17_uart0_cts */
#define GPIO17_UART0_CTS \
	BFLB_PINMUX(17, uart0, cts, periph)

/* gpio17_uart0_tx */
#define GPIO17_UART0_TX \
	BFLB_PINMUX(17, uart0, tx, periph)

/* gpio17_uart0_rx */
#define GPIO17_UART0_RX \
	BFLB_PINMUX(17, uart0, rx, periph)

/* gpio17_uart1_rts */
#define GPIO17_UART1_RTS \
	BFLB_PINMUX(17, uart1, rts, periph)

/* gpio17_uart1_cts */
#define GPIO17_UART1_CTS \
	BFLB_PINMUX(17, uart1, cts, periph)

/* gpio17_uart1_tx */
#define GPIO17_UART1_TX \
	BFLB_PINMUX(17, uart1, tx, periph)

/* gpio17_uart1_rx */
#define GPIO17_UART1_RX \
	BFLB_PINMUX(17, uart1, rx, periph)

/* gpio17_cam1_dat7 */
#define GPIO17_CAM1_DAT7 \
	BFLB_PINMUX(17, cam1, dat7, periph)

/* gpio17_pwm0_ch1p */
#define GPIO17_PWM0_CH1P \
	BFLB_PINMUX(17, pwm0, ch1p, periph)

/* gpio17_jtag_tck */
#define GPIO17_JTAG_TCK \
	BFLB_PINMUX(17, jtag, tck, periph)

/* gpio20_spi_ss */
#define GPIO20_SPI_SS \
	BFLB_PINMUX(20, spi, ss, periph)

/* gpio20_i2s_bclk */
#define GPIO20_I2S_BCLK \
	BFLB_PINMUX(20, i2s, bclk, periph)

/* gpio20_pdm_clk */
#define GPIO20_PDM_CLK \
	BFLB_PINMUX(20, pdm, clk, periph)

/* gpio20_i2c0_scl */
#define GPIO20_I2C0_SCL \
	BFLB_PINMUX(20, i2c0, scl, periph)

/* gpio20_i2c1_scl */
#define GPIO20_I2C1_SCL \
	BFLB_PINMUX(20, i2c1, scl, periph)

/* gpio20_uart0_rts */
#define GPIO20_UART0_RTS \
	BFLB_PINMUX(20, uart0, rts, periph)

/* gpio20_uart0_cts */
#define GPIO20_UART0_CTS \
	BFLB_PINMUX(20, uart0, cts, periph)

/* gpio20_uart0_tx */
#define GPIO20_UART0_TX \
	BFLB_PINMUX(20, uart0, tx, periph)

/* gpio20_uart0_rx */
#define GPIO20_UART0_RX \
	BFLB_PINMUX(20, uart0, rx, periph)

/* gpio20_uart1_rts */
#define GPIO20_UART1_RTS \
	BFLB_PINMUX(20, uart1, rts, periph)

/* gpio20_uart1_cts */
#define GPIO20_UART1_CTS \
	BFLB_PINMUX(20, uart1, cts, periph)

/* gpio20_uart1_tx */
#define GPIO20_UART1_TX \
	BFLB_PINMUX(20, uart1, tx, periph)

/* gpio20_uart1_rx */
#define GPIO20_UART1_RX \
	BFLB_PINMUX(20, uart1, rx, periph)

/* gpio20_pwm0_ch0p */
#define GPIO20_PWM0_CH0P \
	BFLB_PINMUX(20, pwm0, ch0p, periph)

/* gpio20_jtag_tms */
#define GPIO20_JTAG_TMS \
	BFLB_PINMUX(20, jtag, tms, periph)

/* gpio20_adc_ch0 */
#define GPIO20_ADC_CH0 \
	BFLB_PINMUX(20, adc, ch0, analog)

/* gpio21_spi_sclk */
#define GPIO21_SPI_SCLK \
	BFLB_PINMUX(21, spi, sclk, periph)

/* gpio21_i2s_fs */
#define GPIO21_I2S_FS \
	BFLB_PINMUX(21, i2s, fs, periph)

/* gpio21_pdm_in */
#define GPIO21_PDM_IN \
	BFLB_PINMUX(21, pdm, in, periph)

/* gpio21_i2c0_sda */
#define GPIO21_I2C0_SDA \
	BFLB_PINMUX(21, i2c0, sda, periph)

/* gpio21_i2c1_sda */
#define GPIO21_I2C1_SDA \
	BFLB_PINMUX(21, i2c1, sda, periph)

/* gpio21_uart0_rts */
#define GPIO21_UART0_RTS \
	BFLB_PINMUX(21, uart0, rts, periph)

/* gpio21_uart0_cts */
#define GPIO21_UART0_CTS \
	BFLB_PINMUX(21, uart0, cts, periph)

/* gpio21_uart0_tx */
#define GPIO21_UART0_TX \
	BFLB_PINMUX(21, uart0, tx, periph)

/* gpio21_uart0_rx */
#define GPIO21_UART0_RX \
	BFLB_PINMUX(21, uart0, rx, periph)

/* gpio21_uart1_rts */
#define GPIO21_UART1_RTS \
	BFLB_PINMUX(21, uart1, rts, periph)

/* gpio21_uart1_cts */
#define GPIO21_UART1_CTS \
	BFLB_PINMUX(21, uart1, cts, periph)

/* gpio21_uart1_tx */
#define GPIO21_UART1_TX \
	BFLB_PINMUX(21, uart1, tx, periph)

/* gpio21_uart1_rx */
#define GPIO21_UART1_RX \
	BFLB_PINMUX(21, uart1, rx, periph)

/* gpio21_pwm0_ch1p */
#define GPIO21_PWM0_CH1P \
	BFLB_PINMUX(21, pwm0, ch1p, periph)

/* gpio21_jtag_tck */
#define GPIO21_JTAG_TCK \
	BFLB_PINMUX(21, jtag, tck, periph)

/* gpio22_spi_miso */
#define GPIO22_SPI_MISO \
	BFLB_PINMUX(22, spi, miso, periph)

/* gpio22_i2s_di */
#define GPIO22_I2S_DI \
	BFLB_PINMUX(22, i2s, di, periph)

/* gpio22_i2c0_scl */
#define GPIO22_I2C0_SCL \
	BFLB_PINMUX(22, i2c0, scl, periph)

/* gpio22_i2c1_scl */
#define GPIO22_I2C1_SCL \
	BFLB_PINMUX(22, i2c1, scl, periph)

/* gpio22_uart0_rts */
#define GPIO22_UART0_RTS \
	BFLB_PINMUX(22, uart0, rts, periph)

/* gpio22_uart0_cts */
#define GPIO22_UART0_CTS \
	BFLB_PINMUX(22, uart0, cts, periph)

/* gpio22_uart0_tx */
#define GPIO22_UART0_TX \
	BFLB_PINMUX(22, uart0, tx, periph)

/* gpio22_uart0_rx */
#define GPIO22_UART0_RX \
	BFLB_PINMUX(22, uart0, rx, periph)

/* gpio22_uart1_rts */
#define GPIO22_UART1_RTS \
	BFLB_PINMUX(22, uart1, rts, periph)

/* gpio22_uart1_cts */
#define GPIO22_UART1_CTS \
	BFLB_PINMUX(22, uart1, cts, periph)

/* gpio22_uart1_tx */
#define GPIO22_UART1_TX \
	BFLB_PINMUX(22, uart1, tx, periph)

/* gpio22_uart1_rx */
#define GPIO22_UART1_RX \
	BFLB_PINMUX(22, uart1, rx, periph)

/* gpio22_pwm0_ch2p */
#define GPIO22_PWM0_CH2P \
	BFLB_PINMUX(22, pwm0, ch2p, periph)

/* gpio22_audac_p */
#define GPIO22_AUDAC_P \
	BFLB_PINMUX(22, audac, p, periph)

/* gpio22_jtag_tdo */
#define GPIO22_JTAG_TDO \
	BFLB_PINMUX(22, jtag, tdo, periph)

/* gpio22_adc_ch0 */
#define GPIO22_ADC_CH0 \
	BFLB_PINMUX(22, adc, ch0, analog)

/* gpio27_spi_mosi */
#define GPIO27_SPI_MOSI \
	BFLB_PINMUX(27, spi, mosi, periph)

/* gpio27_i2s_do */
#define GPIO27_I2S_DO \
	BFLB_PINMUX(27, i2s, do, periph)

/* gpio27_i2c0_sda */
#define GPIO27_I2C0_SDA \
	BFLB_PINMUX(27, i2c0, sda, periph)

/* gpio27_i2c1_sda */
#define GPIO27_I2C1_SDA \
	BFLB_PINMUX(27, i2c1, sda, periph)

/* gpio27_uart0_rts */
#define GPIO27_UART0_RTS \
	BFLB_PINMUX(27, uart0, rts, periph)

/* gpio27_uart0_cts */
#define GPIO27_UART0_CTS \
	BFLB_PINMUX(27, uart0, cts, periph)

/* gpio27_uart0_tx */
#define GPIO27_UART0_TX \
	BFLB_PINMUX(27, uart0, tx, periph)

/* gpio27_uart0_rx */
#define GPIO27_UART0_RX \
	BFLB_PINMUX(27, uart0, rx, periph)

/* gpio27_uart1_rts */
#define GPIO27_UART1_RTS \
	BFLB_PINMUX(27, uart1, rts, periph)

/* gpio27_uart1_cts */
#define GPIO27_UART1_CTS \
	BFLB_PINMUX(27, uart1, cts, periph)

/* gpio27_uart1_tx */
#define GPIO27_UART1_TX \
	BFLB_PINMUX(27, uart1, tx, periph)

/* gpio27_uart1_rx */
#define GPIO27_UART1_RX \
	BFLB_PINMUX(27, uart1, rx, periph)

/* gpio27_emac_txd1 */
#define GPIO27_EMAC_TXD1 \
	BFLB_PINMUX(27, emac, txd1, periph)

/* gpio27_cam0_dat3 */
#define GPIO27_CAM0_DAT3 \
	BFLB_PINMUX(27, cam0, dat3, periph)

/* gpio27_pwm0_ch3p */
#define GPIO27_PWM0_CH3P \
	BFLB_PINMUX(27, pwm0, ch3p, periph)

/* gpio27_audac_n */
#define GPIO27_AUDAC_N \
	BFLB_PINMUX(27, audac, n, periph)

/* gpio27_jtag_tdi */
#define GPIO27_JTAG_TDI \
	BFLB_PINMUX(27, jtag, tdi, periph)

/* gpio27_adc_ch10 */
#define GPIO27_ADC_CH10 \
	BFLB_PINMUX(27, adc, ch10, analog)

/* gpio28_spi_ss */
#define GPIO28_SPI_SS \
	BFLB_PINMUX(28, spi, ss, periph)

/* gpio28_i2s_bclk */
#define GPIO28_I2S_BCLK \
	BFLB_PINMUX(28, i2s, bclk, periph)

/* gpio28_i2c0_scl */
#define GPIO28_I2C0_SCL \
	BFLB_PINMUX(28, i2c0, scl, periph)

/* gpio28_i2c1_scl */
#define GPIO28_I2C1_SCL \
	BFLB_PINMUX(28, i2c1, scl, periph)

/* gpio28_uart0_rts */
#define GPIO28_UART0_RTS \
	BFLB_PINMUX(28, uart0, rts, periph)

/* gpio28_uart0_cts */
#define GPIO28_UART0_CTS \
	BFLB_PINMUX(28, uart0, cts, periph)

/* gpio28_uart0_tx */
#define GPIO28_UART0_TX \
	BFLB_PINMUX(28, uart0, tx, periph)

/* gpio28_uart0_rx */
#define GPIO28_UART0_RX \
	BFLB_PINMUX(28, uart0, rx, periph)

/* gpio28_uart1_rts */
#define GPIO28_UART1_RTS \
	BFLB_PINMUX(28, uart1, rts, periph)

/* gpio28_uart1_cts */
#define GPIO28_UART1_CTS \
	BFLB_PINMUX(28, uart1, cts, periph)

/* gpio28_uart1_tx */
#define GPIO28_UART1_TX \
	BFLB_PINMUX(28, uart1, tx, periph)

/* gpio28_uart1_rx */
#define GPIO28_UART1_RX \
	BFLB_PINMUX(28, uart1, rx, periph)

/* gpio28_emac_rxd0 */
#define GPIO28_EMAC_RXD0 \
	BFLB_PINMUX(28, emac, rxd0, periph)

/* gpio28_cam0_hsync */
#define GPIO28_CAM0_HSYNC \
	BFLB_PINMUX(28, cam0, hsync, periph)

/* gpio28_pwm0_ch0p */
#define GPIO28_PWM0_CH0P \
	BFLB_PINMUX(28, pwm0, ch0p, periph)

/* gpio28_audac_p */
#define GPIO28_AUDAC_P \
	BFLB_PINMUX(28, audac, p, periph)

/* gpio28_jtag_tms */
#define GPIO28_JTAG_TMS \
	BFLB_PINMUX(28, jtag, tms, periph)

/* gpio29_spi_sclk */
#define GPIO29_SPI_SCLK \
	BFLB_PINMUX(29, spi, sclk, periph)

/* gpio29_i2s_fs */
#define GPIO29_I2S_FS \
	BFLB_PINMUX(29, i2s, fs, periph)

/* gpio29_i2c0_sda */
#define GPIO29_I2C0_SDA \
	BFLB_PINMUX(29, i2c0, sda, periph)

/* gpio29_i2c1_sda */
#define GPIO29_I2C1_SDA \
	BFLB_PINMUX(29, i2c1, sda, periph)

/* gpio29_uart0_rts */
#define GPIO29_UART0_RTS \
	BFLB_PINMUX(29, uart0, rts, periph)

/* gpio29_uart0_cts */
#define GPIO29_UART0_CTS \
	BFLB_PINMUX(29, uart0, cts, periph)

/* gpio29_uart0_tx */
#define GPIO29_UART0_TX \
	BFLB_PINMUX(29, uart0, tx, periph)

/* gpio29_uart0_rx */
#define GPIO29_UART0_RX \
	BFLB_PINMUX(29, uart0, rx, periph)

/* gpio29_uart1_rts */
#define GPIO29_UART1_RTS \
	BFLB_PINMUX(29, uart1, rts, periph)

/* gpio29_uart1_cts */
#define GPIO29_UART1_CTS \
	BFLB_PINMUX(29, uart1, cts, periph)

/* gpio29_uart1_tx */
#define GPIO29_UART1_TX \
	BFLB_PINMUX(29, uart1, tx, periph)

/* gpio29_uart1_rx */
#define GPIO29_UART1_RX \
	BFLB_PINMUX(29, uart1, rx, periph)

/* gpio29_emac_rxd1 */
#define GPIO29_EMAC_RXD1 \
	BFLB_PINMUX(29, emac, rxd1, periph)

/* gpio29_cam0_vsync */
#define GPIO29_CAM0_VSYNC \
	BFLB_PINMUX(29, cam0, vsync, periph)

/* gpio29_pwm0_ch1p */
#define GPIO29_PWM0_CH1P \
	BFLB_PINMUX(29, pwm0, ch1p, periph)

/* gpio29_jtag_tck */
#define GPIO29_JTAG_TCK \
	BFLB_PINMUX(29, jtag, tck, periph)

/* gpio30_spi_miso */
#define GPIO30_SPI_MISO \
	BFLB_PINMUX(30, spi, miso, periph)

/* gpio30_i2s_di */
#define GPIO30_I2S_DI \
	BFLB_PINMUX(30, i2s, di, periph)

/* gpio30_i2c0_scl */
#define GPIO30_I2C0_SCL \
	BFLB_PINMUX(30, i2c0, scl, periph)

/* gpio30_i2c1_scl */
#define GPIO30_I2C1_SCL \
	BFLB_PINMUX(30, i2c1, scl, periph)

/* gpio30_uart0_rts */
#define GPIO30_UART0_RTS \
	BFLB_PINMUX(30, uart0, rts, periph)

/* gpio30_uart0_cts */
#define GPIO30_UART0_CTS \
	BFLB_PINMUX(30, uart0, cts, periph)

/* gpio30_uart0_tx */
#define GPIO30_UART0_TX \
	BFLB_PINMUX(30, uart0, tx, periph)

/* gpio30_uart0_rx */
#define GPIO30_UART0_RX \
	BFLB_PINMUX(30, uart0, rx, periph)

/* gpio30_uart1_rts */
#define GPIO30_UART1_RTS \
	BFLB_PINMUX(30, uart1, rts, periph)

/* gpio30_uart1_cts */
#define GPIO30_UART1_CTS \
	BFLB_PINMUX(30, uart1, cts, periph)

/* gpio30_uart1_tx */
#define GPIO30_UART1_TX \
	BFLB_PINMUX(30, uart1, tx, periph)

/* gpio30_uart1_rx */
#define GPIO30_UART1_RX \
	BFLB_PINMUX(30, uart1, rx, periph)

/* gpio30_emac_rxerr */
#define GPIO30_EMAC_RXERR \
	BFLB_PINMUX(30, emac, rxerr, periph)

/* gpio30_pwm0_ch2p */
#define GPIO30_PWM0_CH2P \
	BFLB_PINMUX(30, pwm0, ch2p, periph)

/* gpio30_jtag_tdo */
#define GPIO30_JTAG_TDO \
	BFLB_PINMUX(30, jtag, tdo, periph)

#endif /* DT_BINDINGS_PINCTRL_BFLB_BL616X_PINCTRL_H_ */
