/*
 * Autogenerated file
 * Copyright (c) 2026 BFLB Pinctrl Generator <nandojve@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef DT_BINDINGS_PINCTRL_BFLB_BL702LX_PINCTRL_H_
#define DT_BINDINGS_PINCTRL_BFLB_BL702LX_PINCTRL_H_

#include <dt-bindings/pinctrl/bl70xl-pinctrl.h>
#include <dt-bindings/pinctrl/bflb-common-pinctrl.h>

/* gpio0_spi_mosi */
#define GPIO0_SPI_MOSI \
	BFLB_PINMUX(0, spi, mosi, periph)

/* gpio0_pdm_clk */
#define GPIO0_PDM_CLK \
	BFLB_PINMUX(0, pdm, clk, periph)

/* gpio0_i2c_scl */
#define GPIO0_I2C_SCL \
	BFLB_PINMUX(0, i2c, scl, periph)

/* gpio0_uart0_rts */
#define GPIO0_UART0_RTS \
	BFLB_PINMUX(0, uart0, rts, periph)

/* gpio0_uart0_cts */
#define GPIO0_UART0_CTS \
	BFLB_PINMUX(0, uart0, cts, periph)

/* gpio0_uart0_tx */
#define GPIO0_UART0_TX \
	BFLB_PINMUX(0, uart0, tx, periph)

/* gpio0_uart0_rx */
#define GPIO0_UART0_RX \
	BFLB_PINMUX(0, uart0, rx, periph)

/* gpio0_pwm0_ch0 */
#define GPIO0_PWM0_CH0 \
	BFLB_PINMUX(0, pwm0, ch0, periph)

/* gpio0_jtag_tms */
#define GPIO0_JTAG_TMS \
	BFLB_PINMUX(0, jtag, tms, periph)

/* gpio1_spi_miso */
#define GPIO1_SPI_MISO \
	BFLB_PINMUX(1, spi, miso, periph)

/* gpio1_pdm_in0 */
#define GPIO1_PDM_IN0 \
	BFLB_PINMUX(1, pdm, in0, periph)

/* gpio1_i2c_sda */
#define GPIO1_I2C_SDA \
	BFLB_PINMUX(1, i2c, sda, periph)

/* gpio1_uart0_rts */
#define GPIO1_UART0_RTS \
	BFLB_PINMUX(1, uart0, rts, periph)

/* gpio1_uart0_cts */
#define GPIO1_UART0_CTS \
	BFLB_PINMUX(1, uart0, cts, periph)

/* gpio1_uart0_tx */
#define GPIO1_UART0_TX \
	BFLB_PINMUX(1, uart0, tx, periph)

/* gpio1_uart0_rx */
#define GPIO1_UART0_RX \
	BFLB_PINMUX(1, uart0, rx, periph)

/* gpio1_pwm1_ch0 */
#define GPIO1_PWM1_CH0 \
	BFLB_PINMUX(1, pwm1, ch0, periph)

/* gpio1_jtag_tdi */
#define GPIO1_JTAG_TDI \
	BFLB_PINMUX(1, jtag, tdi, periph)

/* gpio2_spi_ss */
#define GPIO2_SPI_SS \
	BFLB_PINMUX(2, spi, ss, periph)

/* gpio2_pdm_clk */
#define GPIO2_PDM_CLK \
	BFLB_PINMUX(2, pdm, clk, periph)

/* gpio2_i2c_scl */
#define GPIO2_I2C_SCL \
	BFLB_PINMUX(2, i2c, scl, periph)

/* gpio2_uart0_rts */
#define GPIO2_UART0_RTS \
	BFLB_PINMUX(2, uart0, rts, periph)

/* gpio2_uart0_cts */
#define GPIO2_UART0_CTS \
	BFLB_PINMUX(2, uart0, cts, periph)

/* gpio2_uart0_tx */
#define GPIO2_UART0_TX \
	BFLB_PINMUX(2, uart0, tx, periph)

/* gpio2_uart0_rx */
#define GPIO2_UART0_RX \
	BFLB_PINMUX(2, uart0, rx, periph)

/* gpio2_pwm1_ch1 */
#define GPIO2_PWM1_CH1 \
	BFLB_PINMUX(2, pwm1, ch1, periph)

/* gpio2_jtag_tck */
#define GPIO2_JTAG_TCK \
	BFLB_PINMUX(2, jtag, tck, periph)

/* gpio7_spi_sclk */
#define GPIO7_SPI_SCLK \
	BFLB_PINMUX(7, spi, sclk, periph)

/* gpio7_pdm_in0 */
#define GPIO7_PDM_IN0 \
	BFLB_PINMUX(7, pdm, in0, periph)

/* gpio7_i2c_sda */
#define GPIO7_I2C_SDA \
	BFLB_PINMUX(7, i2c, sda, periph)

/* gpio7_uart0_rts */
#define GPIO7_UART0_RTS \
	BFLB_PINMUX(7, uart0, rts, periph)

/* gpio7_uart0_cts */
#define GPIO7_UART0_CTS \
	BFLB_PINMUX(7, uart0, cts, periph)

/* gpio7_uart0_tx */
#define GPIO7_UART0_TX \
	BFLB_PINMUX(7, uart0, tx, periph)

/* gpio7_uart0_rx */
#define GPIO7_UART0_RX \
	BFLB_PINMUX(7, uart0, rx, periph)

/* gpio7_pwm1_ch1 */
#define GPIO7_PWM1_CH1 \
	BFLB_PINMUX(7, pwm1, ch1, periph)

/* gpio7_jtag_tdo */
#define GPIO7_JTAG_TDO \
	BFLB_PINMUX(7, jtag, tdo, periph)

/* gpio7_adc_ch7 */
#define GPIO7_ADC_CH7 \
	BFLB_PINMUX(7, adc, ch7, analog)

/* gpio8_spi_mosi */
#define GPIO8_SPI_MOSI \
	BFLB_PINMUX(8, spi, mosi, periph)

/* gpio8_pdm_clk */
#define GPIO8_PDM_CLK \
	BFLB_PINMUX(8, pdm, clk, periph)

/* gpio8_i2c_scl */
#define GPIO8_I2C_SCL \
	BFLB_PINMUX(8, i2c, scl, periph)

/* gpio8_uart0_rts */
#define GPIO8_UART0_RTS \
	BFLB_PINMUX(8, uart0, rts, periph)

/* gpio8_uart0_cts */
#define GPIO8_UART0_CTS \
	BFLB_PINMUX(8, uart0, cts, periph)

/* gpio8_uart0_tx */
#define GPIO8_UART0_TX \
	BFLB_PINMUX(8, uart0, tx, periph)

/* gpio8_uart0_rx */
#define GPIO8_UART0_RX \
	BFLB_PINMUX(8, uart0, rx, periph)

/* gpio8_pwm1_ch2 */
#define GPIO8_PWM1_CH2 \
	BFLB_PINMUX(8, pwm1, ch2, periph)

/* gpio8_jtag_tms */
#define GPIO8_JTAG_TMS \
	BFLB_PINMUX(8, jtag, tms, periph)

/* gpio8_adc_ch8 */
#define GPIO8_ADC_CH8 \
	BFLB_PINMUX(8, adc, ch8, analog)

/* gpio9_spi_miso */
#define GPIO9_SPI_MISO \
	BFLB_PINMUX(9, spi, miso, periph)

/* gpio9_i2c_sda */
#define GPIO9_I2C_SDA \
	BFLB_PINMUX(9, i2c, sda, periph)

/* gpio9_uart0_rts */
#define GPIO9_UART0_RTS \
	BFLB_PINMUX(9, uart0, rts, periph)

/* gpio9_uart0_cts */
#define GPIO9_UART0_CTS \
	BFLB_PINMUX(9, uart0, cts, periph)

/* gpio9_uart0_tx */
#define GPIO9_UART0_TX \
	BFLB_PINMUX(9, uart0, tx, periph)

/* gpio9_uart0_rx */
#define GPIO9_UART0_RX \
	BFLB_PINMUX(9, uart0, rx, periph)

/* gpio9_pwm1_ch3 */
#define GPIO9_PWM1_CH3 \
	BFLB_PINMUX(9, pwm1, ch3, periph)

/* gpio9_jtag_tdi */
#define GPIO9_JTAG_TDI \
	BFLB_PINMUX(9, jtag, tdi, periph)

/* gpio9_adc_ch9 */
#define GPIO9_ADC_CH9 \
	BFLB_PINMUX(9, adc, ch9, analog)

/* gpio10_spi_ss */
#define GPIO10_SPI_SS \
	BFLB_PINMUX(10, spi, ss, periph)

/* gpio10_i2c_scl */
#define GPIO10_I2C_SCL \
	BFLB_PINMUX(10, i2c, scl, periph)

/* gpio10_uart0_rts */
#define GPIO10_UART0_RTS \
	BFLB_PINMUX(10, uart0, rts, periph)

/* gpio10_uart0_cts */
#define GPIO10_UART0_CTS \
	BFLB_PINMUX(10, uart0, cts, periph)

/* gpio10_uart0_tx */
#define GPIO10_UART0_TX \
	BFLB_PINMUX(10, uart0, tx, periph)

/* gpio10_uart0_rx */
#define GPIO10_UART0_RX \
	BFLB_PINMUX(10, uart0, rx, periph)

/* gpio10_pwm0_ch0 */
#define GPIO10_PWM0_CH0 \
	BFLB_PINMUX(10, pwm0, ch0, periph)

/* gpio10_jtag_tck */
#define GPIO10_JTAG_TCK \
	BFLB_PINMUX(10, jtag, tck, periph)

/* gpio11_spi_sclk */
#define GPIO11_SPI_SCLK \
	BFLB_PINMUX(11, spi, sclk, periph)

/* gpio11_i2c_sda */
#define GPIO11_I2C_SDA \
	BFLB_PINMUX(11, i2c, sda, periph)

/* gpio11_uart0_rts */
#define GPIO11_UART0_RTS \
	BFLB_PINMUX(11, uart0, rts, periph)

/* gpio11_uart0_cts */
#define GPIO11_UART0_CTS \
	BFLB_PINMUX(11, uart0, cts, periph)

/* gpio11_uart0_tx */
#define GPIO11_UART0_TX \
	BFLB_PINMUX(11, uart0, tx, periph)

/* gpio11_uart0_rx */
#define GPIO11_UART0_RX \
	BFLB_PINMUX(11, uart0, rx, periph)

/* gpio11_pwm1_ch0 */
#define GPIO11_PWM1_CH0 \
	BFLB_PINMUX(11, pwm1, ch0, periph)

/* gpio11_jtag_tdo */
#define GPIO11_JTAG_TDO \
	BFLB_PINMUX(11, jtag, tdo, periph)

/* gpio11_adc_ch10 */
#define GPIO11_ADC_CH10 \
	BFLB_PINMUX(11, adc, ch10, analog)

/* gpio14_spi_ss */
#define GPIO14_SPI_SS \
	BFLB_PINMUX(14, spi, ss, periph)

/* gpio14_i2c_scl */
#define GPIO14_I2C_SCL \
	BFLB_PINMUX(14, i2c, scl, periph)

/* gpio14_uart0_rts */
#define GPIO14_UART0_RTS \
	BFLB_PINMUX(14, uart0, rts, periph)

/* gpio14_uart0_cts */
#define GPIO14_UART0_CTS \
	BFLB_PINMUX(14, uart0, cts, periph)

/* gpio14_uart0_tx */
#define GPIO14_UART0_TX \
	BFLB_PINMUX(14, uart0, tx, periph)

/* gpio14_uart0_rx */
#define GPIO14_UART0_RX \
	BFLB_PINMUX(14, uart0, rx, periph)

/* gpio14_pwm1_ch3 */
#define GPIO14_PWM1_CH3 \
	BFLB_PINMUX(14, pwm1, ch3, periph)

/* gpio14_jtag_tck */
#define GPIO14_JTAG_TCK \
	BFLB_PINMUX(14, jtag, tck, periph)

/* gpio14_adc_ch0 */
#define GPIO14_ADC_CH0 \
	BFLB_PINMUX(14, adc, ch0, analog)

/* gpio15_spi_sclk */
#define GPIO15_SPI_SCLK \
	BFLB_PINMUX(15, spi, sclk, periph)

/* gpio15_i2c_sda */
#define GPIO15_I2C_SDA \
	BFLB_PINMUX(15, i2c, sda, periph)

/* gpio15_uart0_rts */
#define GPIO15_UART0_RTS \
	BFLB_PINMUX(15, uart0, rts, periph)

/* gpio15_uart0_cts */
#define GPIO15_UART0_CTS \
	BFLB_PINMUX(15, uart0, cts, periph)

/* gpio15_uart0_tx */
#define GPIO15_UART0_TX \
	BFLB_PINMUX(15, uart0, tx, periph)

/* gpio15_uart0_rx */
#define GPIO15_UART0_RX \
	BFLB_PINMUX(15, uart0, rx, periph)

/* gpio15_pwm0_ch0 */
#define GPIO15_PWM0_CH0 \
	BFLB_PINMUX(15, pwm0, ch0, periph)

/* gpio15_jtag_tdo */
#define GPIO15_JTAG_TDO \
	BFLB_PINMUX(15, jtag, tdo, periph)

/* gpio15_adc_ch1 */
#define GPIO15_ADC_CH1 \
	BFLB_PINMUX(15, adc, ch1, analog)

/* gpio16_spi_mosi */
#define GPIO16_SPI_MOSI \
	BFLB_PINMUX(16, spi, mosi, periph)

/* gpio16_i2c_scl */
#define GPIO16_I2C_SCL \
	BFLB_PINMUX(16, i2c, scl, periph)

/* gpio16_uart0_rts */
#define GPIO16_UART0_RTS \
	BFLB_PINMUX(16, uart0, rts, periph)

/* gpio16_uart0_cts */
#define GPIO16_UART0_CTS \
	BFLB_PINMUX(16, uart0, cts, periph)

/* gpio16_uart0_tx */
#define GPIO16_UART0_TX \
	BFLB_PINMUX(16, uart0, tx, periph)

/* gpio16_uart0_rx */
#define GPIO16_UART0_RX \
	BFLB_PINMUX(16, uart0, rx, periph)

/* gpio16_pwm1_ch0 */
#define GPIO16_PWM1_CH0 \
	BFLB_PINMUX(16, pwm1, ch0, periph)

/* gpio16_jtag_tms */
#define GPIO16_JTAG_TMS \
	BFLB_PINMUX(16, jtag, tms, periph)

/* gpio17_spi_miso */
#define GPIO17_SPI_MISO \
	BFLB_PINMUX(17, spi, miso, periph)

/* gpio17_i2c_sda */
#define GPIO17_I2C_SDA \
	BFLB_PINMUX(17, i2c, sda, periph)

/* gpio17_uart0_rts */
#define GPIO17_UART0_RTS \
	BFLB_PINMUX(17, uart0, rts, periph)

/* gpio17_uart0_cts */
#define GPIO17_UART0_CTS \
	BFLB_PINMUX(17, uart0, cts, periph)

/* gpio17_uart0_tx */
#define GPIO17_UART0_TX \
	BFLB_PINMUX(17, uart0, tx, periph)

/* gpio17_uart0_rx */
#define GPIO17_UART0_RX \
	BFLB_PINMUX(17, uart0, rx, periph)

/* gpio17_pwm1_ch1 */
#define GPIO17_PWM1_CH1 \
	BFLB_PINMUX(17, pwm1, ch1, periph)

/* gpio17_jtag_tdi */
#define GPIO17_JTAG_TDI \
	BFLB_PINMUX(17, jtag, tdi, periph)

/* gpio17_adc_ch2 */
#define GPIO17_ADC_CH2 \
	BFLB_PINMUX(17, adc, ch2, analog)

/* gpio18_spi_ss */
#define GPIO18_SPI_SS \
	BFLB_PINMUX(18, spi, ss, periph)

/* gpio18_i2c_scl */
#define GPIO18_I2C_SCL \
	BFLB_PINMUX(18, i2c, scl, periph)

/* gpio18_uart0_rts */
#define GPIO18_UART0_RTS \
	BFLB_PINMUX(18, uart0, rts, periph)

/* gpio18_uart0_cts */
#define GPIO18_UART0_CTS \
	BFLB_PINMUX(18, uart0, cts, periph)

/* gpio18_uart0_tx */
#define GPIO18_UART0_TX \
	BFLB_PINMUX(18, uart0, tx, periph)

/* gpio18_uart0_rx */
#define GPIO18_UART0_RX \
	BFLB_PINMUX(18, uart0, rx, periph)

/* gpio18_pwm1_ch2 */
#define GPIO18_PWM1_CH2 \
	BFLB_PINMUX(18, pwm1, ch2, periph)

/* gpio18_jtag_tck */
#define GPIO18_JTAG_TCK \
	BFLB_PINMUX(18, jtag, tck, periph)

/* gpio18_adc_ch3 */
#define GPIO18_ADC_CH3 \
	BFLB_PINMUX(18, adc, ch3, analog)

/* gpio22_spi_ss */
#define GPIO22_SPI_SS \
	BFLB_PINMUX(22, spi, ss, periph)

/* gpio22_i2c_scl */
#define GPIO22_I2C_SCL \
	BFLB_PINMUX(22, i2c, scl, periph)

/* gpio22_uart0_rts */
#define GPIO22_UART0_RTS \
	BFLB_PINMUX(22, uart0, rts, periph)

/* gpio22_uart0_cts */
#define GPIO22_UART0_CTS \
	BFLB_PINMUX(22, uart0, cts, periph)

/* gpio22_uart0_tx */
#define GPIO22_UART0_TX \
	BFLB_PINMUX(22, uart0, tx, periph)

/* gpio22_uart0_rx */
#define GPIO22_UART0_RX \
	BFLB_PINMUX(22, uart0, rx, periph)

/* gpio22_pwm1_ch1 */
#define GPIO22_PWM1_CH1 \
	BFLB_PINMUX(22, pwm1, ch1, periph)

/* gpio22_jtag_tck */
#define GPIO22_JTAG_TCK \
	BFLB_PINMUX(22, jtag, tck, periph)

/* gpio23_flash2_d0 */
#define GPIO23_FLASH2_D0 \
	BFLB_PINMUX(23, flash2, d0, periph)

/* gpio23_spi_sclk */
#define GPIO23_SPI_SCLK \
	BFLB_PINMUX(23, spi, sclk, periph)

/* gpio23_i2c_sda */
#define GPIO23_I2C_SDA \
	BFLB_PINMUX(23, i2c, sda, periph)

/* gpio23_uart0_rts */
#define GPIO23_UART0_RTS \
	BFLB_PINMUX(23, uart0, rts, periph)

/* gpio23_uart0_cts */
#define GPIO23_UART0_CTS \
	BFLB_PINMUX(23, uart0, cts, periph)

/* gpio23_uart0_tx */
#define GPIO23_UART0_TX \
	BFLB_PINMUX(23, uart0, tx, periph)

/* gpio23_uart0_rx */
#define GPIO23_UART0_RX \
	BFLB_PINMUX(23, uart0, rx, periph)

/* gpio23_pwm1_ch2 */
#define GPIO23_PWM1_CH2 \
	BFLB_PINMUX(23, pwm1, ch2, periph)

/* gpio23_jtag_tdo */
#define GPIO23_JTAG_TDO \
	BFLB_PINMUX(23, jtag, tdo, periph)

/* gpio24_flash2_d2 */
#define GPIO24_FLASH2_D2 \
	BFLB_PINMUX(24, flash2, d2, periph)

/* gpio24_spi_mosi */
#define GPIO24_SPI_MOSI \
	BFLB_PINMUX(24, spi, mosi, periph)

/* gpio24_i2c_scl */
#define GPIO24_I2C_SCL \
	BFLB_PINMUX(24, i2c, scl, periph)

/* gpio24_uart0_rts */
#define GPIO24_UART0_RTS \
	BFLB_PINMUX(24, uart0, rts, periph)

/* gpio24_uart0_cts */
#define GPIO24_UART0_CTS \
	BFLB_PINMUX(24, uart0, cts, periph)

/* gpio24_uart0_tx */
#define GPIO24_UART0_TX \
	BFLB_PINMUX(24, uart0, tx, periph)

/* gpio24_uart0_rx */
#define GPIO24_UART0_RX \
	BFLB_PINMUX(24, uart0, rx, periph)

/* gpio24_pwm1_ch3 */
#define GPIO24_PWM1_CH3 \
	BFLB_PINMUX(24, pwm1, ch3, periph)

/* gpio24_jtag_tms */
#define GPIO24_JTAG_TMS \
	BFLB_PINMUX(24, jtag, tms, periph)

/* gpio25_flash2_d1 */
#define GPIO25_FLASH2_D1 \
	BFLB_PINMUX(25, flash2, d1, periph)

/* gpio25_spi_miso */
#define GPIO25_SPI_MISO \
	BFLB_PINMUX(25, spi, miso, periph)

/* gpio25_i2c_sda */
#define GPIO25_I2C_SDA \
	BFLB_PINMUX(25, i2c, sda, periph)

/* gpio25_uart0_rts */
#define GPIO25_UART0_RTS \
	BFLB_PINMUX(25, uart0, rts, periph)

/* gpio25_uart0_cts */
#define GPIO25_UART0_CTS \
	BFLB_PINMUX(25, uart0, cts, periph)

/* gpio25_uart0_tx */
#define GPIO25_UART0_TX \
	BFLB_PINMUX(25, uart0, tx, periph)

/* gpio25_uart0_rx */
#define GPIO25_UART0_RX \
	BFLB_PINMUX(25, uart0, rx, periph)

/* gpio25_pwm0_ch0 */
#define GPIO25_PWM0_CH0 \
	BFLB_PINMUX(25, pwm0, ch0, periph)

/* gpio25_jtag_tdi */
#define GPIO25_JTAG_TDI \
	BFLB_PINMUX(25, jtag, tdi, periph)

/* gpio26_flash2_cs */
#define GPIO26_FLASH2_CS \
	BFLB_PINMUX(26, flash2, cs, periph)

/* gpio26_spi_ss */
#define GPIO26_SPI_SS \
	BFLB_PINMUX(26, spi, ss, periph)

/* gpio26_i2c_scl */
#define GPIO26_I2C_SCL \
	BFLB_PINMUX(26, i2c, scl, periph)

/* gpio26_uart0_rts */
#define GPIO26_UART0_RTS \
	BFLB_PINMUX(26, uart0, rts, periph)

/* gpio26_uart0_cts */
#define GPIO26_UART0_CTS \
	BFLB_PINMUX(26, uart0, cts, periph)

/* gpio26_uart0_tx */
#define GPIO26_UART0_TX \
	BFLB_PINMUX(26, uart0, tx, periph)

/* gpio26_uart0_rx */
#define GPIO26_UART0_RX \
	BFLB_PINMUX(26, uart0, rx, periph)

/* gpio26_pwm1_ch0 */
#define GPIO26_PWM1_CH0 \
	BFLB_PINMUX(26, pwm1, ch0, periph)

/* gpio26_jtag_tck */
#define GPIO26_JTAG_TCK \
	BFLB_PINMUX(26, jtag, tck, periph)

/* gpio27_flash2_clk */
#define GPIO27_FLASH2_CLK \
	BFLB_PINMUX(27, flash2, clk, periph)

/* gpio27_spi_sclk */
#define GPIO27_SPI_SCLK \
	BFLB_PINMUX(27, spi, sclk, periph)

/* gpio27_i2c_sda */
#define GPIO27_I2C_SDA \
	BFLB_PINMUX(27, i2c, sda, periph)

/* gpio27_uart0_rts */
#define GPIO27_UART0_RTS \
	BFLB_PINMUX(27, uart0, rts, periph)

/* gpio27_uart0_cts */
#define GPIO27_UART0_CTS \
	BFLB_PINMUX(27, uart0, cts, periph)

/* gpio27_uart0_tx */
#define GPIO27_UART0_TX \
	BFLB_PINMUX(27, uart0, tx, periph)

/* gpio27_uart0_rx */
#define GPIO27_UART0_RX \
	BFLB_PINMUX(27, uart0, rx, periph)

/* gpio27_pwm1_ch1 */
#define GPIO27_PWM1_CH1 \
	BFLB_PINMUX(27, pwm1, ch1, periph)

/* gpio27_jtag_tdo */
#define GPIO27_JTAG_TDO \
	BFLB_PINMUX(27, jtag, tdo, periph)

/* gpio28_flash2_d3 */
#define GPIO28_FLASH2_D3 \
	BFLB_PINMUX(28, flash2, d3, periph)

/* gpio28_spi_mosi */
#define GPIO28_SPI_MOSI \
	BFLB_PINMUX(28, spi, mosi, periph)

/* gpio28_i2c_scl */
#define GPIO28_I2C_SCL \
	BFLB_PINMUX(28, i2c, scl, periph)

/* gpio28_uart0_rts */
#define GPIO28_UART0_RTS \
	BFLB_PINMUX(28, uart0, rts, periph)

/* gpio28_uart0_cts */
#define GPIO28_UART0_CTS \
	BFLB_PINMUX(28, uart0, cts, periph)

/* gpio28_uart0_tx */
#define GPIO28_UART0_TX \
	BFLB_PINMUX(28, uart0, tx, periph)

/* gpio28_uart0_rx */
#define GPIO28_UART0_RX \
	BFLB_PINMUX(28, uart0, rx, periph)

/* gpio28_pwm1_ch2 */
#define GPIO28_PWM1_CH2 \
	BFLB_PINMUX(28, pwm1, ch2, periph)

/* gpio28_jtag_tms */
#define GPIO28_JTAG_TMS \
	BFLB_PINMUX(28, jtag, tms, periph)

/* gpio30_spi_ss */
#define GPIO30_SPI_SS \
	BFLB_PINMUX(30, spi, ss, periph)

/* gpio30_i2c_scl */
#define GPIO30_I2C_SCL \
	BFLB_PINMUX(30, i2c, scl, periph)

/* gpio30_uart0_rts */
#define GPIO30_UART0_RTS \
	BFLB_PINMUX(30, uart0, rts, periph)

/* gpio30_uart0_cts */
#define GPIO30_UART0_CTS \
	BFLB_PINMUX(30, uart0, cts, periph)

/* gpio30_uart0_tx */
#define GPIO30_UART0_TX \
	BFLB_PINMUX(30, uart0, tx, periph)

/* gpio30_uart0_rx */
#define GPIO30_UART0_RX \
	BFLB_PINMUX(30, uart0, rx, periph)

/* gpio30_pwm0_ch0 */
#define GPIO30_PWM0_CH0 \
	BFLB_PINMUX(30, pwm0, ch0, periph)

/* gpio30_jtag_tck */
#define GPIO30_JTAG_TCK \
	BFLB_PINMUX(30, jtag, tck, periph)

/* gpio31_spi_sclk */
#define GPIO31_SPI_SCLK \
	BFLB_PINMUX(31, spi, sclk, periph)

/* gpio31_i2c_sda */
#define GPIO31_I2C_SDA \
	BFLB_PINMUX(31, i2c, sda, periph)

/* gpio31_uart0_rts */
#define GPIO31_UART0_RTS \
	BFLB_PINMUX(31, uart0, rts, periph)

/* gpio31_uart0_cts */
#define GPIO31_UART0_CTS \
	BFLB_PINMUX(31, uart0, cts, periph)

/* gpio31_uart0_tx */
#define GPIO31_UART0_TX \
	BFLB_PINMUX(31, uart0, tx, periph)

/* gpio31_uart0_rx */
#define GPIO31_UART0_RX \
	BFLB_PINMUX(31, uart0, rx, periph)

/* gpio31_pwm1_ch0 */
#define GPIO31_PWM1_CH0 \
	BFLB_PINMUX(31, pwm1, ch0, periph)

/* gpio31_jtag_tdo */
#define GPIO31_JTAG_TDO \
	BFLB_PINMUX(31, jtag, tdo, periph)

#endif /* DT_BINDINGS_PINCTRL_BFLB_BL702LX_PINCTRL_H_ */
