/*
 * Autogenerated file
 * Copyright (c) 2025 BFLB Pinctrl Generator <nandojve@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef DT_BINDINGS_PINCTRL_BFLB_BL704X_PINCTRL_H_
#define DT_BINDINGS_PINCTRL_BFLB_BL704X_PINCTRL_H_

#include <dt-bindings/pinctrl/bl70x-pinctrl.h>
#include <dt-bindings/pinctrl/bflb-common-pinctrl.h>

/* gpio0_i2s_blck */
#define GPIO0_I2S_BLCK \
	BFLB_PINMUX(0, i2s, blck, periph)

/* gpio0_spi_mosi */
#define GPIO0_SPI_MOSI \
	BFLB_PINMUX(0, spi, mosi, periph)

/* gpio0_i2c_scl */
#define GPIO0_I2C_SCL \
	BFLB_PINMUX(0, i2c, scl, periph)

/* gpio0_uart0_rts */
#define GPIO0_UART0_RTS \
	BFLB_PINMUX(0, uart0, rts, periph)

/* gpio0_uart0_cts */
#define GPIO0_UART0_CTS \
	BFLB_PINMUX(0, uart0, cts, periph)

/* gpio0_uart0_tx */
#define GPIO0_UART0_TX \
	BFLB_PINMUX(0, uart0, tx, periph)

/* gpio0_uart0_rx */
#define GPIO0_UART0_RX \
	BFLB_PINMUX(0, uart0, rx, periph)

/* gpio0_uart1_rts */
#define GPIO0_UART1_RTS \
	BFLB_PINMUX(0, uart1, rts, periph)

/* gpio0_uart1_cts */
#define GPIO0_UART1_CTS \
	BFLB_PINMUX(0, uart1, cts, periph)

/* gpio0_uart1_tx */
#define GPIO0_UART1_TX \
	BFLB_PINMUX(0, uart1, tx, periph)

/* gpio0_uart1_rx */
#define GPIO0_UART1_RX \
	BFLB_PINMUX(0, uart1, rx, periph)

/* gpio0_pwm_ch0 */
#define GPIO0_PWM_CH0 \
	BFLB_PINMUX(0, pwm, ch0, periph)

/* gpio0_cam_pix_clk */
#define GPIO0_CAM_PIX_CLK \
	BFLB_PINMUX(0, cam, pix_clk, periph)

/* gpio0_jtag_tms */
#define GPIO0_JTAG_TMS \
	BFLB_PINMUX(0, jtag, tms, periph)

/* gpio0_fem_gpio0 */
#define GPIO0_FEM_GPIO0 \
	BFLB_PINMUX(0, fem, gpio0, periph)

/* gpio0_mii_ref_clk */
#define GPIO0_MII_REF_CLK \
	BFLB_PINMUX(0, mii, ref_clk, periph)

/* gpio0_qdec0_a */
#define GPIO0_QDEC0_A \
	BFLB_PINMUX(0, qdec0, a, periph)

/* gpio1_i2s_fs */
#define GPIO1_I2S_FS \
	BFLB_PINMUX(1, i2s, fs, periph)

/* gpio1_spi_miso */
#define GPIO1_SPI_MISO \
	BFLB_PINMUX(1, spi, miso, periph)

/* gpio1_i2c_sda */
#define GPIO1_I2C_SDA \
	BFLB_PINMUX(1, i2c, sda, periph)

/* gpio1_uart0_rts */
#define GPIO1_UART0_RTS \
	BFLB_PINMUX(1, uart0, rts, periph)

/* gpio1_uart0_cts */
#define GPIO1_UART0_CTS \
	BFLB_PINMUX(1, uart0, cts, periph)

/* gpio1_uart0_tx */
#define GPIO1_UART0_TX \
	BFLB_PINMUX(1, uart0, tx, periph)

/* gpio1_uart0_rx */
#define GPIO1_UART0_RX \
	BFLB_PINMUX(1, uart0, rx, periph)

/* gpio1_uart1_rts */
#define GPIO1_UART1_RTS \
	BFLB_PINMUX(1, uart1, rts, periph)

/* gpio1_uart1_cts */
#define GPIO1_UART1_CTS \
	BFLB_PINMUX(1, uart1, cts, periph)

/* gpio1_uart1_tx */
#define GPIO1_UART1_TX \
	BFLB_PINMUX(1, uart1, tx, periph)

/* gpio1_uart1_rx */
#define GPIO1_UART1_RX \
	BFLB_PINMUX(1, uart1, rx, periph)

/* gpio1_pwm_ch1 */
#define GPIO1_PWM_CH1 \
	BFLB_PINMUX(1, pwm, ch1, periph)

/* gpio1_cam_frame_vld */
#define GPIO1_CAM_FRAME_VLD \
	BFLB_PINMUX(1, cam, frame_vld, periph)

/* gpio1_jtag_tdi */
#define GPIO1_JTAG_TDI \
	BFLB_PINMUX(1, jtag, tdi, periph)

/* gpio1_fem_gpio1 */
#define GPIO1_FEM_GPIO1 \
	BFLB_PINMUX(1, fem, gpio1, periph)

/* gpio1_mii_txd0 */
#define GPIO1_MII_TXD0 \
	BFLB_PINMUX(1, mii, txd0, periph)

/* gpio1_qdec0_b */
#define GPIO1_QDEC0_B \
	BFLB_PINMUX(1, qdec0, b, periph)

/* gpio2_i2s_do */
#define GPIO2_I2S_DO \
	BFLB_PINMUX(2, i2s, do, periph)

/* gpio2_spi_ss */
#define GPIO2_SPI_SS \
	BFLB_PINMUX(2, spi, ss, periph)

/* gpio2_i2c_scl */
#define GPIO2_I2C_SCL \
	BFLB_PINMUX(2, i2c, scl, periph)

/* gpio2_uart0_rts */
#define GPIO2_UART0_RTS \
	BFLB_PINMUX(2, uart0, rts, periph)

/* gpio2_uart0_cts */
#define GPIO2_UART0_CTS \
	BFLB_PINMUX(2, uart0, cts, periph)

/* gpio2_uart0_tx */
#define GPIO2_UART0_TX \
	BFLB_PINMUX(2, uart0, tx, periph)

/* gpio2_uart0_rx */
#define GPIO2_UART0_RX \
	BFLB_PINMUX(2, uart0, rx, periph)

/* gpio2_uart1_rts */
#define GPIO2_UART1_RTS \
	BFLB_PINMUX(2, uart1, rts, periph)

/* gpio2_uart1_cts */
#define GPIO2_UART1_CTS \
	BFLB_PINMUX(2, uart1, cts, periph)

/* gpio2_uart1_tx */
#define GPIO2_UART1_TX \
	BFLB_PINMUX(2, uart1, tx, periph)

/* gpio2_uart1_rx */
#define GPIO2_UART1_RX \
	BFLB_PINMUX(2, uart1, rx, periph)

/* gpio2_pwm_ch2 */
#define GPIO2_PWM_CH2 \
	BFLB_PINMUX(2, pwm, ch2, periph)

/* gpio2_cam_line_vld */
#define GPIO2_CAM_LINE_VLD \
	BFLB_PINMUX(2, cam, line_vld, periph)

/* gpio2_jtag_tck */
#define GPIO2_JTAG_TCK \
	BFLB_PINMUX(2, jtag, tck, periph)

/* gpio2_fem_gpio2 */
#define GPIO2_FEM_GPIO2 \
	BFLB_PINMUX(2, fem, gpio2, periph)

/* gpio2_mii_txd1 */
#define GPIO2_MII_TXD1 \
	BFLB_PINMUX(2, mii, txd1, periph)

/* gpio2_qdec0_led */
#define GPIO2_QDEC0_LED \
	BFLB_PINMUX(2, qdec0, led, periph)

/* gpio3_i2s_di */
#define GPIO3_I2S_DI \
	BFLB_PINMUX(3, i2s, di, periph)

/* gpio3_spi_sclk */
#define GPIO3_SPI_SCLK \
	BFLB_PINMUX(3, spi, sclk, periph)

/* gpio3_i2c_sda */
#define GPIO3_I2C_SDA \
	BFLB_PINMUX(3, i2c, sda, periph)

/* gpio3_uart0_rts */
#define GPIO3_UART0_RTS \
	BFLB_PINMUX(3, uart0, rts, periph)

/* gpio3_uart0_cts */
#define GPIO3_UART0_CTS \
	BFLB_PINMUX(3, uart0, cts, periph)

/* gpio3_uart0_tx */
#define GPIO3_UART0_TX \
	BFLB_PINMUX(3, uart0, tx, periph)

/* gpio3_uart0_rx */
#define GPIO3_UART0_RX \
	BFLB_PINMUX(3, uart0, rx, periph)

/* gpio3_uart1_rts */
#define GPIO3_UART1_RTS \
	BFLB_PINMUX(3, uart1, rts, periph)

/* gpio3_uart1_cts */
#define GPIO3_UART1_CTS \
	BFLB_PINMUX(3, uart1, cts, periph)

/* gpio3_uart1_tx */
#define GPIO3_UART1_TX \
	BFLB_PINMUX(3, uart1, tx, periph)

/* gpio3_uart1_rx */
#define GPIO3_UART1_RX \
	BFLB_PINMUX(3, uart1, rx, periph)

/* gpio3_pwm_ch3 */
#define GPIO3_PWM_CH3 \
	BFLB_PINMUX(3, pwm, ch3, periph)

/* gpio3_cam_pix_dat0 */
#define GPIO3_CAM_PIX_DAT0 \
	BFLB_PINMUX(3, cam, pix_dat0, periph)

/* gpio3_jtag_tdo */
#define GPIO3_JTAG_TDO \
	BFLB_PINMUX(3, jtag, tdo, periph)

/* gpio3_fem_gpio3 */
#define GPIO3_FEM_GPIO3 \
	BFLB_PINMUX(3, fem, gpio3, periph)

/* gpio3_qdec1_a */
#define GPIO3_QDEC1_A \
	BFLB_PINMUX(3, qdec1, a, periph)

/* gpio7_i2s_di */
#define GPIO7_I2S_DI \
	BFLB_PINMUX(7, i2s, di, periph)

/* gpio7_spi_sclk */
#define GPIO7_SPI_SCLK \
	BFLB_PINMUX(7, spi, sclk, periph)

/* gpio7_i2c_sda */
#define GPIO7_I2C_SDA \
	BFLB_PINMUX(7, i2c, sda, periph)

/* gpio7_uart0_rts */
#define GPIO7_UART0_RTS \
	BFLB_PINMUX(7, uart0, rts, periph)

/* gpio7_uart0_cts */
#define GPIO7_UART0_CTS \
	BFLB_PINMUX(7, uart0, cts, periph)

/* gpio7_uart0_tx */
#define GPIO7_UART0_TX \
	BFLB_PINMUX(7, uart0, tx, periph)

/* gpio7_uart0_rx */
#define GPIO7_UART0_RX \
	BFLB_PINMUX(7, uart0, rx, periph)

/* gpio7_uart1_rts */
#define GPIO7_UART1_RTS \
	BFLB_PINMUX(7, uart1, rts, periph)

/* gpio7_uart1_cts */
#define GPIO7_UART1_CTS \
	BFLB_PINMUX(7, uart1, cts, periph)

/* gpio7_uart1_tx */
#define GPIO7_UART1_TX \
	BFLB_PINMUX(7, uart1, tx, periph)

/* gpio7_uart1_rx */
#define GPIO7_UART1_RX \
	BFLB_PINMUX(7, uart1, rx, periph)

/* gpio7_pwm_ch2 */
#define GPIO7_PWM_CH2 \
	BFLB_PINMUX(7, pwm, ch2, periph)

/* gpio7_jtag_tdo */
#define GPIO7_JTAG_TDO \
	BFLB_PINMUX(7, jtag, tdo, periph)

/* gpio7_fem_gpio2 */
#define GPIO7_FEM_GPIO2 \
	BFLB_PINMUX(7, fem, gpio2, periph)

/* gpio7_mii_rxd0 */
#define GPIO7_MII_RXD0 \
	BFLB_PINMUX(7, mii, rxd0, periph)

/* gpio7_qdec2_b */
#define GPIO7_QDEC2_B \
	BFLB_PINMUX(7, qdec2, b, periph)

/* gpio7_adc_ch6 */
#define GPIO7_ADC_CH6 \
	BFLB_PINMUX(7, adc, ch6, analog)

/* gpio7_usb_dp */
#define GPIO7_USB_DP \
	BFLB_PINMUX(7, usb, dp, analog)

/* gpio8_i2s_bclk */
#define GPIO8_I2S_BCLK \
	BFLB_PINMUX(8, i2s, bclk, periph)

/* gpio8_spi_mosi */
#define GPIO8_SPI_MOSI \
	BFLB_PINMUX(8, spi, mosi, periph)

/* gpio8_i2c_scl */
#define GPIO8_I2C_SCL \
	BFLB_PINMUX(8, i2c, scl, periph)

/* gpio8_uart0_rts */
#define GPIO8_UART0_RTS \
	BFLB_PINMUX(8, uart0, rts, periph)

/* gpio8_uart0_cts */
#define GPIO8_UART0_CTS \
	BFLB_PINMUX(8, uart0, cts, periph)

/* gpio8_uart0_tx */
#define GPIO8_UART0_TX \
	BFLB_PINMUX(8, uart0, tx, periph)

/* gpio8_uart0_rx */
#define GPIO8_UART0_RX \
	BFLB_PINMUX(8, uart0, rx, periph)

/* gpio8_uart1_rts */
#define GPIO8_UART1_RTS \
	BFLB_PINMUX(8, uart1, rts, periph)

/* gpio8_uart1_cts */
#define GPIO8_UART1_CTS \
	BFLB_PINMUX(8, uart1, cts, periph)

/* gpio8_uart1_tx */
#define GPIO8_UART1_TX \
	BFLB_PINMUX(8, uart1, tx, periph)

/* gpio8_uart1_rx */
#define GPIO8_UART1_RX \
	BFLB_PINMUX(8, uart1, rx, periph)

/* gpio8_pwm_ch3 */
#define GPIO8_PWM_CH3 \
	BFLB_PINMUX(8, pwm, ch3, periph)

/* gpio8_jtag_tms */
#define GPIO8_JTAG_TMS \
	BFLB_PINMUX(8, jtag, tms, periph)

/* gpio8_fem_gpio3 */
#define GPIO8_FEM_GPIO3 \
	BFLB_PINMUX(8, fem, gpio3, periph)

/* gpio8_mii_rxd1 */
#define GPIO8_MII_RXD1 \
	BFLB_PINMUX(8, mii, rxd1, periph)

/* gpio8_qdec2_led */
#define GPIO8_QDEC2_LED \
	BFLB_PINMUX(8, qdec2, led, periph)

/* gpio8_adc_ch0 */
#define GPIO8_ADC_CH0 \
	BFLB_PINMUX(8, adc, ch0, analog)

/* gpio8_usb_dm */
#define GPIO8_USB_DM \
	BFLB_PINMUX(8, usb, dm, analog)

/* gpio9_i2s_fs */
#define GPIO9_I2S_FS \
	BFLB_PINMUX(9, i2s, fs, periph)

/* gpio9_spi_miso */
#define GPIO9_SPI_MISO \
	BFLB_PINMUX(9, spi, miso, periph)

/* gpio9_i2c_sda */
#define GPIO9_I2C_SDA \
	BFLB_PINMUX(9, i2c, sda, periph)

/* gpio9_uart0_rts */
#define GPIO9_UART0_RTS \
	BFLB_PINMUX(9, uart0, rts, periph)

/* gpio9_uart0_cts */
#define GPIO9_UART0_CTS \
	BFLB_PINMUX(9, uart0, cts, periph)

/* gpio9_uart0_tx */
#define GPIO9_UART0_TX \
	BFLB_PINMUX(9, uart0, tx, periph)

/* gpio9_uart0_rx */
#define GPIO9_UART0_RX \
	BFLB_PINMUX(9, uart0, rx, periph)

/* gpio9_uart1_rts */
#define GPIO9_UART1_RTS \
	BFLB_PINMUX(9, uart1, rts, periph)

/* gpio9_uart1_cts */
#define GPIO9_UART1_CTS \
	BFLB_PINMUX(9, uart1, cts, periph)

/* gpio9_uart1_tx */
#define GPIO9_UART1_TX \
	BFLB_PINMUX(9, uart1, tx, periph)

/* gpio9_uart1_rx */
#define GPIO9_UART1_RX \
	BFLB_PINMUX(9, uart1, rx, periph)

/* gpio9_pwm_ch4 */
#define GPIO9_PWM_CH4 \
	BFLB_PINMUX(9, pwm, ch4, periph)

/* gpio9_jtag_tdi */
#define GPIO9_JTAG_TDI \
	BFLB_PINMUX(9, jtag, tdi, periph)

/* gpio9_fem_gpio4 */
#define GPIO9_FEM_GPIO4 \
	BFLB_PINMUX(9, fem, gpio4, periph)

/* gpio9_qdec0_a */
#define GPIO9_QDEC0_A \
	BFLB_PINMUX(9, qdec0, a, periph)

/* gpio9_adc_ch7 */
#define GPIO9_ADC_CH7 \
	BFLB_PINMUX(9, adc, ch7, analog)

/* gpio10_i2s_do */
#define GPIO10_I2S_DO \
	BFLB_PINMUX(10, i2s, do, periph)

/* gpio10_spi_ss */
#define GPIO10_SPI_SS \
	BFLB_PINMUX(10, spi, ss, periph)

/* gpio10_i2c_scl */
#define GPIO10_I2C_SCL \
	BFLB_PINMUX(10, i2c, scl, periph)

/* gpio10_uart0_rts */
#define GPIO10_UART0_RTS \
	BFLB_PINMUX(10, uart0, rts, periph)

/* gpio10_uart0_cts */
#define GPIO10_UART0_CTS \
	BFLB_PINMUX(10, uart0, cts, periph)

/* gpio10_uart0_tx */
#define GPIO10_UART0_TX \
	BFLB_PINMUX(10, uart0, tx, periph)

/* gpio10_uart0_rx */
#define GPIO10_UART0_RX \
	BFLB_PINMUX(10, uart0, rx, periph)

/* gpio10_uart1_rts */
#define GPIO10_UART1_RTS \
	BFLB_PINMUX(10, uart1, rts, periph)

/* gpio10_uart1_cts */
#define GPIO10_UART1_CTS \
	BFLB_PINMUX(10, uart1, cts, periph)

/* gpio10_uart1_tx */
#define GPIO10_UART1_TX \
	BFLB_PINMUX(10, uart1, tx, periph)

/* gpio10_uart1_rx */
#define GPIO10_UART1_RX \
	BFLB_PINMUX(10, uart1, rx, periph)

/* gpio10_pwm_ch0 */
#define GPIO10_PWM_CH0 \
	BFLB_PINMUX(10, pwm, ch0, periph)

/* gpio10_jtag_tck */
#define GPIO10_JTAG_TCK \
	BFLB_PINMUX(10, jtag, tck, periph)

/* gpio10_fem_gpio0 */
#define GPIO10_FEM_GPIO0 \
	BFLB_PINMUX(10, fem, gpio0, periph)

/* gpio10_qdec0_b */
#define GPIO10_QDEC0_B \
	BFLB_PINMUX(10, qdec0, b, periph)

/* gpio10_mic_bias */
#define GPIO10_MIC_BIAS \
	BFLB_PINMUX(10, mic, bias, analog)

/* gpio11_i2s_di */
#define GPIO11_I2S_DI \
	BFLB_PINMUX(11, i2s, di, periph)

/* gpio11_spi_sclk */
#define GPIO11_SPI_SCLK \
	BFLB_PINMUX(11, spi, sclk, periph)

/* gpio11_i2c_sda */
#define GPIO11_I2C_SDA \
	BFLB_PINMUX(11, i2c, sda, periph)

/* gpio11_uart0_rts */
#define GPIO11_UART0_RTS \
	BFLB_PINMUX(11, uart0, rts, periph)

/* gpio11_uart0_cts */
#define GPIO11_UART0_CTS \
	BFLB_PINMUX(11, uart0, cts, periph)

/* gpio11_uart0_tx */
#define GPIO11_UART0_TX \
	BFLB_PINMUX(11, uart0, tx, periph)

/* gpio11_uart0_rx */
#define GPIO11_UART0_RX \
	BFLB_PINMUX(11, uart0, rx, periph)

/* gpio11_uart1_rts */
#define GPIO11_UART1_RTS \
	BFLB_PINMUX(11, uart1, rts, periph)

/* gpio11_uart1_cts */
#define GPIO11_UART1_CTS \
	BFLB_PINMUX(11, uart1, cts, periph)

/* gpio11_uart1_tx */
#define GPIO11_UART1_TX \
	BFLB_PINMUX(11, uart1, tx, periph)

/* gpio11_uart1_rx */
#define GPIO11_UART1_RX \
	BFLB_PINMUX(11, uart1, rx, periph)

/* gpio11_pwm_ch1 */
#define GPIO11_PWM_CH1 \
	BFLB_PINMUX(11, pwm, ch1, periph)

/* gpio11_jtag_tdo */
#define GPIO11_JTAG_TDO \
	BFLB_PINMUX(11, jtag, tdo, periph)

/* gpio11_fem_gpio1 */
#define GPIO11_FEM_GPIO1 \
	BFLB_PINMUX(11, fem, gpio1, periph)

/* gpio11_qdec0_led */
#define GPIO11_QDEC0_LED \
	BFLB_PINMUX(11, qdec0, led, periph)

/* gpio11_adc_ch3 */
#define GPIO11_ADC_CH3 \
	BFLB_PINMUX(11, adc, ch3, analog)

/* gpio11_dac_cha */
#define GPIO11_DAC_CHA \
	BFLB_PINMUX(11, dac, cha, analog)

/* gpio14_i2s_do */
#define GPIO14_I2S_DO \
	BFLB_PINMUX(14, i2s, do, periph)

/* gpio14_spi_ss */
#define GPIO14_SPI_SS \
	BFLB_PINMUX(14, spi, ss, periph)

/* gpio14_i2c_scl */
#define GPIO14_I2C_SCL \
	BFLB_PINMUX(14, i2c, scl, periph)

/* gpio14_uart0_rts */
#define GPIO14_UART0_RTS \
	BFLB_PINMUX(14, uart0, rts, periph)

/* gpio14_uart0_cts */
#define GPIO14_UART0_CTS \
	BFLB_PINMUX(14, uart0, cts, periph)

/* gpio14_uart0_tx */
#define GPIO14_UART0_TX \
	BFLB_PINMUX(14, uart0, tx, periph)

/* gpio14_uart0_rx */
#define GPIO14_UART0_RX \
	BFLB_PINMUX(14, uart0, rx, periph)

/* gpio14_uart1_rts */
#define GPIO14_UART1_RTS \
	BFLB_PINMUX(14, uart1, rts, periph)

/* gpio14_uart1_cts */
#define GPIO14_UART1_CTS \
	BFLB_PINMUX(14, uart1, cts, periph)

/* gpio14_uart1_tx */
#define GPIO14_UART1_TX \
	BFLB_PINMUX(14, uart1, tx, periph)

/* gpio14_uart1_rx */
#define GPIO14_UART1_RX \
	BFLB_PINMUX(14, uart1, rx, periph)

/* gpio14_pwm_ch4 */
#define GPIO14_PWM_CH4 \
	BFLB_PINMUX(14, pwm, ch4, periph)

/* gpio14_jtag_tck */
#define GPIO14_JTAG_TCK \
	BFLB_PINMUX(14, jtag, tck, periph)

/* gpio14_fem_gpio4 */
#define GPIO14_FEM_GPIO4 \
	BFLB_PINMUX(14, fem, gpio4, periph)

/* gpio14_qdec1_led */
#define GPIO14_QDEC1_LED \
	BFLB_PINMUX(14, qdec1, led, periph)

/* gpio14_adc_ch5 */
#define GPIO14_ADC_CH5 \
	BFLB_PINMUX(14, adc, ch5, analog)

/* gpio14_atest_out0 */
#define GPIO14_ATEST_OUT0 \
	BFLB_PINMUX(14, atest, out0, analog)

/* gpio15_i2s_di */
#define GPIO15_I2S_DI \
	BFLB_PINMUX(15, i2s, di, periph)

/* gpio15_spi_sclk */
#define GPIO15_SPI_SCLK \
	BFLB_PINMUX(15, spi, sclk, periph)

/* gpio15_i2c_sda */
#define GPIO15_I2C_SDA \
	BFLB_PINMUX(15, i2c, sda, periph)

/* gpio15_uart0_rts */
#define GPIO15_UART0_RTS \
	BFLB_PINMUX(15, uart0, rts, periph)

/* gpio15_uart0_cts */
#define GPIO15_UART0_CTS \
	BFLB_PINMUX(15, uart0, cts, periph)

/* gpio15_uart0_tx */
#define GPIO15_UART0_TX \
	BFLB_PINMUX(15, uart0, tx, periph)

/* gpio15_uart0_rx */
#define GPIO15_UART0_RX \
	BFLB_PINMUX(15, uart0, rx, periph)

/* gpio15_uart1_rts */
#define GPIO15_UART1_RTS \
	BFLB_PINMUX(15, uart1, rts, periph)

/* gpio15_uart1_cts */
#define GPIO15_UART1_CTS \
	BFLB_PINMUX(15, uart1, cts, periph)

/* gpio15_uart1_tx */
#define GPIO15_UART1_TX \
	BFLB_PINMUX(15, uart1, tx, periph)

/* gpio15_uart1_rx */
#define GPIO15_UART1_RX \
	BFLB_PINMUX(15, uart1, rx, periph)

/* gpio15_pwm_ch0 */
#define GPIO15_PWM_CH0 \
	BFLB_PINMUX(15, pwm, ch0, periph)

/* gpio15_jtag_tdo */
#define GPIO15_JTAG_TDO \
	BFLB_PINMUX(15, jtag, tdo, periph)

/* gpio15_fem_gpio0 */
#define GPIO15_FEM_GPIO0 \
	BFLB_PINMUX(15, fem, gpio0, periph)

/* gpio15_qdec2_a */
#define GPIO15_QDEC2_A \
	BFLB_PINMUX(15, qdec2, a, periph)

/* gpio15_adc_ch1 */
#define GPIO15_ADC_CH1 \
	BFLB_PINMUX(15, adc, ch1, analog)

/* gpio15_atest_out1 */
#define GPIO15_ATEST_OUT1 \
	BFLB_PINMUX(15, atest, out1, analog)

/* gpio17_flash1_d0 */
#define GPIO17_FLASH1_D0 \
	BFLB_PINMUX(17, flash1, d0, periph)

/* gpio17_flash2_cs2 */
#define GPIO17_FLASH2_CS2 \
	BFLB_PINMUX(17, flash2, cs2, periph)

/* gpio17_i2s_fs */
#define GPIO17_I2S_FS \
	BFLB_PINMUX(17, i2s, fs, periph)

/* gpio17_spi_miso */
#define GPIO17_SPI_MISO \
	BFLB_PINMUX(17, spi, miso, periph)

/* gpio17_i2c_sda */
#define GPIO17_I2C_SDA \
	BFLB_PINMUX(17, i2c, sda, periph)

/* gpio17_uart0_rts */
#define GPIO17_UART0_RTS \
	BFLB_PINMUX(17, uart0, rts, periph)

/* gpio17_uart0_cts */
#define GPIO17_UART0_CTS \
	BFLB_PINMUX(17, uart0, cts, periph)

/* gpio17_uart0_tx */
#define GPIO17_UART0_TX \
	BFLB_PINMUX(17, uart0, tx, periph)

/* gpio17_uart0_rx */
#define GPIO17_UART0_RX \
	BFLB_PINMUX(17, uart0, rx, periph)

/* gpio17_uart1_rts */
#define GPIO17_UART1_RTS \
	BFLB_PINMUX(17, uart1, rts, periph)

/* gpio17_uart1_cts */
#define GPIO17_UART1_CTS \
	BFLB_PINMUX(17, uart1, cts, periph)

/* gpio17_uart1_tx */
#define GPIO17_UART1_TX \
	BFLB_PINMUX(17, uart1, tx, periph)

/* gpio17_uart1_rx */
#define GPIO17_UART1_RX \
	BFLB_PINMUX(17, uart1, rx, periph)

/* gpio17_pwm_ch2 */
#define GPIO17_PWM_CH2 \
	BFLB_PINMUX(17, pwm, ch2, periph)

/* gpio17_jtag_tdi */
#define GPIO17_JTAG_TDI \
	BFLB_PINMUX(17, jtag, tdi, periph)

/* gpio17_fem_gpio2 */
#define GPIO17_FEM_GPIO2 \
	BFLB_PINMUX(17, fem, gpio2, periph)

/* gpio17_qdec2_led */
#define GPIO17_QDEC2_LED \
	BFLB_PINMUX(17, qdec2, led, periph)

/* gpio17_adc_ch2 */
#define GPIO17_ADC_CH2 \
	BFLB_PINMUX(17, adc, ch2, analog)

/* gpio17_dac_chb */
#define GPIO17_DAC_CHB \
	BFLB_PINMUX(17, dac, chb, analog)

/* gpio18_flash1_d1 */
#define GPIO18_FLASH1_D1 \
	BFLB_PINMUX(18, flash1, d1, periph)

/* gpio18_i2s_do */
#define GPIO18_I2S_DO \
	BFLB_PINMUX(18, i2s, do, periph)

/* gpio18_spi_ss */
#define GPIO18_SPI_SS \
	BFLB_PINMUX(18, spi, ss, periph)

/* gpio18_i2c_scl */
#define GPIO18_I2C_SCL \
	BFLB_PINMUX(18, i2c, scl, periph)

/* gpio18_uart0_rts */
#define GPIO18_UART0_RTS \
	BFLB_PINMUX(18, uart0, rts, periph)

/* gpio18_uart0_cts */
#define GPIO18_UART0_CTS \
	BFLB_PINMUX(18, uart0, cts, periph)

/* gpio18_uart0_tx */
#define GPIO18_UART0_TX \
	BFLB_PINMUX(18, uart0, tx, periph)

/* gpio18_uart0_rx */
#define GPIO18_UART0_RX \
	BFLB_PINMUX(18, uart0, rx, periph)

/* gpio18_uart1_rts */
#define GPIO18_UART1_RTS \
	BFLB_PINMUX(18, uart1, rts, periph)

/* gpio18_uart1_cts */
#define GPIO18_UART1_CTS \
	BFLB_PINMUX(18, uart1, cts, periph)

/* gpio18_uart1_tx */
#define GPIO18_UART1_TX \
	BFLB_PINMUX(18, uart1, tx, periph)

/* gpio18_uart1_rx */
#define GPIO18_UART1_RX \
	BFLB_PINMUX(18, uart1, rx, periph)

/* gpio18_pwm_ch3 */
#define GPIO18_PWM_CH3 \
	BFLB_PINMUX(18, pwm, ch3, periph)

/* gpio18_cam_pix_dat5 */
#define GPIO18_CAM_PIX_DAT5 \
	BFLB_PINMUX(18, cam, pix_dat5, periph)

/* gpio18_jtag_tck */
#define GPIO18_JTAG_TCK \
	BFLB_PINMUX(18, jtag, tck, periph)

/* gpio18_fem_gpio3 */
#define GPIO18_FEM_GPIO3 \
	BFLB_PINMUX(18, fem, gpio3, periph)

/* gpio18_mii_mdc */
#define GPIO18_MII_MDC \
	BFLB_PINMUX(18, mii, mdc, periph)

/* gpio18_qdec0_a */
#define GPIO18_QDEC0_A \
	BFLB_PINMUX(18, qdec0, a, periph)

/* gpio18_adc_ch8 */
#define GPIO18_ADC_CH8 \
	BFLB_PINMUX(18, adc, ch8, analog)

/* gpio19_flash1_cs */
#define GPIO19_FLASH1_CS \
	BFLB_PINMUX(19, flash1, cs, periph)

/* gpio19_i2s_di */
#define GPIO19_I2S_DI \
	BFLB_PINMUX(19, i2s, di, periph)

/* gpio19_spi_sclk */
#define GPIO19_SPI_SCLK \
	BFLB_PINMUX(19, spi, sclk, periph)

/* gpio19_i2c_sda */
#define GPIO19_I2C_SDA \
	BFLB_PINMUX(19, i2c, sda, periph)

/* gpio19_uart0_rts */
#define GPIO19_UART0_RTS \
	BFLB_PINMUX(19, uart0, rts, periph)

/* gpio19_uart0_cts */
#define GPIO19_UART0_CTS \
	BFLB_PINMUX(19, uart0, cts, periph)

/* gpio19_uart0_tx */
#define GPIO19_UART0_TX \
	BFLB_PINMUX(19, uart0, tx, periph)

/* gpio19_uart0_rx */
#define GPIO19_UART0_RX \
	BFLB_PINMUX(19, uart0, rx, periph)

/* gpio19_uart1_rts */
#define GPIO19_UART1_RTS \
	BFLB_PINMUX(19, uart1, rts, periph)

/* gpio19_uart1_cts */
#define GPIO19_UART1_CTS \
	BFLB_PINMUX(19, uart1, cts, periph)

/* gpio19_uart1_tx */
#define GPIO19_UART1_TX \
	BFLB_PINMUX(19, uart1, tx, periph)

/* gpio19_uart1_rx */
#define GPIO19_UART1_RX \
	BFLB_PINMUX(19, uart1, rx, periph)

/* gpio19_pwm_ch4 */
#define GPIO19_PWM_CH4 \
	BFLB_PINMUX(19, pwm, ch4, periph)

/* gpio19_cam_pix_dat6 */
#define GPIO19_CAM_PIX_DAT6 \
	BFLB_PINMUX(19, cam, pix_dat6, periph)

/* gpio19_jtag_tdo */
#define GPIO19_JTAG_TDO \
	BFLB_PINMUX(19, jtag, tdo, periph)

/* gpio19_fem_gpio4 */
#define GPIO19_FEM_GPIO4 \
	BFLB_PINMUX(19, fem, gpio4, periph)

/* gpio19_mii_mdio */
#define GPIO19_MII_MDIO \
	BFLB_PINMUX(19, mii, mdio, periph)

/* gpio19_qdec0_b */
#define GPIO19_QDEC0_B \
	BFLB_PINMUX(19, qdec0, b, periph)

/* gpio19_adc_ch9 */
#define GPIO19_ADC_CH9 \
	BFLB_PINMUX(19, adc, ch9, analog)

/* gpio20_flash1_d3 */
#define GPIO20_FLASH1_D3 \
	BFLB_PINMUX(20, flash1, d3, periph)

/* gpio20_i2s_bclk */
#define GPIO20_I2S_BCLK \
	BFLB_PINMUX(20, i2s, bclk, periph)

/* gpio20_spi_mosi */
#define GPIO20_SPI_MOSI \
	BFLB_PINMUX(20, spi, mosi, periph)

/* gpio20_i2c_scl */
#define GPIO20_I2C_SCL \
	BFLB_PINMUX(20, i2c, scl, periph)

/* gpio20_uart0_rts */
#define GPIO20_UART0_RTS \
	BFLB_PINMUX(20, uart0, rts, periph)

/* gpio20_uart0_cts */
#define GPIO20_UART0_CTS \
	BFLB_PINMUX(20, uart0, cts, periph)

/* gpio20_uart0_tx */
#define GPIO20_UART0_TX \
	BFLB_PINMUX(20, uart0, tx, periph)

/* gpio20_uart0_rx */
#define GPIO20_UART0_RX \
	BFLB_PINMUX(20, uart0, rx, periph)

/* gpio20_uart1_rts */
#define GPIO20_UART1_RTS \
	BFLB_PINMUX(20, uart1, rts, periph)

/* gpio20_uart1_cts */
#define GPIO20_UART1_CTS \
	BFLB_PINMUX(20, uart1, cts, periph)

/* gpio20_uart1_tx */
#define GPIO20_UART1_TX \
	BFLB_PINMUX(20, uart1, tx, periph)

/* gpio20_uart1_rx */
#define GPIO20_UART1_RX \
	BFLB_PINMUX(20, uart1, rx, periph)

/* gpio20_pwm_ch0 */
#define GPIO20_PWM_CH0 \
	BFLB_PINMUX(20, pwm, ch0, periph)

/* gpio20_cam_pix_dat7 */
#define GPIO20_CAM_PIX_DAT7 \
	BFLB_PINMUX(20, cam, pix_dat7, periph)

/* gpio20_jtag_tms */
#define GPIO20_JTAG_TMS \
	BFLB_PINMUX(20, jtag, tms, periph)

/* gpio20_fem_gpio0 */
#define GPIO20_FEM_GPIO0 \
	BFLB_PINMUX(20, fem, gpio0, periph)

/* gpio20_mii_rxerr */
#define GPIO20_MII_RXERR \
	BFLB_PINMUX(20, mii, rxerr, periph)

/* gpio20_qdec0_led */
#define GPIO20_QDEC0_LED \
	BFLB_PINMUX(20, qdec0, led, periph)

/* gpio20_adc_ch10 */
#define GPIO20_ADC_CH10 \
	BFLB_PINMUX(20, adc, ch10, analog)

/* gpio21_flash1_clk */
#define GPIO21_FLASH1_CLK \
	BFLB_PINMUX(21, flash1, clk, periph)

/* gpio21_i2s_fs */
#define GPIO21_I2S_FS \
	BFLB_PINMUX(21, i2s, fs, periph)

/* gpio21_spi_miso */
#define GPIO21_SPI_MISO \
	BFLB_PINMUX(21, spi, miso, periph)

/* gpio21_i2c_sda */
#define GPIO21_I2C_SDA \
	BFLB_PINMUX(21, i2c, sda, periph)

/* gpio21_uart0_rts */
#define GPIO21_UART0_RTS \
	BFLB_PINMUX(21, uart0, rts, periph)

/* gpio21_uart0_cts */
#define GPIO21_UART0_CTS \
	BFLB_PINMUX(21, uart0, cts, periph)

/* gpio21_uart0_tx */
#define GPIO21_UART0_TX \
	BFLB_PINMUX(21, uart0, tx, periph)

/* gpio21_uart0_rx */
#define GPIO21_UART0_RX \
	BFLB_PINMUX(21, uart0, rx, periph)

/* gpio21_uart1_rts */
#define GPIO21_UART1_RTS \
	BFLB_PINMUX(21, uart1, rts, periph)

/* gpio21_uart1_cts */
#define GPIO21_UART1_CTS \
	BFLB_PINMUX(21, uart1, cts, periph)

/* gpio21_uart1_tx */
#define GPIO21_UART1_TX \
	BFLB_PINMUX(21, uart1, tx, periph)

/* gpio21_uart1_rx */
#define GPIO21_UART1_RX \
	BFLB_PINMUX(21, uart1, rx, periph)

/* gpio21_pwm_ch1 */
#define GPIO21_PWM_CH1 \
	BFLB_PINMUX(21, pwm, ch1, periph)

/* gpio21_jtag_tdi */
#define GPIO21_JTAG_TDI \
	BFLB_PINMUX(21, jtag, tdi, periph)

/* gpio21_fem_gpio1 */
#define GPIO21_FEM_GPIO1 \
	BFLB_PINMUX(21, fem, gpio1, periph)

/* gpio21_mii_tx_en */
#define GPIO21_MII_TX_EN \
	BFLB_PINMUX(21, mii, tx_en, periph)

/* gpio21_qdec1_led */
#define GPIO21_QDEC1_LED \
	BFLB_PINMUX(21, qdec1, led, periph)

/* gpio21_adc_ch11 */
#define GPIO21_ADC_CH11 \
	BFLB_PINMUX(21, adc, ch11, analog)

/* gpio22_flash1_d2 */
#define GPIO22_FLASH1_D2 \
	BFLB_PINMUX(22, flash1, d2, periph)

/* gpio22_i2s_do */
#define GPIO22_I2S_DO \
	BFLB_PINMUX(22, i2s, do, periph)

/* gpio22_spi_ss */
#define GPIO22_SPI_SS \
	BFLB_PINMUX(22, spi, ss, periph)

/* gpio22_i2c_scl */
#define GPIO22_I2C_SCL \
	BFLB_PINMUX(22, i2c, scl, periph)

/* gpio22_uart0_rts */
#define GPIO22_UART0_RTS \
	BFLB_PINMUX(22, uart0, rts, periph)

/* gpio22_uart0_cts */
#define GPIO22_UART0_CTS \
	BFLB_PINMUX(22, uart0, cts, periph)

/* gpio22_uart0_tx */
#define GPIO22_UART0_TX \
	BFLB_PINMUX(22, uart0, tx, periph)

/* gpio22_uart0_rx */
#define GPIO22_UART0_RX \
	BFLB_PINMUX(22, uart0, rx, periph)

/* gpio22_uart1_rts */
#define GPIO22_UART1_RTS \
	BFLB_PINMUX(22, uart1, rts, periph)

/* gpio22_uart1_cts */
#define GPIO22_UART1_CTS \
	BFLB_PINMUX(22, uart1, cts, periph)

/* gpio22_uart1_tx */
#define GPIO22_UART1_TX \
	BFLB_PINMUX(22, uart1, tx, periph)

/* gpio22_uart1_rx */
#define GPIO22_UART1_RX \
	BFLB_PINMUX(22, uart1, rx, periph)

/* gpio22_pwm_ch2 */
#define GPIO22_PWM_CH2 \
	BFLB_PINMUX(22, pwm, ch2, periph)

/* gpio22_jtag_tck */
#define GPIO22_JTAG_TCK \
	BFLB_PINMUX(22, jtag, tck, periph)

/* gpio22_fem_gpio2 */
#define GPIO22_FEM_GPIO2 \
	BFLB_PINMUX(22, fem, gpio2, periph)

/* gpio22_mii_rx_dv */
#define GPIO22_MII_RX_DV \
	BFLB_PINMUX(22, mii, rx_dv, periph)

/* gpio22_qdec1_b */
#define GPIO22_QDEC1_B \
	BFLB_PINMUX(22, qdec1, b, periph)

/* gpio22_ir_tx */
#define GPIO22_IR_TX \
	BFLB_PINMUX(22, ir, tx, analog)

/* gpio23_flash2_d2 */
#define GPIO23_FLASH2_D2 \
	BFLB_PINMUX(23, flash2, d2, periph)

/* gpio23_i2s_di */
#define GPIO23_I2S_DI \
	BFLB_PINMUX(23, i2s, di, periph)

/* gpio23_spi_sclk */
#define GPIO23_SPI_SCLK \
	BFLB_PINMUX(23, spi, sclk, periph)

/* gpio23_i2c_sda */
#define GPIO23_I2C_SDA \
	BFLB_PINMUX(23, i2c, sda, periph)

/* gpio23_uart0_rts */
#define GPIO23_UART0_RTS \
	BFLB_PINMUX(23, uart0, rts, periph)

/* gpio23_uart0_cts */
#define GPIO23_UART0_CTS \
	BFLB_PINMUX(23, uart0, cts, periph)

/* gpio23_uart0_tx */
#define GPIO23_UART0_TX \
	BFLB_PINMUX(23, uart0, tx, periph)

/* gpio23_uart0_rx */
#define GPIO23_UART0_RX \
	BFLB_PINMUX(23, uart0, rx, periph)

/* gpio23_uart1_rts */
#define GPIO23_UART1_RTS \
	BFLB_PINMUX(23, uart1, rts, periph)

/* gpio23_uart1_cts */
#define GPIO23_UART1_CTS \
	BFLB_PINMUX(23, uart1, cts, periph)

/* gpio23_uart1_tx */
#define GPIO23_UART1_TX \
	BFLB_PINMUX(23, uart1, tx, periph)

/* gpio23_uart1_rx */
#define GPIO23_UART1_RX \
	BFLB_PINMUX(23, uart1, rx, periph)

/* gpio23_pwm_ch3 */
#define GPIO23_PWM_CH3 \
	BFLB_PINMUX(23, pwm, ch3, periph)

/* gpio23_cam_pix_dat4 */
#define GPIO23_CAM_PIX_DAT4 \
	BFLB_PINMUX(23, cam, pix_dat4, periph)

/* gpio23_jtag_tdo */
#define GPIO23_JTAG_TDO \
	BFLB_PINMUX(23, jtag, tdo, periph)

/* gpio23_fem_gpio3 */
#define GPIO23_FEM_GPIO3 \
	BFLB_PINMUX(23, fem, gpio3, periph)

/* gpio23_qdec1_led */
#define GPIO23_QDEC1_LED \
	BFLB_PINMUX(23, qdec1, led, periph)

/* gpio23_ir_tx */
#define GPIO23_IR_TX \
	BFLB_PINMUX(23, ir, tx, analog)

/* gpio24_flash2_d1 */
#define GPIO24_FLASH2_D1 \
	BFLB_PINMUX(24, flash2, d1, periph)

/* gpio24_i2s_blck */
#define GPIO24_I2S_BLCK \
	BFLB_PINMUX(24, i2s, blck, periph)

/* gpio24_spi_mosi */
#define GPIO24_SPI_MOSI \
	BFLB_PINMUX(24, spi, mosi, periph)

/* gpio24_i2c_scl */
#define GPIO24_I2C_SCL \
	BFLB_PINMUX(24, i2c, scl, periph)

/* gpio24_uart0_rts */
#define GPIO24_UART0_RTS \
	BFLB_PINMUX(24, uart0, rts, periph)

/* gpio24_uart0_cts */
#define GPIO24_UART0_CTS \
	BFLB_PINMUX(24, uart0, cts, periph)

/* gpio24_uart0_tx */
#define GPIO24_UART0_TX \
	BFLB_PINMUX(24, uart0, tx, periph)

/* gpio24_uart0_rx */
#define GPIO24_UART0_RX \
	BFLB_PINMUX(24, uart0, rx, periph)

/* gpio24_uart1_rts */
#define GPIO24_UART1_RTS \
	BFLB_PINMUX(24, uart1, rts, periph)

/* gpio24_uart1_cts */
#define GPIO24_UART1_CTS \
	BFLB_PINMUX(24, uart1, cts, periph)

/* gpio24_uart1_tx */
#define GPIO24_UART1_TX \
	BFLB_PINMUX(24, uart1, tx, periph)

/* gpio24_uart1_rx */
#define GPIO24_UART1_RX \
	BFLB_PINMUX(24, uart1, rx, periph)

/* gpio24_pwm_ch4 */
#define GPIO24_PWM_CH4 \
	BFLB_PINMUX(24, pwm, ch4, periph)

/* gpio24_cam_pix_dat5 */
#define GPIO24_CAM_PIX_DAT5 \
	BFLB_PINMUX(24, cam, pix_dat5, periph)

/* gpio24_jtag_tms */
#define GPIO24_JTAG_TMS \
	BFLB_PINMUX(24, jtag, tms, periph)

/* gpio24_fem_gpio4 */
#define GPIO24_FEM_GPIO4 \
	BFLB_PINMUX(24, fem, gpio4, periph)

/* gpio24_mii_mdc */
#define GPIO24_MII_MDC \
	BFLB_PINMUX(24, mii, mdc, periph)

/* gpio24_qdec2_a */
#define GPIO24_QDEC2_A \
	BFLB_PINMUX(24, qdec2, a, periph)

/* gpio25_flash2_cs */
#define GPIO25_FLASH2_CS \
	BFLB_PINMUX(25, flash2, cs, periph)

/* gpio25_i2s_fs */
#define GPIO25_I2S_FS \
	BFLB_PINMUX(25, i2s, fs, periph)

/* gpio25_spi_miso */
#define GPIO25_SPI_MISO \
	BFLB_PINMUX(25, spi, miso, periph)

/* gpio25_i2c_sda */
#define GPIO25_I2C_SDA \
	BFLB_PINMUX(25, i2c, sda, periph)

/* gpio25_uart0_rts */
#define GPIO25_UART0_RTS \
	BFLB_PINMUX(25, uart0, rts, periph)

/* gpio25_uart0_cts */
#define GPIO25_UART0_CTS \
	BFLB_PINMUX(25, uart0, cts, periph)

/* gpio25_uart0_tx */
#define GPIO25_UART0_TX \
	BFLB_PINMUX(25, uart0, tx, periph)

/* gpio25_uart0_rx */
#define GPIO25_UART0_RX \
	BFLB_PINMUX(25, uart0, rx, periph)

/* gpio25_uart1_rts */
#define GPIO25_UART1_RTS \
	BFLB_PINMUX(25, uart1, rts, periph)

/* gpio25_uart1_cts */
#define GPIO25_UART1_CTS \
	BFLB_PINMUX(25, uart1, cts, periph)

/* gpio25_uart1_tx */
#define GPIO25_UART1_TX \
	BFLB_PINMUX(25, uart1, tx, periph)

/* gpio25_uart1_rx */
#define GPIO25_UART1_RX \
	BFLB_PINMUX(25, uart1, rx, periph)

/* gpio25_pwm_ch0 */
#define GPIO25_PWM_CH0 \
	BFLB_PINMUX(25, pwm, ch0, periph)

/* gpio25_cam_pix_dat6 */
#define GPIO25_CAM_PIX_DAT6 \
	BFLB_PINMUX(25, cam, pix_dat6, periph)

/* gpio25_jtag_tdi */
#define GPIO25_JTAG_TDI \
	BFLB_PINMUX(25, jtag, tdi, periph)

/* gpio25_fem_gpio0 */
#define GPIO25_FEM_GPIO0 \
	BFLB_PINMUX(25, fem, gpio0, periph)

/* gpio25_mii_mdio */
#define GPIO25_MII_MDIO \
	BFLB_PINMUX(25, mii, mdio, periph)

/* gpio25_qdec2_b */
#define GPIO25_QDEC2_B \
	BFLB_PINMUX(25, qdec2, b, periph)

/* gpio26_flash2_d3 */
#define GPIO26_FLASH2_D3 \
	BFLB_PINMUX(26, flash2, d3, periph)

/* gpio26_i2s_do */
#define GPIO26_I2S_DO \
	BFLB_PINMUX(26, i2s, do, periph)

/* gpio26_spi_ss */
#define GPIO26_SPI_SS \
	BFLB_PINMUX(26, spi, ss, periph)

/* gpio26_i2c_scl */
#define GPIO26_I2C_SCL \
	BFLB_PINMUX(26, i2c, scl, periph)

/* gpio26_uart0_rts */
#define GPIO26_UART0_RTS \
	BFLB_PINMUX(26, uart0, rts, periph)

/* gpio26_uart0_cts */
#define GPIO26_UART0_CTS \
	BFLB_PINMUX(26, uart0, cts, periph)

/* gpio26_uart0_tx */
#define GPIO26_UART0_TX \
	BFLB_PINMUX(26, uart0, tx, periph)

/* gpio26_uart0_rx */
#define GPIO26_UART0_RX \
	BFLB_PINMUX(26, uart0, rx, periph)

/* gpio26_uart1_rts */
#define GPIO26_UART1_RTS \
	BFLB_PINMUX(26, uart1, rts, periph)

/* gpio26_uart1_cts */
#define GPIO26_UART1_CTS \
	BFLB_PINMUX(26, uart1, cts, periph)

/* gpio26_uart1_tx */
#define GPIO26_UART1_TX \
	BFLB_PINMUX(26, uart1, tx, periph)

/* gpio26_uart1_rx */
#define GPIO26_UART1_RX \
	BFLB_PINMUX(26, uart1, rx, periph)

/* gpio26_pwm_ch1 */
#define GPIO26_PWM_CH1 \
	BFLB_PINMUX(26, pwm, ch1, periph)

/* gpio26_cam_pix_dat7 */
#define GPIO26_CAM_PIX_DAT7 \
	BFLB_PINMUX(26, cam, pix_dat7, periph)

/* gpio26_jtag_tck */
#define GPIO26_JTAG_TCK \
	BFLB_PINMUX(26, jtag, tck, periph)

/* gpio26_fem_gpio1 */
#define GPIO26_FEM_GPIO1 \
	BFLB_PINMUX(26, fem, gpio1, periph)

/* gpio26_mii_rxerr */
#define GPIO26_MII_RXERR \
	BFLB_PINMUX(26, mii, rxerr, periph)

/* gpio26_qdec2_led */
#define GPIO26_QDEC2_LED \
	BFLB_PINMUX(26, qdec2, led, periph)

/* gpio27_flash2_clk */
#define GPIO27_FLASH2_CLK \
	BFLB_PINMUX(27, flash2, clk, periph)

/* gpio27_i2s_di */
#define GPIO27_I2S_DI \
	BFLB_PINMUX(27, i2s, di, periph)

/* gpio27_spi_sclk */
#define GPIO27_SPI_SCLK \
	BFLB_PINMUX(27, spi, sclk, periph)

/* gpio27_i2c_sda */
#define GPIO27_I2C_SDA \
	BFLB_PINMUX(27, i2c, sda, periph)

/* gpio27_uart0_rts */
#define GPIO27_UART0_RTS \
	BFLB_PINMUX(27, uart0, rts, periph)

/* gpio27_uart0_cts */
#define GPIO27_UART0_CTS \
	BFLB_PINMUX(27, uart0, cts, periph)

/* gpio27_uart0_tx */
#define GPIO27_UART0_TX \
	BFLB_PINMUX(27, uart0, tx, periph)

/* gpio27_uart0_rx */
#define GPIO27_UART0_RX \
	BFLB_PINMUX(27, uart0, rx, periph)

/* gpio27_uart1_rts */
#define GPIO27_UART1_RTS \
	BFLB_PINMUX(27, uart1, rts, periph)

/* gpio27_uart1_cts */
#define GPIO27_UART1_CTS \
	BFLB_PINMUX(27, uart1, cts, periph)

/* gpio27_uart1_tx */
#define GPIO27_UART1_TX \
	BFLB_PINMUX(27, uart1, tx, periph)

/* gpio27_uart1_rx */
#define GPIO27_UART1_RX \
	BFLB_PINMUX(27, uart1, rx, periph)

/* gpio27_pwm_ch2 */
#define GPIO27_PWM_CH2 \
	BFLB_PINMUX(27, pwm, ch2, periph)

/* gpio27_jtag_tdo */
#define GPIO27_JTAG_TDO \
	BFLB_PINMUX(27, jtag, tdo, periph)

/* gpio27_fem_gpio2 */
#define GPIO27_FEM_GPIO2 \
	BFLB_PINMUX(27, fem, gpio2, periph)

/* gpio27_mii_tx_en */
#define GPIO27_MII_TX_EN \
	BFLB_PINMUX(27, mii, tx_en, periph)

/* gpio27_qdec0_a */
#define GPIO27_QDEC0_A \
	BFLB_PINMUX(27, qdec0, a, periph)

/* gpio28_flash2_d0 */
#define GPIO28_FLASH2_D0 \
	BFLB_PINMUX(28, flash2, d0, periph)

/* gpio28_i2s_bclk */
#define GPIO28_I2S_BCLK \
	BFLB_PINMUX(28, i2s, bclk, periph)

/* gpio28_spi_mosi */
#define GPIO28_SPI_MOSI \
	BFLB_PINMUX(28, spi, mosi, periph)

/* gpio28_i2c_scl */
#define GPIO28_I2C_SCL \
	BFLB_PINMUX(28, i2c, scl, periph)

/* gpio28_uart0_rts */
#define GPIO28_UART0_RTS \
	BFLB_PINMUX(28, uart0, rts, periph)

/* gpio28_uart0_cts */
#define GPIO28_UART0_CTS \
	BFLB_PINMUX(28, uart0, cts, periph)

/* gpio28_uart0_tx */
#define GPIO28_UART0_TX \
	BFLB_PINMUX(28, uart0, tx, periph)

/* gpio28_uart0_rx */
#define GPIO28_UART0_RX \
	BFLB_PINMUX(28, uart0, rx, periph)

/* gpio28_uart1_rts */
#define GPIO28_UART1_RTS \
	BFLB_PINMUX(28, uart1, rts, periph)

/* gpio28_uart1_cts */
#define GPIO28_UART1_CTS \
	BFLB_PINMUX(28, uart1, cts, periph)

/* gpio28_uart1_tx */
#define GPIO28_UART1_TX \
	BFLB_PINMUX(28, uart1, tx, periph)

/* gpio28_uart1_rx */
#define GPIO28_UART1_RX \
	BFLB_PINMUX(28, uart1, rx, periph)

/* gpio28_pwm_ch3 */
#define GPIO28_PWM_CH3 \
	BFLB_PINMUX(28, pwm, ch3, periph)

/* gpio28_cam_pix_dat4 */
#define GPIO28_CAM_PIX_DAT4 \
	BFLB_PINMUX(28, cam, pix_dat4, periph)

/* gpio28_jtag_tms */
#define GPIO28_JTAG_TMS \
	BFLB_PINMUX(28, jtag, tms, periph)

/* gpio28_fem_gpio3 */
#define GPIO28_FEM_GPIO3 \
	BFLB_PINMUX(28, fem, gpio3, periph)

/* gpio28_mii_rx_dv */
#define GPIO28_MII_RX_DV \
	BFLB_PINMUX(28, mii, rx_dv, periph)

/* gpio28_qdec0_b */
#define GPIO28_QDEC0_B \
	BFLB_PINMUX(28, qdec0, b, periph)

#endif /* DT_BINDINGS_PINCTRL_BFLB_BL704X_PINCTRL_H_ */
