/*
 * Autogenerated file
 * Copyright (c) 2025 BFLB Pinctrl Generator <nandojve@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef DT_BINDINGS_PINCTRL_BFLB_BL602X_PINCTRL_H_
#define DT_BINDINGS_PINCTRL_BFLB_BL602X_PINCTRL_H_

#include <dt-bindings/pinctrl/bl60x-pinctrl.h>
#include <dt-bindings/pinctrl/bflb-common-pinctrl.h>

/* gpio0_sdio_clk */
#define GPIO0_SDIO_CLK \
	BFLB_PINMUX_XXX(0, sdio, clk, periph)

/* gpio0_flash_d1 */
#define GPIO0_FLASH_D1 \
	BFLB_PINMUX_XXX(0, flash, d1, periph)

/* gpio0_spi_mosi */
#define GPIO0_SPI_MOSI \
	BFLB_PINMUX_XXX(0, spi, mosi, periph)

/* gpio0_i2c_scl */
#define GPIO0_I2C_SCL \
	BFLB_PINMUX_XXX(0, i2c, scl, periph)

/* gpio0_uart0_rts */
#define GPIO0_UART0_RTS \
	BFLB_PINMUX_XXX(0, uart0, rts, periph)

/* gpio0_uart0_cts */
#define GPIO0_UART0_CTS \
	BFLB_PINMUX_XXX(0, uart0, cts, periph)

/* gpio0_uart0_tx */
#define GPIO0_UART0_TX \
	BFLB_PINMUX_XXX(0, uart0, tx, periph)

/* gpio0_uart0_rx */
#define GPIO0_UART0_RX \
	BFLB_PINMUX_XXX(0, uart0, rx, periph)

/* gpio0_uart1_rts */
#define GPIO0_UART1_RTS \
	BFLB_PINMUX_XXX(0, uart1, rts, periph)

/* gpio0_uart1_cts */
#define GPIO0_UART1_CTS \
	BFLB_PINMUX_XXX(0, uart1, cts, periph)

/* gpio0_uart1_tx */
#define GPIO0_UART1_TX \
	BFLB_PINMUX_XXX(0, uart1, tx, periph)

/* gpio0_uart1_rx */
#define GPIO0_UART1_RX \
	BFLB_PINMUX_XXX(0, uart1, rx, periph)

/* gpio0_pwm_ch0 */
#define GPIO0_PWM_CH0 \
	BFLB_PINMUX_XXX(0, pwm, ch0, periph)

/* gpio0_fem_gpio0 */
#define GPIO0_FEM_GPIO0 \
	BFLB_PINMUX_XXX(0, fem, gpio0, periph)

/* gpio0_jtag_tms */
#define GPIO0_JTAG_TMS \
	BFLB_PINMUX_XXX(0, jtag, tms, periph)

/* gpio0_atest_in */
#define GPIO0_ATEST_IN \
	BFLB_PINMUX_XXX(0, atest, in, analog)

/* gpio1_sdio_cmd */
#define GPIO1_SDIO_CMD \
	BFLB_PINMUX_XXX(1, sdio, cmd, periph)

/* gpio1_flash_d2 */
#define GPIO1_FLASH_D2 \
	BFLB_PINMUX_XXX(1, flash, d2, periph)

/* gpio1_spi_miso */
#define GPIO1_SPI_MISO \
	BFLB_PINMUX_XXX(1, spi, miso, periph)

/* gpio1_i2c_sda */
#define GPIO1_I2C_SDA \
	BFLB_PINMUX_XXX(1, i2c, sda, periph)

/* gpio1_uart0_rts */
#define GPIO1_UART0_RTS \
	BFLB_PINMUX_XXX(1, uart0, rts, periph)

/* gpio1_uart0_cts */
#define GPIO1_UART0_CTS \
	BFLB_PINMUX_XXX(1, uart0, cts, periph)

/* gpio1_uart0_tx */
#define GPIO1_UART0_TX \
	BFLB_PINMUX_XXX(1, uart0, tx, periph)

/* gpio1_uart0_rx */
#define GPIO1_UART0_RX \
	BFLB_PINMUX_XXX(1, uart0, rx, periph)

/* gpio1_uart1_rts */
#define GPIO1_UART1_RTS \
	BFLB_PINMUX_XXX(1, uart1, rts, periph)

/* gpio1_uart1_cts */
#define GPIO1_UART1_CTS \
	BFLB_PINMUX_XXX(1, uart1, cts, periph)

/* gpio1_uart1_tx */
#define GPIO1_UART1_TX \
	BFLB_PINMUX_XXX(1, uart1, tx, periph)

/* gpio1_uart1_rx */
#define GPIO1_UART1_RX \
	BFLB_PINMUX_XXX(1, uart1, rx, periph)

/* gpio1_pwm_ch1 */
#define GPIO1_PWM_CH1 \
	BFLB_PINMUX_XXX(1, pwm, ch1, periph)

/* gpio1_fem_gpio1 */
#define GPIO1_FEM_GPIO1 \
	BFLB_PINMUX_XXX(1, fem, gpio1, periph)

/* gpio1_jtag_tdi */
#define GPIO1_JTAG_TDI \
	BFLB_PINMUX_XXX(1, jtag, tdi, periph)

/* gpio1_atest_ip */
#define GPIO1_ATEST_IP \
	BFLB_PINMUX_XXX(1, atest, ip, analog)

/* gpio3_sdio_dat1 */
#define GPIO3_SDIO_DAT1 \
	BFLB_PINMUX_XXX(3, sdio, dat1, periph)

/* gpio3_spi_sclk */
#define GPIO3_SPI_SCLK \
	BFLB_PINMUX_XXX(3, spi, sclk, periph)

/* gpio3_i2c_sda */
#define GPIO3_I2C_SDA \
	BFLB_PINMUX_XXX(3, i2c, sda, periph)

/* gpio3_uart0_rts */
#define GPIO3_UART0_RTS \
	BFLB_PINMUX_XXX(3, uart0, rts, periph)

/* gpio3_uart0_cts */
#define GPIO3_UART0_CTS \
	BFLB_PINMUX_XXX(3, uart0, cts, periph)

/* gpio3_uart0_tx */
#define GPIO3_UART0_TX \
	BFLB_PINMUX_XXX(3, uart0, tx, periph)

/* gpio3_uart0_rx */
#define GPIO3_UART0_RX \
	BFLB_PINMUX_XXX(3, uart0, rx, periph)

/* gpio3_uart1_rts */
#define GPIO3_UART1_RTS \
	BFLB_PINMUX_XXX(3, uart1, rts, periph)

/* gpio3_uart1_cts */
#define GPIO3_UART1_CTS \
	BFLB_PINMUX_XXX(3, uart1, cts, periph)

/* gpio3_uart1_tx */
#define GPIO3_UART1_TX \
	BFLB_PINMUX_XXX(3, uart1, tx, periph)

/* gpio3_uart1_rx */
#define GPIO3_UART1_RX \
	BFLB_PINMUX_XXX(3, uart1, rx, periph)

/* gpio3_pwm_ch3 */
#define GPIO3_PWM_CH3 \
	BFLB_PINMUX_XXX(3, pwm, ch3, periph)

/* gpio3_fem_gpio3 */
#define GPIO3_FEM_GPIO3 \
	BFLB_PINMUX_XXX(3, fem, gpio3, periph)

/* gpio3_jtag_tdo */
#define GPIO3_JTAG_TDO \
	BFLB_PINMUX_XXX(3, jtag, tdo, periph)

/* gpio3_atest_qp */
#define GPIO3_ATEST_QP \
	BFLB_PINMUX_XXX(3, atest, qp, analog)

#endif /* DT_BINDINGS_PINCTRL_BFLB_BL602X_PINCTRL_H_ */
