/*
 * Autogenerated file
 * Copyright (c) 2025 BFLB Pinctrl Generator <nandojve@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef DT_BINDINGS_PINCTRL_BFLB_BL60X_PINCTRL_H_
#define DT_BINDINGS_PINCTRL_BFLB_BL60X_PINCTRL_H_

#define BFLB_PINMUX_FUN_INST_sdio                       0x0001
#define BFLB_PINMUX_FUN_INST_flash                      0x0002
#define BFLB_PINMUX_FUN_INST_spi                        0x0004
#define BFLB_PINMUX_FUN_INST_i2c                        0x0006
#define BFLB_PINMUX_FUN_INST_uart0                      0x0007
#define BFLB_PINMUX_FUN_INST_uart1                      0x0107
#define BFLB_PINMUX_FUN_INST_pwm                        0x0008
#define BFLB_PINMUX_FUN_INST_fem                        0x0009
#define BFLB_PINMUX_FUN_INST_analog                     0x000a
#define BFLB_PINMUX_FUN_INST_swgpio                     0x000b
#define BFLB_PINMUX_FUN_INST_gpio                       0x000b
#define BFLB_PINMUX_FUN_INST_jtag                       0x000e

#define BFLB_PINMUX_SIGNAL_clk                          0x00
#define BFLB_PINMUX_SIGNAL_cts                          0x01
#define BFLB_PINMUX_SIGNAL_ch0                          0x00
#define BFLB_PINMUX_SIGNAL_cmd                          0x00
#define BFLB_PINMUX_SIGNAL_ch1                          0x00
#define BFLB_PINMUX_SIGNAL_ch2                          0x00
#define BFLB_PINMUX_SIGNAL_ch3                          0x00
#define BFLB_PINMUX_SIGNAL_d1                           0x00
#define BFLB_PINMUX_SIGNAL_d2                           0x00
#define BFLB_PINMUX_SIGNAL_dat0                         0x00
#define BFLB_PINMUX_SIGNAL_d3                           0x00
#define BFLB_PINMUX_SIGNAL_dat1                         0x00
#define BFLB_PINMUX_SIGNAL_gpio0                        0x00
#define BFLB_PINMUX_SIGNAL_gpio1                        0x00
#define BFLB_PINMUX_SIGNAL_gpio2                        0x00
#define BFLB_PINMUX_SIGNAL_gpio3                        0x00
#define BFLB_PINMUX_SIGNAL_in                           0x00
#define BFLB_PINMUX_SIGNAL_ip                           0x00
#define BFLB_PINMUX_SIGNAL_mosi                         0x00
#define BFLB_PINMUX_SIGNAL_miso                         0x00
#define BFLB_PINMUX_SIGNAL_qn                           0x00
#define BFLB_PINMUX_SIGNAL_qp                           0x00
#define BFLB_PINMUX_SIGNAL_rts                          0x00
#define BFLB_PINMUX_SIGNAL_rx                           0x03
#define BFLB_PINMUX_SIGNAL_scl                          0x00
#define BFLB_PINMUX_SIGNAL_sda                          0x00
#define BFLB_PINMUX_SIGNAL_ss                           0x00
#define BFLB_PINMUX_SIGNAL_sclk                         0x00
#define BFLB_PINMUX_SIGNAL_tx                           0x02
#define BFLB_PINMUX_SIGNAL_tms                          0x00
#define BFLB_PINMUX_SIGNAL_tdi                          0x00
#define BFLB_PINMUX_SIGNAL_tck                          0x00
#define BFLB_PINMUX_SIGNAL_tdo                          0x00

#endif /* DT_BINDINGS_PINCTRL_BFLB_BL60X_PINCTRL_H_ */
